### ISSUE TITLE
"Preparing" » "Ready" state fail on both Print and Export

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1018]
## Description
When I do not have a USB drive already plugged-in to a USB port, and I go to export a file... the window does not update the H1 text, when the upper-left spinner transitions to the icon. While I do not have a supported printer, for kicks I also tried the same with Print, and the same happened.

Note: This does not happen when a drive _is_ already plugged-in. Since I do not have a supported printer, I could not try that route.

![image](https://user-images.githubusercontent.com/8262612/77705527-2163b880-6f7d-11ea-8e2b-4cabb5ddaf33.png)

![image](https://user-images.githubusercontent.com/8262612/77705637-769fca00-6f7d-11ea-9a2b-a4001a2a7477.png)

## STR
1. On a non-prod machine w/ the 25 March nightly running, ensure no external drives are plugged-in.
2. Click "Print" or "Export" when nothing is plugged in.

## Expected
After preflight, the spinner changes to an icon and the text changes from "Preparing" to "Ready"

**Comment by eloquence** [comment]
This seems to be a variant of #990 under different conditions. Once we have a clear repro I'm inclined to close and consolidate.

**Comment by eloquence** [comment]
Closing in favor of #990, but will note there that we should investigate additional STRs as well.
