### ISSUE TITLE
No "Active State" button spinner on "Insert Encrypted Drive"

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1019]
## Problem
I go to Export a file, without a drive of any kind plugged in. When I go to plug in a drive, either a correctly encrypted drive or a dud drive, or if I don't plug in any drive and just hit "Continue," there should be an `active state` whereby the button gets a 'lil spinner on it and goes grey. This does not happen. The button, instead, does nothing.

![image](https://user-images.githubusercontent.com/8262612/77705885-12c9d100-6f7e-11ea-9fbb-c4616022f2f2.png)

# STR
1. Open client on a non-prod machine with the 25 March nightly running
2. Go to Export a file w/o a drive of any kind plugged in
3. When prompted to insert a drive...
  a. Click "Continue" w/o any drive there
  b. Insert a dud drive and click "Continue"
  c. Insert a correctly provisioned drive and click "Continue"
4. Observe.

## Expected
A happy spinner `active state` on the button, anytime I hit that "Continue" button—before it either progresses to the next screen, or bounces-back with an error.

**Comment by eloquence** [comment]
Adding this to the near-term backlog; I agree this is confusing behavior (IMO more severe from a UX perspective than the login issue you identified in #1038, since it happens even on first try).

**Comment by eloquence** [comment]
@ninavizz @creviera and I discussed this again briefly in a mini-backlog review today, and we agreed that it's still a high priority UX papercut we should address soon. 

To recap:
- The original issue is still valid: There is no active state on the "Continue" button on the "Insert encrypted USB drive" stage of the export flow.
- We do have an existing active state spinner animation on the button for the _subsequent_ screen, i.e. after the user enters their passphrase for a correctly provisioned drive. We could potentially re-use that spinner and behavior for the "Continue" button.
- After inserting a drive and clicking "Continue", the Client displays the following error if the device is not usable: "Either the drive is not encrypted or there is something else wrong with it."
- The Client displays _no_ error message if you press "Continue" _without_ a USB drive being inserted. This is the worst case: no active state, no error.

I think the open Qs are:
- Does it make sense to use the same active state style for the "Continue" button as we are using on the subsequent screen?
- What errors can arise on the "Insert encrypted USB drive" screen, and which ones are currently handled?
- What should the error message be for errors that are not handled yet?
