### ISSUE TITLE
Long messages are truncated in conversation view

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-client#1028]
Sometimes long messages are truncated in the conversation view. The first two messages in this thread are long messages; a long reply is also truncated, and a long reply with line breaks is also truncated.

![multiline_message](https://user-images.githubusercontent.com/22777700/77966868-f39aae80-72b1-11ea-8678-1bd9767f5fc0.png)

**Comment by rocodes** [comment]
Dupe of #998--closing

**Comment by creviera** [comment]
Just want to mention that this screenshot also shows the File widget alignment issue: https://github.com/freedomofpress/securedrop-client/issues/694
