### ISSUE TITLE
Set max size on SpeechBubble

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#105]
Right now if there are only one or two messages, the conversation bubbles expand to the entire window:

![screen shot 2018-11-05 at 4 20 22 pm](https://user-images.githubusercontent.com/7832803/48035040-cf678c00-e116-11e8-8556-0e96f6a7ae78.png)

We should set a max size and allow there to be a fair bit of whitespace if there are insufficient messages to fill the conversation view.

**Comment by ntoll** [comment]
OK... the solution is probably to add an invisible "fill / padding" widget that'll push the speech bubbles up the screen. When we don't need the padding, remove it. etc...

**Comment by redshiftzero** [comment]
@nightwarrior-xxx is going to take a look at this one!

**Comment by nightwarrior-xxx** [comment]
@eloquence @redshiftzero   Is this ok ? Or I have to reduce some space between messages i.e between two bubbles
![securedrop-client](https://user-images.githubusercontent.com/32111606/50042827-4f2a3400-008f-11e9-90c6-9be01223e9d5.png)

**Comment by ninavizz** [comment]
The spacing between different messages from the same user in the same session should be around 10-20px; spacing between different groups of messages sent in different sessions, and a complete set of spacing specs, will be posted in its own issue within a few weeks. 

Neither are significantly critical until VisDe Issues get drafted, but for interim evaluation of the client it'd be nice if more messages could be visible to users w/in the pane view w/o scrolling. I'll let @eloquence make the call on whether or not this should be considered for this issue to be completed, tho. :)

**Comment by eloquence** [comment]
@nightwarrior-xxx Please limit yourself to the issue of reducing the spacing between all messages to 10-20 px. Ignore what "session" the messages were sent in as this introduces significant complexity we'll handle in follow-up issues (we don't have a firmly defined concept of a session yet).
