### ISSUE TITLE
db migration testing

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#1068]
On SecureDrop server we have alembic db migration tests, see this documentation for background/explanation: https://docs.securedrop.org/en/release-1.2.2/development/database_migrations.html?highlight=alembic#unit-testing-migrations

We added the same test runner [here](https://github.com/freedomofpress/securedrop-client/blob/master/tests/test_alembic.py) but: we haven't been adding the corresponding tests to ensure that the database updates cleanly. I've found these tests pretty useful, so we could start writing them to catch issues with database migrations (otherwise we need to manually upgrade the database from `master` to test, which we could add to the PR checklist for now).

**Comment by eloquence** [comment]
@creviera @emkll I think this would be a good preparatory change in support of read/unread, which will almost certainly require a client DB migration, and other near term new features. What do you think?

**Comment by creviera** [comment]
Yes, this should come first, before https://github.com/freedomofpress/securedrop-client/issues/1068 and the migration to move update null `journalist_id`s in the `replies` table to that of the deleted user account. 

Thinking about order of operations, ideally we would start by adding db migration test infrastructure. Then we could add the change to prepopulate the user db with a "deleted" user account at setup time. Next we can add all of our migrations:
* https://github.com/freedomofpress/securedrop-client/issues/1068
* the migration to move update null `journalist_id`s in the `replies` table to that of the deleted user account
* adding seen tables without allowing null `journalist_id`s

**Comment by eloquence** [comment]
I've tentatively added this to the next sprint candidates, but per the above it may make sense to start work on this still in the current sprint (ending Thursday), and move #1149 (which _is_ in the current sprint) to the next one.
