### ISSUE TITLE
Support 1366x768 screen resolution

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1074]
We've heard reports from a couple of users that the whole client doesn't fit on their Qubes desktop. In a quick test outside Qubes, the smallest I can make the window is `1405 x 630`. We should investigate if we can have it scale below `1366` horizontally (`1366 x 768` is a common resolution) or even below 1280 (to support `1280 x 1024`).

**Comment by eloquence** [comment]
Testing in Qubes I can confirm that the whole client does indeed not fit onto the screen horizontally in 1368x768.

**Comment by ninavizz** [comment]
This is a video of me reproducing the issue. It fits nicely when the screen is maximized, but when the screen is un-maximized it goes down too far... so I cannot grab the bottom-right corner. Out of view from the screen, is my clicking the icons in the Window in the top-right. The window is showing with my preferred _Atlanta_ theme, on the chance its frame edges look oddly thin—that'd be why.

BTW, video here is on FPF GDrive, so only folks w/in FPF or specifically invited to view it, can have access: https://drive.google.com/drive/folders/1AA5y1NByT9GKonACUPy7djpPKq0jFlgk

**Comment by creviera** [comment]
I see, yeah we can default to maximizing to full screen and reduce our supported min window size.

**Comment by conorsch** [comment]
Updated the screen resolution mentioned in the title 1280x1024 -> 1366x768, since the latter is a common configuration in many Thinkpads, including the T480 which we currently recommend, as well as other Qubes-specific models such as https://insurgo.ca/produit/qubesos-certified-privacybeast_x230-reasonably-secured-laptop/
