### ISSUE TITLE
Add documentation, tests, and cleanup stylesheets

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1078]
# Description

The following issues around stylesheets in Qt could be avoided if we have documentation on how to set stylesheets in the client, remove "bad" examples from the code, and add stylesheet tests to our manual test plan or test suite.

* [upstream stylesheet bug causing segfault](https://github.com/freedomofpress/securedrop-client/issues/273), see https://github.com/freedomofpress/securedrop-client/pull/254#issuecomment-472216744 for context
* [switching out CSS for different reply states](https://github.com/freedomofpress/securedrop-client/commit/53b123f7512144e205dd072cf4185923d0cd25da)
* [switching out CSS for different message states](https://github.com/freedomofpress/securedrop-client/pull/1059/files#r412409560)
* [segfault when making QLabel selectable](https://github.com/freedomofpress/securedrop-client/commit/490323651bee169d67fbf5fa8e14752cfd90f9d4), see https://github.com/freedomofpress/securedrop-client/pull/1063/commits/22e1b3490d8916e62ad7983e5a3d7a181e4763d0 for our solution

**Comment by creviera** [comment]
> * [segfault when making QLabel selectable](https://github.com/freedomofpress/securedrop-client/commit/490323651bee169d67fbf5fa8e14752cfd90f9d4), see https://github.com/freedomofpress/securedrop-client/pull/1063/commits/22e1b3490d8916e62ad7983e5a3d7a181e4763d0 for our solution

I haven't had much time to look into this issue but here's an interesting finding:

* [this segfaults](https://github.com/freedomofpress/securedrop-client/files/4566722/thissegfaults.txt)
* [this does not segfault](https://github.com/freedomofpress/securedrop-client/files/4566719/thisworks.txt), see screenshot:
![Screenshot from 2020-05-01 16-54-16](https://user-images.githubusercontent.com/4522213/80849585-a1102300-8bcc-11ea-8d32-19f478550f08.png)

As you can see, we can set a stylesheet on the `ConversationView` and insert widgets that have the `TextSelectableByMouse` flag set into the layout of the child widget of the `QScrollArea`. If we insert these widgets from the `update_conversation` method or its submethods, e.g. `add_message`, then we see the segfault.

More to come next week!

**Comment by creviera** [comment]
In case that's not clear, this works:

```py
class ConversationView(QWidget):

    CSS = '''
    #container {
        background: #f3f5f9;
    }
    #scroll {
        border: 0;
        background: #f3f5f9;
    }
    '''
    
	... [CODE TRUNCATED] ...


    def __init__(self, source_db_object: Source, controller: Controller):

	... [CODE TRUNCATED] ...

        self.setStyleSheet(self.CSS)

        self.container = QWidget()
        self.container.setObjectName('container')
        self.conversation_layout = QVBoxLayout()
        self.container.setLayout(self.conversation_layout)
        self.conversation_layout.setContentsMargins(self.MARGIN_LEFT, 0, self.MARGIN_RIGHT, 0)
        self.conversation_layout.setSpacing(0)
        self.container.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.scroll = QScrollArea()
        self.scroll.setObjectName('scroll')
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll.setWidget(self.container)
        self.scroll.setWidgetResizable(True)

	... [CODE TRUNCATED] ...

        label = QLabel('beep')
        label.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.conversation_layout.insertWidget(0, label, alignment=Qt.AlignLeft)
        main_layout.addWidget(self.scroll)
```

this doesn't work:

```py
class ConversationView(QWidget):

    CSS = '''
    #container {
        background: #f3f5f9;
    }
    #scroll {
        border: 0;
        background: #f3f5f9;
    }
    '''
    
	... [CODE TRUNCATED] ...


    def __init__(self, source_db_object: Source, controller: Controller):

	... [CODE TRUNCATED] ...

        self.setStyleSheet(self.CSS)

        self.container = QWidget()
        self.container.setObjectName('container')
        self.conversation_layout = QVBoxLayout()
        self.container.setLayout(self.conversation_layout)
        self.conversation_layout.setContentsMargins(self.MARGIN_LEFT, 0, self.MARGIN_RIGHT, 0)
        self.conversation_layout.setSpacing(0)
        self.container.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.scroll = QScrollArea()
        self.scroll.setObjectName('scroll')
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll.setWidget(self.container)
        self.scroll.setWidgetResizable(True)

	... [CODE TRUNCATED] ...

        self.conversation_layout.insertWidget(0, label, alignment=Qt.AlignLeft)
        main_layout.addWidget(self.scroll)

	self.update_conversation(self.source.collection)

    def update_conversation(self, collection: list) -> None:
        label = QLabel('beep')
        label.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.conversation_layout.insertWidget(0, label, alignment=Qt.AlignLeft)
```

**Comment by eloquence** [comment]
Deferring to a future sprint in favor of closing out the other docs task we already have a PR for, https://github.com/freedomofpress/securedrop-client/pull/1089

**Comment by creviera** [comment]
> Add documentation, tests, and cleanup stylesheets

The bulk of this work to create tests and cleanup/refactor how we style the gui happened more than a month ago, so I went ahead and started a wiki page around [project organization](https://github.com/freedomofpress/securedrop-client/wiki/Project-Patterns) so that we can close this out.
