### ISSUE TITLE
Document process for compiling Qt from source & known major upstream issues

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1084]
We've agreed that we'd like to
- [ ] document the process for compiling Qt from source in the development environment
- [ ] document known Qt upstream issues that have bitten or could bite us during development -- this should include the issue described in #1078 but may also cover other issues.

**Comment by creviera** [comment]
see https://github.com/freedomofpress/securedrop-client/issues/273#issuecomment-625915894, https://github.com/freedomofpress/securedrop-client/pull/1082, and https://github.com/freedomofpress/securedrop-client/issues/1078

**Comment by zenmonkeykstop** [comment]
Closing, won't fix. We haven't needed it in recent memory.
