### ISSUE TITLE
Add widget style border tests 

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#1096]
# Description

We should have some kind of test that asserts borders look the way we expect them to look, e.g.  we should assert 'border: 2px solid rgba(42, 49, 157, 0.4);' for button_box when disabled.

Reference:

https://code.woboq.org/qt5/qtbase/src/widgets/styles/qstylesheetstyle.cpp.html#_ZN21QStyleSheetBorderDataC1EPiP6QBrushPN4QCss11BorderStyleEP5QSize

Follow up from: https://github.com/freedomofpress/securedrop-client/pull/1082#issue-413254749

**Comment by zenmonkeykstop** [comment]
Closing - looking to move toward GUI testing likely with OpenQA, so we may not need it.
