### ISSUE TITLE
Finish CSS stylesheet tests

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#1097]
# Description

https://github.com/freedomofpress/securedrop-client/pull/1082#issue-413254749 added stylesheet tests but we still need tests to cover:

* padding (note: we have tests for margins as well as for min and max height and width)
* borders (how do we get a border or rectangle outline attribute in Qt?)

Reference:

https://doc.qt.io/archives/qt-4.8/stylesheet-customizing.html

Follow up from: https://github.com/freedomofpress/securedrop-client/pull/1082#issue-413254749

**Comment by creviera** [comment]
More details on assertions we need:
* ```py'#05a6fe' == download_button.palette().color(QPalette.Foreground).name()`
* For modal dialog button: 
  ```py
       assert border: 2px solid #f1f1f6;
       assert (12, 0, 0, 0) == continue_button.getContentsMargins()
       assert 40 == continue_button.height()
       assert padding-left: 20px;
       assert padding-right: 20px;
   ```

**Comment by zenmonkeykstop** [comment]
Taking a new approach to GUI testing with workstation CI, which will likely make this overkill. Closing.
