### ISSUE TITLE
Login window title bar missing when starting client from qubes sd updater

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1106]
# Description

After running the updater in qubes today, I noticed that the client login window's titlebar was missing. This only happened when the client was started after the updater finished running. The issue may have to do with how the updater opens the client, but perhaps this can be fixed by setting certain window flags on the login window.

**Comment by eloquence** [comment]
> This only happened when the client was started after the updater finished running. 

Did the issue disappear after some time, or did the client lose its window title for the entire remainder of the session?

(I've observed what may be the same or a similar issue, but it only lasted for a few seconds.)

**Comment by eloquence** [comment]
(Probably intermittent, not able to reproduce yet.)

**Comment by creviera** [comment]
This happened again for me today directly after the updater ran. Moving this issue into https://github.com/freedomofpress/securedrop-workstation because it's most likely that the solution will need to be made in how we run the client from the updater: https://github.com/freedomofpress/securedrop-workstation/blob/52d5c7d593b244701cfc221d6a01100bf985f5c1/launcher/sdw_updater_gui/UpdaterApp.py#L20
