### ISSUE TITLE
Part of the client window is hidden when resized

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1109]
# Description

When you click the resize button in the client window titlebar, the application doesn't fit neatly within the screen. If you click it again it is maximized properly where only the top window titlebar shows (not the Qubes window border).

You can best see this by following these steps in Qubes:

1. Login into the client
2. Select a source
3. Click the resize button in the titlebar

Expected

To see the full client window, including the Qubes border.

Actual

The right Qubes border is hidden and part of the bottom of the client is hidden.

## See also
Nina's comment here observing the same behavior: https://github.com/freedomofpress/securedrop-client/issues/1074#issuecomment-620171589

*edited by @eloquence 2020-07-01*

**Comment by eloquence** [comment]
Is the same as #1118, @creviera ?
