### ISSUE TITLE
Optimize reply placeholder width

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1119]
This screenshot shows how, at a lower widow size (which will be supported once #1103 is merged), the "Compose a reply to" placeholder can be truncated for long source designations (the full codename is `organizational implementation`).

![Screenshot from 2020-06-26 14-42-40](https://user-images.githubusercontent.com/213636/85903486-4c97b700-b7bb-11ea-9b08-8feb6ddb707b.png)

We should elide those codenames (#1120), but we should also optimize the width of the placeholder, which appears to currently be cut off where the "Send" button begins, even though it is always rendered above it.

**Comment by eloquence** [comment]
Unfortunately I don't see a simple way to avoid this issue. This screenshot illustrates the problem:

![reply-layout](https://user-images.githubusercontent.com/213636/90300017-636a9980-de4d-11ea-9df0-c5fe413c69ea.png)

The textbox takes up as much space as is available, and the placeholder text is a child object of the text box. The only reasonable solution I see is to try to force the placeholder text to float on top of the textbox, instead of having it be layouted as a child object. That may add too much complexity to be worthwhile, and eliding the placeholder text (#1120) seems to get us bigger bang for the buck.

**Comment by ninavizz** [comment]
I'm also not keen on what looks like a tabular layout, with the airplane in its own column? 
Does QT do z-axis type layering of objects?

(...she says, keenly watching the hardworking dev team hold it together as to not wither in tears of frustration after having spent scores of hours just trying to work within QTs constraints so that it does not implode)

**Comment by eloquence** [comment]
There are a few different strategies Allie and I have discussed for this, but for now we're deferring it in favor of #1120. It would still be nice to eventually solve to get those extra pixels.

**Comment by eloquence** [comment]
With #1145 merged, upon consideration, I'd nominate to close this; the "..." abbreviation should give us enough space and looks  sufficiently polished, IMO.

**Comment by eloquence** [comment]
Closing per above.
