### ISSUE TITLE
Disable executable scripts in AppVMs other than `sd-app`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1141]
In the current template consolidation plan (https://github.com/freedomofpress/securedrop-workstation/issues/471) we anticipate that the `securedrop-client` package will end up being installed in AppVMs that don't need it, e.g., `sd-proxy`. We want to ensure that the client is not accidentally opened in a VM in which it is not meant to be run. While RPC policies will restrict the proper functioning of the client in any VM other than `sd-app`, we should still prevent it from being run to reduce confusion.

We want to ensure that client-specific configurations and scripts are not installed in those VMs. In addition to MIME types (tracked in https://github.com/freedomofpress/securedrop-debian-packaging/issues/188 and https://github.com/freedomofpress/securedrop-workstation/issues/603), that includes the two executable scripts in the [files folder](https://github.com/freedomofpress/securedrop-client/tree/main/files):

- `securedrop-client`
- `sd-app-qubes-gpg-domain.sh` (sets the `QUBES_GPG_DOMAIN` environment variable used to configure the Qubes GPG wrapper in the [split GPG architecture](https://www.qubes-os.org/doc/split-gpg/))

**Comment by eloquence** [comment]
One option @emkll and I discussed today was to check `hostname` in the VM and exit out if these scripts are invoked in a VM other than `sd-app`.

**Comment by creviera** [comment]
If we enforce app-to-vm execution restrictions, then i want to advocate for a way to easily disable this when running securedrop-workstation in "dev" mode. I used to do development in the sd-managed vms, but now I use a much more stable system of developing client and sdk in a dev vm (not sd-app) and the proxy in a dev vm (not sd-proxy). This also allows us to generate sdk cassettes for api calls over qrexec, see https://github.com/freedomofpress/securedrop-sdk/blob/30a28463270ffc44bfaeb89776e5a4addc9c3e8a/README.md#generating-cassettes-for-api-calls-over-qrexec.

**Comment by eloquence** [comment]
That makes sense -- perhaps we could override the name of the VM via env var, or disable those checks in a dev environment altogether.
