### ISSUE TITLE
Add platform independent file opening

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#115]
We use `QProcess` to open files in a disposable VM using `qvm-open-in-vm`, which is a Qubes-only program. We could use `xdg-open` to open files such that this file open process would also work in Linux, but by always using `qvm-open-in-vm`, we get defense in depth as we will not accidentally open a file in the `sd-app` AppVM if there is a misconfiguration with the mime type handlers in the sd-app VM. 

The problem with this is that now on Mac or Linux, we can't open files. We can apply a patch, like:

```diff
diff --git a/securedrop_client/logic.py b/securedrop_client/logic.py
index 8b5c27c..99bbe4f 100644
@@ -462,6 +462,11 @@ class Client(QObject):
             process = QProcess(self)
             process.start(command, args)
         else:  # pragma: no cover
+            # Running on mac.
+            command = "open"
+            args = [submission_filepath]
+            process = QProcess(self)
+            process.start(command, args)
             # Non Qubes OS. Just log the event for now.
             logger.info('Opening file "{}".'.format(submission_filepath))
``` 

for testing, but this is not convenient for developers. Another approach is in the above diff, to subprocess out to a script that calls `open` (macOS) or `xdg-open`, depending on what the current platform is. This ticket is for implementing that approach (or a better idea if you have one!). 

(Followup to #113)

**Comment by eloquence** [comment]
This is very nice to have for development but not absolutely critical for beta since we must test everything in Qubes anyway, so added to Post-Beta milestone for now.

**Comment by eloquence** [comment]
From 2022-08-22 review with @nathandyer @cfm @gonzalo-bulnes @eloquence: 
In practice, since opening this issue, we've been doing all our testing of opening files in disposable VMs in Qubes, so this has not re-emerged as an urgent need. Closing for now, we can revisit if it turns out to be useful e.g. for CI or author automation.

**Comment by gonzalo-bulnes** [comment]
Loosely related to #1541, which should make swapping QVM for something else easier.
