### ISSUE TITLE
Avoid duplicate downloads of files

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#116]
If a user clicks a file to begin its download, and a user becomes impatient and clicks the file again, using the current logic, another API request to download a file download will occur. We should only have each file downloading once. 

Note that how to implement this cleanly needs some discussion and is related to #100.

Followup from: #113

**Comment by eloquence** [comment]
See also #388 where we have a similar problem.

From a UX perspective, we want the download to transition to an active state when it is underway. This is described in #288. In active "Downloading .." state, the element should no longer be clickable, so it should be impossible to even trigger a duplicate download.

**Comment by eloquence** [comment]
Still the case in current builds, at least I see log lines for jobs being added. I would suggest that we add to @ntoll's punchlist a small fix that prevents the download spinners from being clickable, so we at least have that in if #863 gets deferred.

**Comment by redshiftzero** [comment]
The part of #863 that ensures that duplicate jobs are not added is small, I'll pick it into a separate PR tomorrow (to explain why I put #853 on the post-beta timeline, I don't want to increase the sync frequency now given some of the concurrency issues that were uncovered during QA)

**Comment by ninavizz** [comment]
@redshiftzero #853 was a ticket about login error messaging... not sure how it's relevant to this? Wrong number typed? Yeah, a trip to a sunny beach is probably overdue.
