### ISSUE TITLE
Track in database which files/messages/replies are decrypted

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#117]
Part of #231.

Right now we track whether or not a submission is downloaded in the database (in a column not surprisingly called `is_downloaded`). We should also track which files were successfully decrypted via a column called `is_decrypted`. This should go on both the Submission and Reply tables. 

This is needed for the following situation:

1. User starts download of large file
2. Download finishes
3. Decryption of download fails for some reason

At this point, we don't really want to have to download the entire file again to attempt a decryption, so we should save all files that successfully download as such locally, and then mark whether or not decryption completed (what to do if decryption fails is not a part of this ticket).

**Comment by heartsucker** [comment]
Closed by #262.
