### ISSUE TITLE
Stop download animation on file missing error

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#1173]
# Description

When a file is missing from the server and one attempts to download that file on the client, the download icon is stuck in animation.

# STR

1. add a file submission via the source interface
2. delete that file from the server in /var/lib/securedrop/store
3. start the client and click on the download link next to the file

# Expected

A file missing error message in the top pane and the download icon to stop the animation that makes it look like a download is still in progress.

# Actual

A file missing error message in the top pane and the download icon continues the animation that makes it look like a download is still in progress until you close and reopen the client.

**Comment by zenmonkeykstop** [comment]
Can be closed - download progress changes are in progress which will change this anyway.
