### ISSUE TITLE
Remove paperclip icon or implement paperclip logic

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#119]
The paperclip icon is meant to indicate that a source has associated _documents_ that can be downloaded or have been downloaded. It is currently shown for all sources.

If we can trivially check whether there is >1 downloadable file associated with a source, having the actual check would be nice. If not, we can remove the icon for now.

Note: Until we have server-side deletion of individual documents (which may be a beta feature), the paperclip state will not change during the lifetime of a source.

**Comment by redshiftzero** [comment]
implemented in #157
