### ISSUE TITLE
Active source loses highlight when "Refresh" button is clicked

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#121]
There may be other circumstances when this issue is triggered:

![focusissues](https://user-images.githubusercontent.com/213636/48103860-e2955d00-e1e5-11e8-8f22-2bd1c6bd2c1f.gif)

Stretch, but it's really problematic from a UX perspective, obviously. We can't get rid of the redundant balloons with the source designation at the top until this is fixed. The currently displayed source should _always_ be highlighted.

**Comment by timruffles** [comment]
Will take a look!
