### ISSUE TITLE
add code comments around `base_path` and why we check `is_absolute` right away

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1227]
https://github.com/freedomofpress/securedrop-client/blob/94efe51e2d90545997312fcb8ed1e542f8259f35/securedrop_client/utils.py#L132-L135
> is the `and not filename_or_filepath.is_absolute()` needed here? If the path is absolute, `basepath = filename_or_filepath` and `relative_filepath` will resolve to `filename_or_filepath` . Am I missing something here?
~@emkll

> I comment here to explain why the basepath is used would be helpful, as noted in https://github.com/freedomofpress/securedrop-client-security/pull/1/files#r594692678 , what will `Path().resolve()` return in a production context?
~@emkll

**Comment by creviera** [comment]
any updates here should also be make in the export repo

**Comment by creviera** [comment]
@emkll - do you think we should allow `base_path` to be a relative path? I just want to make sure I understand your concern before I add a comment to explain why we specify `base_path` to be absolute.

**Comment by emkll** [comment]
Per the current code, `base_path` will always be absolute - which IMO is preferable in this scenario. The first comment in the issue I think is outdated and no longer needs to be addressed.

The only documentation to add would be a comment indicating what `base_path` resolves to when calling ` base_path = Path().resolve() `
