### ISSUE TITLE
Distinguish network error from auth error on login

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1237]
Currently we have a single error message that is shown on login:
https://github.com/freedomofpress/securedrop-client/blob/c33f18a211626d4771e732920b93de78703a8dca/securedrop_client/logic.py#L500-L503

This can make the experience of debugging a failed login very frustrating: was it the password, the 2FA code, some VM having issues, the network having issues?

There are security reasons we cannot show details about authentication errors, but we can certainly distinguish the network error case from the auth error case, and should come up with a separate error message, e.g.:

> There was a problem connecting with the SecureDrop server. Please check your network connectivity and try again.

**Comment by eloquence** [comment]
I'll take a stab at this one during the 4/15 sprint.

**Comment by creviera** [comment]
@eloquence this is relevant to how login and logout error handling happens outside of the queue on separate threads https://github.com/freedomofpress/securedrop-client/issues/1129

**Comment by eloquence** [comment]
What I would propose is that we distinguish three error states on the login dialog:
- `AuthError` - likely related to credentials and we can point the user in that direction.
- `ServerConnectionError` or `RequestTimeoutError` - possibly related to Tor or Internet connectivity, and we can point the user in that direction. See 3de06b1154599f5df8a4b1431025b4a6c6be04ad for a stab at this change only.
- Everything else - we show a generic error similar or identical to the current error message.
I've proposed the specific error messages in [this spreadsheet](https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbYQxpO2-U/edit#gid=1724968705). (Thanks to @ninavizz for kicking the language and error cases around with me for a bit.)

Comments or language suggestions appreciated, otherwise planning to proceed along those lines tomorrow. :)

**Comment by creviera** [comment]
overall, sounds good to me, but i don't think we should say "Make sure to use a new two-factor code" in the generalized message if we are already saying that in the AuthError scenario.

**Comment by eloquence** [comment]
Thanks, that makes sense I think (will do some testing of non-AuthError cases w/ re-used 2FA code). I've updated the spreadsheet accordingly.
