### ISSUE TITLE
Submissions are exported twice

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-client#1240]
Recently during Workstation QA, I was surprised to see that files exported to a physical USB stick were exported twice from the client. After tinkering for a bit with package versions, it appears that on my system the latest nightly `securedrop-export_0.2.4-dev-20210315-061408` reliably doubles exports, whereas the prod version 0.2.4 does not. 

Here's an example of the timestamps generated:

```
$ find /media/conor/Transfer/ | sort
/media/conor/Transfer/
/media/conor/Transfer/lost+found
/media/conor/Transfer/sd-export-20210315-161039
/media/conor/Transfer/sd-export-20210315-161039/export_data
/media/conor/Transfer/sd-export-20210315-161039/export_data/surf.mp4
/media/conor/Transfer/sd-export-20210315-161048
/media/conor/Transfer/sd-export-20210315-161048/export_data
/media/conor/Transfer/sd-export-20210315-161048/export_data/surf.mp4
/media/conor/Transfer/sd-export-20210315-161439
/media/conor/Transfer/sd-export-20210315-161439/export_data
/media/conor/Transfer/sd-export-20210315-161439/export_data/wikipedia.jpg
/media/conor/Transfer/sd-export-20210315-161455
/media/conor/Transfer/sd-export-20210315-161455/export_data
/media/conor/Transfer/sd-export-20210315-161455/export_data/wikipedia.jpg
/media/conor/Transfer/sd-export-20210315-161939
/media/conor/Transfer/sd-export-20210315-161939/export_data
/media/conor/Transfer/sd-export-20210315-161939/export_data/surf.mp4
```

There were three (3) export operations performed:

* `surf.mp4` on latest nightly, was doubled
* `wikipedia.jpg` on latest nightly, was doubled
* `surf.mp4` on 0.2.4 prod, was not doubled

**Comment by creviera** [comment]
I'm able to repro every time by pressing "Enter" instead of clicking the "Continue" button, which tells you that our QKeyEvent handler isn't handling the even properly. I'll have a fix shortly and would appreciate some extra eyes on testing in case there's another way to repro the issue.
