### ISSUE TITLE
release makefile target or script

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#126]
this makefile target or script should take a new version and:

* update the version in setup.py
* update the version here: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/__init__.py#L22
* git tag -a the version (when this component goes to prod we'll sign this tag object with the official SecureDrop release key)

One can refer to https://github.com/freedomofpress/securedrop/blob/develop/update_version.sh for inspiration

**Comment by heartsucker** [comment]
Many python projects use this pattern for setting the version in `setup.py` (this one pulled from `flask`). I think we should do the same.

```python
with io.open('flask/__init__.py', 'rt', encoding='utf8') as f:
    version = re.search(r'__version__ = \'(.*?)\'', f.read()).group(1)
```
