### ISSUE TITLE
Add "Earlier files and messages deleted" notice to conversation view

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1260]
When the first item (message, file, reply) in the conversation view is not the first item ever created for that source, we want to show a notice near the top of the conversation view: **"Earlier files and messages deleted".**

## Design

The proposed design for this notice can be found [here](https://scene.zeplin.io/project/5c807ea562f734bd2756b243/screen/6080e14f8240401e04a6e5aa). Pink text is used for annotations and not part of the design.

## Acceptance criteria
- Display the notice when there are items missing at the beginning of a sequence of items in the conversation view.
- Do not display the notice for any other case.
    - Example: Given a sequence **1 2 ~3~ ~4~ ~5~** or **1 2 ~3~ 4** (with strikethrough indicating deletion), the notice should not be displayed.
    - Example: Given a sequence of items **~1~ ~2~ ~3~** (i.e. all items deleted), the notice should not be displayed. (We will show a separate empty state for this case.)

## User Story

As a journalist, I want to know if a message from a source follows a deleted conversation history, so that I can distinguish new from returning sources.

**Comment by creviera** [comment]
this was resolved as part of https://github.com/freedomofpress/securedrop-client/pull/1263
