### ISSUE TITLE
replicate `i18n_tool.py list-translators` in continuous-localization workflow

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1280]
In #1266, as hoped, Weblate's continuous-localization workflow will allow `securedrop-client` to sidestep much of the Git traversal done by `securedrop`'s `i18n_tool.py`.  A notable exception is `i18n_tool.py`'s `list-translators` command, for which there is no Makefile-friendly scripting available:

1. The Weblate UI can generate a ["translator credits" report](https://docs.weblate.org/en/weblate-4.6/devel/reporting.html) that is *exactly* what we want, including reST output.  But since it's a [view](https://github.com/WeblateOrg/weblate/blob/c531080bce7d5fb0e14a8ef19bfcc2aa65d933d7/weblate/trans/views/reports.py#L58) rather than an API endpoint, it can only be (easily) used interactively, not programmatically.
2. [The `changes` API endpoint](https://docs.weblate.org/en/weblate-4.6/api.html#get--api-changes-) will also give us what we want, via e.g. `GET /api/translations/securedrop/securedrop/de/changes/?`[`action=5`](https://github.com/WeblateOrg/weblate/blob/072e18cf9a3f832c117d1f872e537272716fd648/weblate/trans/models/change.py#L177).  But the results are paginated, which makes them nontrivial to use in a Makefile/shell environment.  Even then, *some* Git operation will be required to replicate `list-translators`'s `--since` parameter.
    * **See:**  WeblateOrg/weblate#5459
2. [`wlc changes`](https://docs.weblate.org/en/latest/wlc.html#cmdoption-wlc-arg-changes) very kindly [traverses Weblate's pagination](https://github.com/WeblateOrg/wlc/blob/678a392311838ed73b96f3a812504aec2f03c2a1/wlc/__init__.py#L219-L226), but (a) it can't be parameterized on a starting timestamp and (b) its output doesn't include the `user` field we're most interested in.

I see two worthwhile approaches here:

1. Following (2), write a minimal "get translators [since X]" script here.  In Python, the paginated traversal *is* trivial (à la `wlc changes`).  We could do the Git lookup, too, in pure Python via [Dulwich](https://github.com/dulwich/dulwich).  This script might stay here in `securedrop-client` as the guinea pig for continuous localization; or we might find it useful to factor out and make includable elsewhere, especially if the continuous workflow eventually makes its way back to `securedrop`.
2. Offer to make an upstream contribution towards WeblateOrg/weblate#5459.

Thoughts?  Note that this functionality need not be in place to *use* the continuous-localization workflow, only to properly credit translators in a release.

**Comment by cfm** [comment]
I'm returning to this for freedomofpress/securedrop#6917.

<details>
<summary>Weblate has been able to generate reports like this one since December 2015 (WeblateOrg/weblate@0428d3ca30878f130e48dbb48a2295af056ccee7).</summary>

```
* Catalan

    * Joan Montané <joan@montane.cat> (2)
    * Benet (BennyBeat) R. i Camps <bennybeat@gmail.com> (15)


* Czech

    * Jan Papež <honyczek@centrum.cz> (12)


* Turkish

    * tekrei <tekrei@tutanota.com> (2)


* Icelandic

    * Sveinn í Felli <sv1@fellsnet.is> (3)


* Portuguese (Brazil)

    * Cory Francis Myers <cory@freedom.press> (1)
    * Guilherme <gui.rugai.freire@gmail.com> (7)


* Croatian

    * Milo Ivir <mail@milotype.de> (55)


* German

    * Martin Trebuch <martin.trebuch@gmail.com> (1)
    * Curtis Baltimore <curtisbaltimore@protonmail.com> (1)
    * Ettore Atalan <atalanttore@googlemail.com> (10)


* Greek

    * Dimitris Maroulidis <dmaroulidis@dimitrismaroulidis.com> (3)


* Occitan

    * Mejans <farga@mejans.fr> (71)


* Italian

    * lsd-cat <giulio@gmx.com> (2)


* Slovak

    * Cory Francis Myers <cory@freedom.press> (1)


* French

    * AO Localization Lab <ao@localizationlab.org> (3)


* Swedish

    * Jonas Waga <jonas.waga@schibsted.com> (3)


* Persian

    * Leila Zia <leila.zia@gmail.com> (59)


* Polish

    * Adam Rak <kitynska@gmail.com> (129)


* Slovenian

    * Enej <enej.grmek@osiria.net> (15)


* Norwegian Bokmål

    * Øyvind Bye Skille <oyvind@byeskille.net> (4)


* Portuguese (Portugal)

    * notmuchtohide <notmuchtohide@protonmail.com> (4)
    * deeplow <deeplower@protonmail.com> (5)


* Chinese (Traditional)

    * Chi-Hsun Tsai <chihsun.tsai@gmail.com> (1)
    * Meng Pang Wang <mengpangwang@gmail.com> (3)


* Chinese (Simplified)

    * Kishin Sagume <kishinsagi@riseup.net> (2)
```
</details>

<details>
<summary>We added <code>i18n_tool.py list-translators</code> in June 2019 (freedomofpress/securedrop@16253063b2cd0ffca065df6ca55742ca39d8c9fe) to generate reports like this one.  <a href="https://github.com/search?q=org%3Afreedomofpress%20list-translators&type=code">We only use it manually.</a></summary>

```
ar (Arabic):


ca (Catalan):
  Benet (BennyBeat) R. i Camps
  Joan Montané
  John Smith


cs (Czech):
  Jan Papež


de_DE (German):
  Curtis Baltimore
  Ettore Atalan
  Martin Trebuch


el (Greek):
  Dimitris Maroulidis


es_ES (Spanish):


fr_FR (French):
  AO Localization Lab


hi (Hindi):


is (Icelandic):
  Sveinn í Felli


it_IT (Italian):
  lsd-cat


nb_NO (Norwegian):
  Øyvind Bye Skille


nl (Dutch):


pt_BR (Portuguese, Brasil):
  Guilherme
  leilane
  notmuchtohide


pt_PT (Portuguese, Portugal):
  deeplow
  notmuchtohide


ro (Romanian):


ru (Russian):
  Adham Kurbanov


sk (Slovak):


sv (Swedish):
  Jonas Waga


tr (Turkish):
  tekrei


zh_Hans (Chinese, Simplified):
  Kishin Sagume


zh_Hant (Chinese, Traditional):
  Chi-Hsun Tsai
  Meng Pang Wang
```
</details>

I'm not convinced we should maintain, or reimplement, our own (workflow-dependent/fragile) version of this feature for a low-risk task we perform less than once a month (again, manually anyway).  Please convince me!

**Comment by legoktm** [comment]
The weblate report format looks good to me, plus post-processing that if we want a different format (not sure we want to promote/advertise everyone's emails like that) seems much simpler than having our own data extraction script.

**Comment by cfm** [comment]
Dropping per <https://github.com/freedomofpress/securedrop/issues/6917#issuecomment-1690762840>.
