### ISSUE TITLE
packaging should include compiled gettext MOs

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1283]
#1348 supersedes the changes described below from #1282.  Under #1348, all that remains to do here is:

1. [x] Test end to end that a `securedrop-client` package includes a `messages.mo` machine object for each locale and that the client loads these correctly via:
    - [x] **Development:** `LANG=es ./run.sh`
    - [x] **Production:**  `/opt/venvs/securedrop-client/bin/sd-client` from `securedrop-client.X.Y.Z+buster_all.deb` installed in disposable VM from template with `export LANG=es_ES.utf-8; dpkg-reconfigure locales`

| Target | 0.5.1 | `main` | #1294 | `*.mo` in... |
| --- | --- | --- | --- | --- |
| `PKG_GITREF=` | | `main` | `1283-package-translations` | |
| | ✗ | ✓ | ✓ | `python setup.py sdist` |
| | ✗ | ✓ | ✓ | `python setup.py bdist_wheel` |
| | ✗ | ✓ | ✓ | `securedrop-client_X.Y.Z+buster_all.deb` |
- [x] Any of the languages available in `securedrop_client/locale/*` can be loaded with `LANG=foo`
2. ~Revert the substantive changes of freedomofpress/securedrop-debian-packaging#270: `babel` is no longer required (after #1348), but the bootstrap will need to be re-signed.~  →  freedomofpress/securedrop-debian-packaging#283

---

#1282 provides a Make target `compile-translation-catalogs` to compile the per-locale POs committed by Weblate into the MOs actually loaded by gettext at runtime.  While it's acceptable for this compilation step to happen at runtime in the development environment, loadable MOs should be included in production packages, ~whether~ compiled ~as part of `securedrop-client` CI or~ during the `securedrop-debian-packaging` workflow.

1. [x] Python
    1. [x] `MANIFEST.in` includes `*.{po,mo}`:  https://github.com/freedomofpress/securedrop-client/blob/16b379962bc79129d74a380b88a047187be3eca5/MANIFEST.in#L15
    2. [x] `python setup.py sdist` includes `*.po` → `*.mo`
    3. [x] `python setup.py bdist_wheel` includes `*.mo`
2. [x] Debian
    - [x] Check: inclusion of `*.mo` will not break determinism/reproducibility
3. [x] `pybabel` available in `securedrop-debian-packaging` context

**Comment by cfm** [comment]
Updated based on this morning's demo and discussion:  `securedrop-client` will ship with precompiled `.mo`s, meaning that these will be compiled from Weblate's `.po`s as part of the packaging workflow rather than as part of nightly CI.

**Comment by cfm** [comment]
As of aa37aaba8754b649792d316d1675bfa5b9e4297f (WIP):

1. [x] `python setup.py sdist` includes `*.po` → `*.mo`
    ```sh-session
    (.env) cfm@ozymandias{1058}$ python setup.py sdist | grep "\.mo"
    [...]
    copying securedrop_client/locale/es/LC_MESSAGES/messages.mo -> securedrop-client-0.5.0/securedrop_client/locale/es/LC_MESSAGES
    ```

2. [x] `python setup.py bdist_wheel` includes `*.mo`
    ```sh-session
    (.env) cfm@ozymandias{1064:1}$ python setup.py bdist_wheel | grep "\.mo"
    [...]
    copying build/lib/securedrop_client/locale/es/LC_MESSAGES/messages.mo -> build/bdist.macosx-10.15-x86_64/wheel/securedrop_client/locale/es/LC_MESSAGES
    adding 'securedrop_client/locale/es/LC_MESSAGES/messages.mo'
    ```

**Comment by eloquence** [comment]
@cfm Could you clarify what's left to do to resolve this issue?

**Comment by cfm** [comment]
Thanks for flagging, @eloquence.  I've updated the description with a new checklist after #1348 based on what I'd left (unhelpfully :-) in <https://github.com/freedomofpress/securedrop-client/issues/239#issuecomment-988187758>.

**Comment by cfm** [comment]
I've done end-to-end testing to confirm that a `securedrop-client` package includes a `messages.mo` machine object for each locale and that the client loads these correctly via:
1. [x] **Development:**  `LANG=es ./run.sh`
2. [x] **Production:**  `/opt/venvs/securedrop-client/bin/sd-client` from `securedrop-client.X.Y.Z+buster_all.deb` installed in disposable VM from template with `export LANG=es_ES.utf-8; dpkg-reconfigure locales`

#1294 is no longer required, and I've closed it accordingly.

**Comment by cfm** [comment]
The remaining non-blocking housekeeping chore here has been opened as freedomofpress/securedrop-debian-packaging#283, to be included in the next sprint.
