### ISSUE TITLE
Permissions on `svs.sqlite` is `700` instead of `600`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1291]
# Steps to reproduce
1. Delete ~/.securedrop_client (manually copy `config.json` first if you want to ensure correct functioning of the client without re-running apply)
2. Start the client via command line by running: `securedrop-client` in `sd-app`

# Expected behavior
`svs.sqlite` and `sync_flag` should have `600` permission per #1256
# Actual behavior
The permission on `svs.sqlite` is 700 (includes executable bit).

**Comment by conorsch** [comment]
Thanks for filing, @eloquence! I'll grab this one.
