### ISSUE TITLE
Unlink out.name when decryption fails in crypto.py

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-client#132]
We should delete all files created by crypto.py when the return code of the gpg command is not zero. The `err` file is unlinked but the `out` file is not.

see: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/crypto.py#L51

While this is a temporary file and will be deleted after reboot, we should still delete them for the system since they are no longer needed.

**Comment by redshiftzero** [comment]
Thanks for filing @emkll. So I just looked at the [tempfile module docs for `NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile):

> If delete is true (the default), the file is deleted as soon as it is closed.

So we just need to make sure that we are closing these tempfiles, and afterwards we shouldn't need to `os.unlink` (indeed if we attempt to then an exception will occur)

**Comment by joshuathayer** [comment]
Happily, I've cleaned a bunch of this stuff up already! Sadly, it's all locked in the [send-replies branch](https://github.com/freedomofpress/securedrop-client/blob/send-replies/securedrop_client/crypto.py), which, I think, is substantially different enough to make cherry-picking difficult. If this isn't critical for the audit, we may consider letting it go until we get the replies stuff merged.

**Comment by redshiftzero** [comment]
ahhh, thanks for the pointer, I'll just make a minimal change for the audit to close this on top of #166

also i was wrong in my last comment, `err` is using `delete=False` so the logic above works 👌
