### ISSUE TITLE
restore macOS development requirements

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1320]

**Comment by creviera** [comment]
When restoring macOS dev reqs, see what breaks when you use `dev-requirements.in`. You should just need one additional dependency: `rubicon-objc`. If we intend to support macOS moving forward, past our Aaron Swartz day hackathon, then we will need to make sure that maintainers without macs are not blocked when upgrading dev-only dependencies for our debian test environment. https://pypi.org/project/PyQt5/5.11.3/ and https://pypi.org/project/sip/4.19.8/ are needed for this to look and _mostly_ behave like the production application that runs in a Qubes VM with system pyqt installed. The system pyqt is: 5.11.3+dfsg-1+b3.

**Comment by eloquence** [comment]
This was resolved by #1335.
