### ISSUE TITLE
Pressing enter from login form defaults to offline mode

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1338]
## STR

1. Start the client
2. Enter login credentials and don't press TAB after reaching the end of the login form where you enter your 2FA code
3. Press the Enter key

## Expected

To log in with the credentials you just typed in

## Actual

Instead of logging you in, the client opens in offline mode.

**Comment by gonzalo-bulnes** [comment]
This sounds like a mistake, [I thought I'd made the submit the default](https://github.com/freedomofpress/securedrop-client/commit/2f8fad450f4048160bcf53bf02fa08ee0d454588). Clearly it didn't work like I expected and I didn't check it. Good catch @creviera I'll fix it now.
