### ISSUE TITLE
Update "Entire source account" deletion to complete when server reports success

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1344]
#1311 updates "Files and messages" deletion to complete when the server reports success, instead of waiting for the next sync. This dramatically improves deletion performance, especially on a server with many sources where a sync takes a long time. We should apply the same performance improvement to "Entire source account" deletion.

**Comment by eloquence** [comment]
(Proposing this as a post-0.5.0 enhancement assuming we discover no novel issues with this approach.)

**Comment by eloquence** [comment]
Reopened via revert in #1426. To fully resolve, we'll want to make sure we don't observe the behavior noted in #1420.

**Comment by creviera** [comment]
https://github.com/freedomofpress/securedrop-client/issues/1420 is not specific to account deletion, rather it has to do with how we switch between online and offline modes in the client. So those issues should be resolved separately, I believe.

**Comment by creviera** [comment]
Also, https://github.com/freedomofpress/securedrop-client/issues/1420 is higher priority than speeding up source deletion right now.

**Comment by eloquence** [comment]
I do think the two issues should ideally be resolved together. Deletion is already a major pain point for our users, and we don't want to push out a release that makes things _slower_. And slowness is also a security issue: if you are in an emergency situation, having to wait for an entire sync duration to delete sources could prevent you from deleting things you need to delete, and you may be just as likely to close the laptop while the on-disk deletion is not complete.

**Comment by creviera** [comment]
Good point, let's prioritize adding this into the next release as well, but it is technically a separate issue. Right now, I'm seeing three issues that we'll need to work on: this one, https://github.com/freedomofpress/securedrop-client/issues/1420, and https://github.com/freedomofpress/securedrop-client/issues/1429. Is that your understanding?

**Comment by eloquence** [comment]
Yes, that makes sense - #1429 could be resolved by ensuring that files and database updates are performed the moment the server notifies us the deletion is successful (instead of waiting for a sync).
