### ISSUE TITLE
Preview most recent message or reply in source view

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#135]
Below the source designation, the source list should show a preview (text abbreviated with "..." if necessary) of the most recent message or reply, as shown in this grayscale wireframe:

![snippets](https://user-images.githubusercontent.com/213636/48295958-022ac080-e446-11e8-91a9-592c34980104.png)

If the most recent interaction is a message from the source, it should show an excerpt of that message; if the most recent interaction is a reply from the journalist, it should an excerpt of the reply.

If the most recent interaction is a file upload, we should show the most recent message or reply.

If there has never been any message or reply but only a file, we can show "_&mdash;submitted a file, no message&mdash;_".

**Comment by eloquence** [comment]
For anyone wanting to work on this issue, the code removed in https://github.com/freedomofpress/securedrop-client/pull/134/files may give some useful pointers how to update the source view.

**Comment by timruffles** [comment]
Will take a look.

**Comment by creviera** [comment]
Note: Once we add the preview snippets, the width available for preview snippets should scale up or down if you resize the client window, but the space to the left and to the right in the source list should _not_ scale up along with it, but be fixed.

**Comment by ninavizz** [comment]
Pls to update preview message text from: `— submitted a file, no message —` 
...to: `— file only —`  (pls to mind the spaces between the em-dashes and the characters before and after)

I don't know if there'd be a lot of logic involved in pluralizing, but per the rough rule for grouping files in the File Pane (if a Source submits more than 1 document in a 12 hour period, it is visually shown as a group—vs as individual stand-alone files) it'd also be great to have the pluralized message display if more than 1 document is received in a 12 hour period: `— files only —`

bump, @creviera :)

Also, per the OG comment: This should only display if the Source has never sent a message, and/or the Newsroom has never sent a response. If a Source sends just a message, in a thread, then the most recent message should go in the preview.

**Comment by ntoll** [comment]
FYI, I started work on this this afternoon. Please move to "in development". Thanks.

**Comment by ntoll** [comment]
OK... here's a screenie of the working solution. I need to clean up the code a little but PR imminent. :-)
![latest_message_preview](https://user-images.githubusercontent.com/37602/72344648-ab63eb00-36c9-11ea-8e46-423af6161fba.gif)

**Comment by ntoll** [comment]
The "reply not yet available" message will disappear upon each refresh (it's just on first start the messages have not been made available yet).
