### ISSUE TITLE
Polish: Add pixels after last message in Conversation Pane

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1355]
## Oddity
The bottom edge of the `urgent-coral` bar on the last message in the conversation pane, is up against the top edge of the Reply pane, when the scroll is at its bottom-most position of a long scrolling page. 

Conversely, all of the messages have a consistent amount of space between them, which is the same as the space between the top of the first Source message and the top of the Conversation area.

## Requested Correction
There should be the same amount of spacing between the bottom edge of the last message and the top edge of the Reply Pane, as there is between the top of the most recent Source message, and the bottom of the "NA" Journalist reply in the below screenshot. So—around 10px of "dead space" at the end of the scroll. 

## Why?
It looks odd and potentially broken, without the negative space at the end of the page scroll.

![image](https://user-images.githubusercontent.com/8262612/143808963-d0e174cd-24ce-4af8-ba7f-7cbca49dea8b.png)

**Comment by creviera** [comment]
closed by https://github.com/freedomofpress/securedrop-client/pull/1391
