### ISSUE TITLE
Add read receipts for source messages and journalist replies

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1371]
# Description

Implement the frontend that shows which journalists have seen a message or reply.

* Use "Seen by" records to pull journalist names per message/reply
* Display a checkmark icon in the lower right-hand corner of a speech bubble that is displayed in a conversation **if** any journalist other than the currently logged-in journalist has seen it
* Display a tooltip (similar to the journalist badge tooltip) with a list of journalist names when you hover over the checkmark icon

Towards https://github.com/freedomofpress/securedrop-client/issues/1365

**Comment by Er1kkkaaa** [comment]
![seen_checkmark](https://user-images.githubusercontent.com/87483970/145277997-2a824b75-e3b3-45d2-a8c4-e3548e977547.png)
![checkkycheck](https://user-images.githubusercontent.com/87483970/145278014-796773a6-d9d1-4005-9c09-08f49fdf63d1.png)

**Comment by Er1kkkaaa** [comment]
The link: https://www.figma.com/file/vs52zFnp5zpEHfCnTI0R3U/SDW-Design-System?node-id=266%3A2777

**Comment by ninavizz** [comment]
@Er1kkkaaa If you're using PNGs in a UI, pls export them at 300% of the final displayed size. That will help avert "fuzzy" appearances on high-pixel-density displays. :)

**Comment by Er1kkkaaa** [comment]
@ninavizz I just started watching your tutorial actually, cause I felt something was not right haha. Thank you!!

**Comment by Er1kkkaaa** [comment]
Figma link for reference: https://www.figma.com/file/YejZGCIGZikX55LDcfvcYY/Client-%E2%89%A5-Q4-2021?node-id=511%3A58327
