### ISSUE TITLE
[CI] Update container images for tests

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-client#1384]
We're currently using the `circleci/python-3.7` images in CI. According to the [CircleCI docs](https://circleci.com/docs/2.0/circleci-images/):

> Legacy images with the prefix "circleci/" will be deprecated on December 31, 2021. For faster builds, upgrade your projects with next-generation convenience images.

The recommended image would be `cimg/python`, but that's based on Ubuntu Focal 20.04, whereas we need Debian 10 (until we migrate to Debian 11 for the Workstation). Let's consider `debian:buster` instead.

**Comment by conorsch** [comment]
@gonzalo-bulnes started a branch to resolve this, which I've picked up and appended to. Tracking in https://github.com/freedomofpress/securedrop-client/pull/1385, with the optimistic goal of having this week, ahead of the "deprecation" date at EOY.

**Comment by conorsch** [comment]
Recording runtimes for historical CI jobs, for reference:

* `test-buster`: 5-7m
* `build-buster`: 3-5m

It's possible, even likely, that switching the container image will affect wall time on CI, so let's evaluate that as part of the change.

**Comment by conorsch** [comment]
Based on discussion in #1385, we'll use `debian:buster` as the default, and explicitly add packages required for a build environment. I've updated the OP for `s/python:3.7-buster/debian:buster/` to match.

**Comment by legoktm** [comment]
We've since standardized on plain `debian:{version}` images.
