### ISSUE TITLE
token is not always invalidated on logout

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1453]
# STR

Follow STR in #1420 issue description with one modification: log in as a different user on step 8

# Expected

Replies that are sent should only ever come from the sender.

# Actual

If the user logs out without a network connection when there are pending replies, and then logs back in again as a different user, the first draft reply is sent as the new user.

@creviera in <https://github.com/freedomofpress/securedrop-client/issues/1420#issuecomment-1080932370>:

> this doesn't fix the underlying issue [#1420], but there is a bug where the following should be called outside of the conditional in order to ensure that we update the `authenticated_user` every time we logout (this is why we saw a pending reply sent as the new user that logged in after the outage):
> 
> https://github.com/freedomofpress/securedrop-client/blob/f903cc34bdfd8d25d359ca4f6425b91fc0e623aa/securedrop_client/logic.py#L773-L775
> 
> should be:
> 
> ```python
>   if self.api is not None: 
>      self.call_api(self.api.logout, self.on_logout_success, self.on_logout_failure) 
> 
>   self.invalidate_token()
> ```

**Comment by cfm** [comment]
@creviera, I've gone ahead and branched this off from <https://github.com/freedomofpress/securedrop-client/issues/1420#issuecomment-1080932370> so that we can track the distinct authentication- and queue-related problems.  I'll fold your proposed fix (giving credit where credit is due!) into my upcoming work on #1434 in the next sprint unless you beat me to it separately.  :-)

**Comment by creviera** [comment]
good idea with breaking this out - if #1420 isn't resolved by the next release, at least we can get a fix for this in, making #1420 less severe.
