### ISSUE TITLE
Local safe-delete removes enclosing directory, remote delete does not

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-client#1474]
## Description

Reported by @cfm:  

Local 'safe-delete' (deleting files and messages) also deletes the directory containing the file and message data (`~/.securedrop_client/data/<journalist-designator>`), while remote delete of files and messages removes the content but leaves the directory in place.
 
## Steps to Reproduce
- Log into the JI and delete source A's files and messages
- Locally delete source B's files and messages 
- Inspect `~/.securedrop_client/data/` directory and observe source A directory (now empty) is still present

## Expected Behavior
- Client and server deletion behave the same

## Actual Behavior
- Source A directory is present, source B directory is gone

## Comments

I kind of prefer the client deletion behaviour, because it really cleans up _all_ of the indications that messages and files were downloaded, vs removing the files but leaving the directory in place.

**Comment by rocodes** [comment]
The options are:

- Change nothing, leave the bug in place for the time being
- Change local delete so that it removes files and messages, but not the enclosing folder.
- Change the deletion behaviour in sync so that if it deletes the last file in a directory, it also deletes the enclosing directory. (Sync doesn't know anything about 'delete files and messages' - all it knows is that the server shares its submission contents, and basically, any submissions that are present locally but were not found in the latest sync data are deemed to have been deleted, and are removed one by one). 

Option 1 means lack of consistency with client and server. Option 2 means consistency, but extra info left behind (a source that has had their files and messages deleted will still have the directory name there, which indicates that at one point someone did download files and messages for that source). I think Option 3 is the best option, but also introduces more potential edge cases. If anyone has thoughts, feel free to chime in.

**Comment by eloquence** [comment]
(If the behavior hasn't changed, my vote would be to keep it out of scope for this release train)

**Comment by creviera** [comment]
> I think Option 3 is the best option, but also introduces more potential edge cases. If anyone has thoughts, feel free to chime in.

Removing the enclosing folder with the source name makes the most sense and is the best option in my opinion as well. I'm about to review https://github.com/freedomofpress/securedrop-client/pull/1475 and will try to think of edge cases when running through the test plan.

**Comment by creviera** [comment]
> (If the behavior hasn't changed, my vote would be to keep it out of scope for this release train)

After review, I'll have a better idea of how large or small the implementation is, and we can all check in during the our developer meeting and decide whether or not to add it into rc2.

**Comment by creviera** [comment]
fyi, decided as a group to delay until the next client release
