### ISSUE TITLE
Add basic display layer

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#15]
Once we have the ability to authenticate (#14) and synchronize data (#5), we should display the available data to the user. For now we can use the [first prototype](https://eloquence.github.io/workstation-messaging/#benignartichoke1_page) as a guidepost for the client design, but we will iterate on the design as we go, so we can use placeholder colors, icons, etc. for now. Regardless of the final design, we will need a source list view and a per-source detail view.

The data we want to display as part of the list view in the UI is:
- a list of sources the client knows about
- when a source was most recently updated (could represent a source or journalist interaction!)
- whether a source has been starred
- when the client was last synchronized
- if I am logged in, what my user name is.

Once we can decrypt messages, we want to also display
- an excerpt from the most recent interaction with a source in the list view
- the messages, submissions (just filename / placeholder icon) and replies for that source in the per-source detail view.

**NOTE:** It may not be possible to display some legacy replies; see #4.

The scope of this task is just the display of information in the list and detail view, not the interactions, which will be tracked separately.

For the first iteration of the display layer, we should not concern ourselves with read/unread status, or the number of new or total messages/submissions for a given source.

**Comment by ninavizz** [comment]
Yet to create an Issue to G3rk1n the functionality of allthese things, but tentatively:
• Starring: unstar/star interaction only in the "Message" view, not in the list itself
• Source detail pane, including the interactive header-portion, to deliver this week—stay tuned!
• Want to display Journalist username and picture, and for the picture to accompany journalist name into Source interface—but I suspect that's it's own Beta feature, and a separate feature request for the Source interface?

**Comment by eloquence** [comment]
> Want to display Journalist username and picture, and for the picture to accompany journalist name into Source interface—but I suspect that's it's own Beta feature, and a separate feature request for the Source interface?

Yes, that's probably a post-alpha feature.

**Comment by eloquence** [comment]
For the 9/24 sprint, we've committed to integration against the development environment, i.e., it should be possible to to 
- launch the client
- optionally log in (#14)
- display all data in the dev environment as enumerated in the issue (i.e. messages only, not submitted documents).

**Comment by ntoll** [comment]
Hi... some visible signs of progress attached to this comment:

![images](https://user-images.githubusercontent.com/37602/46029617-dbaa0380-c0eb-11e8-8daf-a85cc69df5b4.png)
![styled_login](https://user-images.githubusercontent.com/37602/46029618-dbaa0380-c0eb-11e8-8cef-6d5dc87a0ff0.png)

**Comment by ninavizz** [comment]
Not sure if this is the best place on GH for this, but here is ye dummy content!
https://docs.google.com/document/d/16ppERLy-jDlREtwKEmrAT5HCdC3ogcyN_OPsf5HUTQg/edit?usp=sharing

**Comment by ntoll** [comment]
Ack on dummy content.

Most of the features of this have landed via merging #29.

**Comment by redshiftzero** [comment]
fair, closing since the remainder of this functionality is tracked in #32
