### ISSUE TITLE
[v0.9.0] set supported languages

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1533]
In last week's flurry of Workstation-wide release activity, #1531 was not reviewed in time to be included in `securedrop-client` 0.8.0.  Let's prioritize setting supported languages for the quieter v0.9.0 release.

**Comment by gonzalo-bulnes** [comment]
Update: #1531 will be part of `v0.9.0`.

**Comment by cfm** [comment]
I can confirm from #1637 that #1531 works as expected after both Python and Debian packaging.
