### ISSUE TITLE
Identifying test failures in the CI pipeline is attention-consuming

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-client#1543]
## Description

When any test fails in the CI pipeline, the `test` job fails. That's expected. However, if you want to determine which test failed (or which requirement wasn't met, it could be a linting issue), you need to scroll through the output of one single long step.

I propose splitting the testing tasks into multiple CI **jobs**.

Current:

- build
- test
  - setup
  - lint-and-test-all-the-things
  
Proposed:

- build
- lint, type check, etc.
  - setup
  - lint, type check, etc.
- unit test
  - setup
  - test (`make test`)
- integration test
  - setup
  - test (`make test-integration`)
- functional test
  - setup
  - test (`make test-functional`)

### Trade-offs

CI builds duration can be measured using "wall clock time", and "CPU time". One advantage of grouping all tasks as we do currently is keeping the "CPU time" minimal. That's good for the planet in terms or energy consumption :earth_africa:, and may be cheaper.

Splitting the tasks into more jobs may (or may not, it depends) result in a decrease in "wall clock time", which means people have to wait less for CI results. However it often results in an increase of "CPU time" because some setup has to be repeated across jobs (which are typically run independently). It's main value lays in the readability of the results, and a decrease of the time spent looking for answers.

_I don't take increasing CPU time lightly (:earth_americas:), but I would give a try to splitting jobs, see how we like it before assuming that the trade-off it not worth it._

### Impact

Developers could rely on CI builds more effectively to narrow down troubleshooting. It's a day-to-day quality of life improvement.

### Security

There are no implications for the threat model, because we'd still be running the exact same checks, and those are not order-dependent.

**Comment by rocodes** [comment]
Thanks, this is well thought out. I think this is a good idea, and it could also afford us more nuance in our CI logic (bail immediately if a job fails; only run functional/integration tests under certain conditions; etc). I appreciate your noting the possible increased environmental burden too (and I wonder if a more streamlined testing strategy would offset that somewhat).
