### ISSUE TITLE
Release securedrop-client 0.8.1

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-client#1558]
This issue tracks the SecureDrop Client release **0.8.1**. It will be organized by:

- Release Manager: @creviera 
- Deputy Release Manager: @gonzalo-bulnes 

This release includes the following changes (~~[0.8.0..main](https://github.com/freedomofpress/securedrop-client/compare/0.8.0...main)~~ - [0.8.0..release-cutom-timeout](https://github.com/freedomofpress/securedrop-client/compare/0.8.0...release-custom-timeout)):

- Add experimental support for a custom timeout that allows the SecureDrop Client to retrieve a larger number of sources (https://github.com/freedomofpress/securedrop-client/pull/1552)
- ~~Add language support for Portuguese (`pt_PT`)~~
- ~~Add language support for Simplified Chinese (`zh_Hans`)~~
- ~~Fix missing translation in export dialog title~~
- ~~(Dev) ...~~
- ~~(Dev) ...~~

SecureDrop maintainers and testers: As you QA this release, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the release milestone for tracking (or ask a maintainer to do so).

## Test plan

[Make sure to include the version(s) of the server that need to be tested against. If the release is being coordinated with a server release, specify rc versions of the server that need to be tested and release order. Once completed, insert or link to a test plan here. It can be left out until then.]

## Release tasks

-  ~~Check if there are any security bug fixes waiting to be pulled into the RC~~
- ~~Check if there are any translations:~~
    - ~~pending merge into `main`~~
    - ~~pending inclusion as a supported language in [`MANIFEST.in`](https://github.com/freedomofpress/securedrop-client/blob/main/MANIFEST.in)~~
- [x] Update changelog
- [x] Create test plan
- ~~Refresh nightlies~~
- ~~Begin formal QA using nightlies; refresh nightlies as needed~~
- [x] Begin formal QA using ... :tangerine: 
- [x] Build production package in standard [build environment](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/FAQ#how-do-i-create-a-local-environment-suitable-for-building-packages)
- [ ] Sign production package
- [x] Perform final pre-flight testing using apt-qa.freedom.press
  - [ ] **Localization:** In a dispVM, change your locale (e.g.: `export LANG=es_ES.utf-8; dpkg-reconfigure locales`), run the Client, and confirm that the application is translated.
- [x] Publish production package
- [ ] Publicize release via support channels

**Comment by gonzalo-bulnes** [comment]
**Update**: @creviera and I considered releasing `main` as **0.8.1** because we're making this release outside of the regular release schedule and don't want to pull others into the QA process (despite generous offers!), we changed our minds and decided to only release the experimental custom timeout feature.

We'll be branching out of `0.8.0` and creating a release branch for that purpose.

**Comment by gonzalo-bulnes** [comment]
I've pushed the [0.8.1](https://github.com/freedomofpress/securedrop-client/releases/tag/0.8.1) tag @creviera.

**Comment by gonzalo-bulnes** [comment]
I've added the change log entry, and pushed a new [`0.8.1`](https://github.com/freedomofpress/securedrop-client/releases/tag/0.8.1) tag @creviera

**Comment by creviera** [comment]
small update: i removed the 0.8.1 tag for now since the release didn't happen this week

**Comment by gonzalo-bulnes** [comment]
For the record, I've updated the `0.8.1` tag once again after making sure the version number was updated were it needed to be (`./update-version 0.8.1`).
