### ISSUE TITLE
Support multiple select for sources

### ISSUE THREAD

**Issue by philmcmahon** [freedomofpress/securedrop-client#1569]
## Description
It would be helpful to be able to select multiple sources and then e.g. download all/delete all for the selected sources. At our organisation we frequently need to delete large numbers of messages so this would be a very helpful feature.

In terms of priority, this isn't urgent for us because we can use the old journalist portal to do this work at the moment.

As well as deletion and downloads, in future this feature could be used to support exporting the submissions/replies of multiple sources.

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?
As a securedrop workstation user, my organisation would find this very useful.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?
I don't think this changes the threat model as the behaviour is already possible by individually clicking on sources one by one.

## User Stories

As a user I want to be able to select multiple sources so that I can delete them in bulk.

**Comment by gonzalo-bulnes** [comment]
Hi @philmcmahon! Thank you for filing this issue(s), please keep doing so!

This one particularly is on my radar and something I am doing preliminary work for. Please don't take that as a prioritization call yet, but as me saying that opening the issue and discussing your use cases is useful! :slightly_smiling_face:

**Comment by rocodes** [comment]
As part of our n+1 release (0.14.0) we are planning to upstream the work that The Guardian team did in https://github.com/guardian/securedrop-client/pull/5, with a few modifications. I will open a new ticket describing a proposed work plan for that; @zekehuntergreen and team, sorry we did not converge on this sooner but looking forward to including and attributing your work.

For now, the plan is that multiple-select will be scoped to one action (batch delete sources +source accounts, per the implementation above). Based on a few conversations with pilot orgs, this is the most-requested multi-delete option (as opposed to deleting only the conversation contents, which users do not report doing as a bulk action). Multi-select as a path to multi-download would be fairly straightforward to implement after this, but that will be deferred to keep the scope small and our release cadence up.

**Comment by hoyla** [comment]
🙏
