### ISSUE TITLE
`DeleteConversationDialog`: confirmation prompt is ambiguous

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1575]
Translator pappasadrian [notes](https://weblate.securedrop.org/translate/securedrop/securedrop-client/en/?checksum=d1cf4e35916efef0#comments) that the source string—

https://github.com/freedomofpress/securedrop-client/blob/b6baa620e2f20e3f3d194676042a93607086b2c6/securedrop_client/gui/conversation/delete/dialog.py#L59-L60

—is phrased ambiguously in English and therefore difficult to translate.

**Comment by gonzalo-bulnes** [comment]
Yup! I take your self-assignment as you'll fix it @cfm ? I'll line up for review!
