### ISSUE TITLE
Allow plain text conversation digest to be created

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-client#1581]
## Description

This would be a step towards allowing conversations to be printed. (https://github.com/freedomofpress/securedrop-client/issues/1435)

Format: plain text, to allow immediate printing
Content: messages, replies and references to files, in chronological order (the same as the conversation displayed in the GUI)
Trigger: none yet, exporting or printing is out of scope, and downloading the file without exporting or printing it is not useful in itself

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?

No visible impact yet.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?

What information is exported within the conversation digest needs to be considered because some of it might not have been exportable previously. (e.g. timestamps, file names...)

**Comment by gonzalo-bulnes** [comment]
My initial thoughts for the digest format are:

```
happy-bird said:
Hello! I think this is newsworthy: ...
------
interested-journalist said:
Thank you for the tip!

Can you tell me more about... ?
------
Do you have proof of...?
------
happy-bird said:
File: memo.pdf
------
Here is a document with details!
------
I can send you more if you're interested.
------
other-journalist said:
Yes, the document you sent was useful, I'd love to see more.
```

**Comment by rocodes** [comment]
I think this is fine, and I don't know if you need the "said" (just `journo designator:` and `source desginator:` seem fine to me and avoid translation issues)

**Comment by gonzalo-bulnes** [comment]
Even the colon already enters the translation land (think RTL/LTR languages)... on one hand, I think that translating those would be fine (because they've a regular structure that's known ahead of time and the only variable is the username that is not itself translated).

We could also opt for nothing: `journo designator` or some symbolic markup that doesn't require translation like `[journo designator]`. I personally still prefer translating a more familiar-looking string: `journo designator wrote:`, but don't feel strongly about it.

Any thougths @tina-ux ?

**Comment by eaon** [comment]
1. I think a plain-text only approach is a good start to get the ball rolling, but long-term, I think it'd be better if we had a minimalist design that reflects the look of the conversation on screen. For what it's worth, it's relatively easy to create XML based templates that can be used by the client to generate documents that can be converted to printable PDFs by LibreOffice. I wrote some code doing this for a non-FOSS project a while ago, if there's interest in this approach, I'd be happy to look into details for that again.
2. As far as I am aware, there are some newsrooms with longer-term conversations with sources, and I think for them it'd be quite beneficial to include at least the dates of messages (my intuition tells me time is less important here). Formatting wise, I'd probably go for something along the lines of `Thursday, November 52, 2342 [ message ] [ message ] Sunday, November 56, 2342 [ message ]` (and if we don't do that in the client yet I think it'd be cool there too)

**Comment by cfm** [comment]
Controversial intuition (please disabuse me of it!):  This is a serialization problem; we just want the serialization format to be human-readable and print-friendly.  What if we defined a versioned YAML schema and output that, rather than creating a custom digest format just for this purpose?

**Comment by gonzalo-bulnes** [comment]
Can you give an example of the YAML output you've in mind @cfm? (or feel free to wait until we :pear: pair today!)

Yours is a good call out. It made me realize the I'm assuming that copy/paste is high on the requirements list, despite framing the issue as a printing issue first.

I've been assuming that the main uses of a digest would be to:
- search
- copy/paste
- print (or print goes first?)
- only for a narrower amount of folks: programmatically working with the file

The search will behave similarly in any text-based format, plain text, YAML, JSON or otherwise. It seems to me that for manual copy/pasting purposes, the plainer the text format is, the better. For printing purposes, spacing seems like it would be beneficial (the `------` lines in my example probably hinder readability on a printed page more than they help).

We can also output multiple files without any significant overhead, e.g. `conversation.txt`, `conversation.yml` and `conversation.pdf` if people express interest for them. Which brings us back to the question of the focus... which was printing, but maybe warrants reconsidering?

**Comment by cfm** [comment]
Discussed in pairing with @gonzalo-bulnes re: <https://github.com/freedomofpress/securedrop-client/issues/1581#issuecomment-1291086812>:

> Can you give an example of the YAML output you've in mind @cfm? (or feel free to wait until we pair today!)

I propose:

```yaml
- From: happy-bird
  Message: >
    Hello! I think this is newsworthy: ...

- From: interested-journalist
  Message: >
    Thank you for the tip!

    Can you tell me more about... ?

- From: interested-journalist
  Message: >
    Do you have proof of...?

- From: happy-bird
  File: memo.pdf

- From: happy-bird
  Message: >
    Here is a document with details!

- From: happy-bird
  Message: >
    I can send you more if you're interested.

- From: other-journalist
  Message: >
    Yes, the document you sent was useful, I'd love to see more.
```

By serializing to YAML, we'd get for free a canonical representation of the conversation that's (a) human-readable on screen, (b) nicely whitespaced for printing, *and* (c) also machine-deserializable for other processing.  It should prevent us from having to solve most encoding and formatting problems ourselves.  The possible exception, which I'll  look into, is how YAML  as a plain-text format with whitespace semantics copes with right-to-left languages.

**Comment by eloquence** [comment]
A couple of thoughts from my end:
- I think it's worth considering an intermediate machine-readable serialization format or lightweight template-like substitution format even in the first iteration, so we have maximum flexibility on what the human-readable output(s) should look like, and what variables should be included/omitted.
- For human consumption, I would suggest avoiding any output that includes control characters like `>` or other output that does not aid readability. IMO that makes YAML a poor fit for human readability.

My own take on a first iteration for the human-readable format would be something like this. Note that this collapses the distinction between multiple subsequent messages/replies by the same user -- this is the kind of thing that we might want to iterate on, with input from journalist users, so having a flexible approach to generating the human-friendly format seems like it would aid such iteration.

```
Last source activity: Wed 26 Oct 2022 10:53:14 AM UTC

----------------------------------------
[Source] happy bird:

Hello! I think this is newsworthy: ...

----------------------------------------
interested-journalist:

Thank you for the tip!

Can you tell me more about... ?

Do you have proof of...?

----------------------------------------
[Source] happy bird

[File: memo.pdf]

Here is a document with details!

----------------------------------------
interested-journalist:

I can send you more if you're interested.

----------------------------------------
other-journalist:

Yes, the document you sent was useful, I'd love to see more.
```

**Comment by eloquence** [comment]
@eaon 
> I think for them it'd be quite beneficial to include at least the dates of messages

AFAIK we can't do that because we only track a single source-level timestamp which reflects the last source activity -- I've included that in the example format above.

**Comment by rocodes** [comment]
I have one more thing that is worth mentioning: we should consider how we will handle failed replies in the conversation view.

IMO, the perfect is the enemy of the good in all of this. (So I think we should _not_ try to interleave the DraftReply table, for example.) If the DraftReplies table is someday integrated into the Replies table (as per Cory's suggestion), then we can cross that bridge when we come to it, but for now it doesn't need to play a role. I'm just mentioning it here so that we're aware it could violate user expectations (what's seen in conversation view is not what's seen in printout if there are failed replies in conversation view).

I also agree that a slightly-nicely-formatted (but clearly human-readable) version is a good idea, but since the lack of this feature is seriously hampering usability at the moment for existing pilot orgs, I think it's okay if we iterate on it and just get something out that is more useful to folks than the current situation. I think the most important things are: that the conversation is replicated and files are interleaved with dialog whenever they were sent, and that the text is selectable/searchable.

**Comment by rocodes** [comment]
(So eg if timestamps and "last source activity" are giving us grief, I'd be in favour of going ahead with a version that doesn't include them just to get it out the door, rather than spending a lot of time trying to decide how we will address that issue. But that's just me).

**Comment by gonzalo-bulnes** [comment]
Thanks @rocodes! 

I think we're feeling the same as you with regards to being comfortable iterating on the format. We'll set up the code to generate arbitray transcripts, use what seems like a reasonably useful format to start with and let further iteration for later, when we get user input to inform our changes.

I expect the code we write to allow us to adjust whatever format we decide to use or to change it altogether if we decide to. In other words, even if future iterations change the output format widely, if we need to make significant changes to the code (I'd be surprized and) I'd think we got something wrong. That's where I'd draw the line.

I'll add that it's looking great to me so far! 🙌 @cfm
