### ISSUE TITLE
Nightlies broke 5 days ago

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-client#1585]
The nightlies are failing with:
```
dch: error: gb_41fe4f1b-dev-20221029-060354+buster is not a valid version
```

This is because we do:
```
# Nightly versioning format is: LATEST_TAG-dev-YYMMDD-HHMMSS
export VERSION_TO_BUILD="$(git describe --tags $(git rev-list --tags --max-count=1))-dev-$(date +%Y%m%d)-$(date +%H%M%S)"
```

And https://github.com/freedomofpress/securedrop-client/releases/tag/gb_41fe4f1b was pushed 6 days ago, which causes CI to create an invalid version and dch to bail out.

**Comment by rocodes** [comment]
Historically we have only tagged releases and rcs, and IMO we should stick to doing so, leaving other tags in other remotes for cleanliness

**Comment by gonzalo-bulnes** [comment]
I pushed that tag, to sign a series of unsigned commits in [a working branch](https://github.com/freedomofpress/securedrop-client/tree/add-conversation-digest).

**Comment by gonzalo-bulnes** [comment]
@cfm I followed @rocodes suggestion and moved the tag to my fork if you want to verify the commits in #1582. :slightly_smiling_face: 

_Leaving the issue open until we confirm the nightly is green again._

**Comment by legoktm** [comment]
Manually kicked and it's all good: https://github.com/freedomofpress/securedrop-dev-packages-lfs/commit/a429b89505c35ec9a774f035b45df55603b2ae2d. Thanks!
