### ISSUE TITLE
Show the progress of message and reply retrieval after a metadata sync

### ISSUE THREAD

**Issue by zekehuntergreen** [freedomofpress/securedrop-client#1607]
## Description
This idea is closely related to https://github.com/freedomofpress/securedrop-client/issues/1608
The volume of sources and messages at our organization means that metadata syncs and the resulting message and reply download jobs can take quite a long time (around 10-20 minutes). 
As a user it's difficult to know the state of the system during this time - whether or not messages being downloaded and how up to date the sources and messages are. We'd like to be able to give the user explicit feedback about the progress of syncs and resulting download jobs so that this state is more clear. 
We'd like to replace the "Retrieving new messages" status that is displayed after a metadata sync is complete with "Retrieving `n` messages" where `n` is the number of message and reply download jobs queued for processing. Every time jobs complete or are added to the queue, the message would refresh. When all downloads are complete, the message would disappear. 

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?
This change should improve user experience, especially at organizations where sync and download jobs take a significant amount of time.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?
This proposal should not have any impact on SecureDrop Workstation's threat model.

## User Stories

As a user of the workstation, I'd like to see a message telling me how many message and reply download jobs are queued so that I know how up-to-date my sources and message are.

**Comment by gonzalo-bulnes** [comment]
I've marked this issue to be closed by #1604 (via ~~`Addresses #1607`~~ `Fixes #1607`) because I think that was your intention @zekehuntergreen! Please correct it if I got that wrong!

**Comment by zekehuntergreen** [comment]
> I've marked this issue to be closed by #1604 (via ~`Addresses #1607`~ `Fixes #1607`) because I think that was your intention @zekehuntergreen! Please correct it if I got that wrong!

Thanks, @gonzalo-bulnes - I'm new to github issues and actually wasn't aware that `Fixes` was a keyword that would close this issue when the PR is merged! 

> On the issue content, the proposed behavior enhances the existing messaging, without other significant changes. I think it is a clear improvement, that's well scoped, and I see no downsides to it. 👍

Amazing, that's great news!
