### ISSUE TITLE
set default duration for messages in the left sidebar status bar

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#162]
## Description

In the status bar at the bottom of the application, the status bar messages have a default duration.

We should implement this for the status bar at the left sidebar of the application:

<img width="444" alt="screen shot 2018-11-11 at 4 51 57 pm" src="https://user-images.githubusercontent.com/7832803/48320779-1ef3ff00-e5d2-11e8-9f62-ea3a794c1cce.png">

**Comment by eloquence** [comment]
I'm assuming this can be closed since we now have a single status bar at the top which does appear to consistently go away after a few seconds; please reopen if this is still relevant.
