### ISSUE TITLE
Add support for starring and un-starring sources

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#17]
As a journalist, I want to be able to star or un-star sources, so that I can identify high priority submissions for myself and others.

Starring and un-starring is supported in the web UI, where it promotes a source to the top of the list for all users. 

For the first iteration, starring/unstarring needs not to have any side effects (e.g., position in the list view); it should just change the status of that source in the list view, which should be reflected in the display layer with a placeholder icon.

**Comment by redshiftzero** [comment]
wip so far for this is in branch `starring-unstarring`

I added a wee status field for error messages in the left sidebar for now, i.e. if a user tries to star a source and they are not logged in they get:

![screen shot 2018-10-16 at 4 43 17 pm](https://user-images.githubusercontent.com/7832803/47054012-7f735600-d164-11e8-893b-5102a7965d35.png)
