### ISSUE TITLE
 [securedrop-proxy] Support range requests (RFC 7233)

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#1707]
Related issue in SecureDrop core: https://github.com/freedomofpress/securedrop/issues/3907

Because Tor is slow and flaky, and because long downloads are slow. We may want to support range requests to allow partial downloads to resume. The behavior would be to download file to a special, permission protected directory in `/tmp` so they are cleaned up on reboots. When a download would start, the proxy application would check for the presence of the file and then send the appropriate range header to pickup where the last process left off.

We would also need to guard against multiple simultaneous downloads, possibly using some sort of `fcntl` exclusive lock to prevent race conditions with one process finishing and then another process appending before the file move happens.

**Comment by legoktm** [comment]
proxy v2 supports range requests by just passing the headers through like any other header, and streaming the bytes back. The range support is really implemented in the client/sdk, which happened in https://github.com/freedomofpress/securedrop-client/pull/2006.
