### ISSUE TITLE
 [securedrop-log] write directly to the target path in QubesIncomingLogs? 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#1722]
currently we're writing in progress logs to a NamedTemporaryFile which means that if you are observing `~/QubesIncomingLogs/<myVM>` for spicy logs about your current run of the client, you'll be disappointed as they'll only appear when we copy temp logs to  `~/QubesIncomingLogs/<myVM>`: https://github.com/freedomofpress/securedrop-log/blob/master/securedrop-log#L95

does anyone see any issue with writing directly to the final destination in `~/QubesIncomingLogs/<myVM>` and _appending_ to the log if a log of that name already exists?

**Comment by legoktm** [comment]
This was fixed in the rsyslog version (https://github.com/freedomofpress/securedrop-client/commit/29c1cf7caa08a5e3209dfac7abe94f161be1d61f)
