### ISSUE TITLE
Unstarring consistently fails on Qubes

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#173]
Note: I'm not able to reproduce this issue in the Docker development environment on current `master`, only in a Qubes environment built from the `securedrop-workstation` repo [as of today](https://github.com/freedomofpress/securedrop-workstation/commit/73517c6a53c077924cd47dc936171c11f34d666f). So, this may no longer be valid, but filing in case it's a Qubes-specific issue.

### Steps to reproduce:

1) Sign in to a SecureDrop instance that has some submissions.
2) Star a submission.
3) Once it is starred, unstar the submission.

### Expected behavior:

Submission is unstarred.

### Actual behavior:

Unstarring fails with "Failed to apply change"

**Comment by zenmonkeykstop** [comment]
Confirmed for me on current master.

**Comment by redshiftzero** [comment]
note that logs are in `~/.securedrop_client/logs/*.log` in `sd-svs` (fishing out the relevant log lines helps with repro)

**Comment by redshiftzero** [comment]
since https://github.com/freedomofpress/securedrop/issues/3977 was resolved, this is also resolved on staging instances provisioned on `develop`
