### ISSUE TITLE
 [securedrop-export] device mapper sometimes busy when exporting

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#1732]
# Description

We've removed the "Export Successful" message from `securedrop-export` and are [getting ready](https://github.com/freedomofpress/securedrop-client/pull/666) for the client to wait until either no status (meaning success) or a status containing an error message is returned. https://github.com/freedomofpress/securedrop-client/pull/666 surfaces a bug where sometimes the client receives an error message `device-mapper: remove ioctl on luks-<unique id> failed: Device of resource busy`, however the file transfer is successful. 

# More details

The bullets below indicate that the device is properly being mounted/unmounted locked/unlocked:

* Looking at `securedrop-export` logs, I see all three of these logs appear when this error is returned to the client: https://github.com/freedomofpress/securedrop-export/blob/9526fe4558a4fa2872cd4b9249ce9865030eeb99/securedrop_export/disk/actions.py#L180-L192

* I also see the 2 "Device removed" Qubes popups when we mount the device after unlocking it and the 2 "Device available" popups when we unmount and lock the device

* Exporting a file again from the client, after seeing this error, will sometimes succeed without returning the error message `device-mapper: remove ioctl on luks-<unique id> failed: Device of resource busy`

* Regardless of the error, the file seems to successfully transfer each time

**Comment by rocodes** [comment]
Fixed in #1779, closing
