### ISSUE TITLE
Apostrophes are replaced with HTML entity codes in messages, replies.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-client#175]
If a message contains an apostrophe , ie `I'm a message`, the text will be rendered as `I&#x27m a message` in the client.

Note that this isn't always the case - the message `& # " ' <a href="foo">` rendered correctly.

**Comment by ultimatecoder** [comment]
Thanks @zenmonkeykstop for such detailed observation :smiley: 

I am trying to fix this issue. Will update here as soon as I will create the PR.
