### ISSUE TITLE
document signing procedures

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#1763]
For the first non-alpha/beta release, we should be signing the SDK releases with the SecureDrop release key as we do with other SecureDrop software releases. This issue is to document the signing and upload process, as we have for the [SecureDrop core release procedures](https://docs.securedrop.org/en/release-0.12.1/development/release_management.html#release-process), noting that PSF's PyPI doesn't have great support for pgp signatures (see: https://github.com/pypa/warehouse/issues/3356 and https://kushaldas.in/posts/pypi-and-gpg-signed-packages.html).

**Comment by legoktm** [comment]
Closing now that we've merged the sdk into the client, so we're not going to be doing independent sdk releases anymore.
