### ISSUE TITLE
gvfs-bin package is deprecated in Debian bullseye and completely gone in bookworm

### ISSUE THREAD

**Issue by marmarek** [freedomofpress/securedrop-client#1787]
securedrop-workstation-config depends on it:

https://github.com/freedomofpress/securedrop-client/blob/79d34b1dcee3a93703dcdbba38b41b31fac20552/debian/control#L43

This prevents building bookworm template.

**Comment by legoktm** [comment]
I could not find any calls to `gvfs-copy` nor `gvfs-rename`, so I think we're safe to just remove this.
