### ISSUE TITLE
Without MANIFEST.in, client component does not build a working package

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-client#1874]
## Description

- We were using manifest.in to include project resources (css files etc) as well as to supply to sdist to build packages
- Now that we've removed it (#1854), when we build the client package, we're missing some necessary files; this is a place to discuss the right solution. (A solution is in progress at #1873)

## Steps to Reproduce

- Build securedrop-client from the tip of main and install it, then launch

## Expected Behavior

- Client launches successfully and all necessary files, components are in `/opt/venv/securedrop-client/lib/python3.9/site-packages/` 

## Actual Behavior

- Client builds sucessfully but resources and some packages missing

## Comments

- Should we revert to using it (probably a quick fix/bandaid that we'd not want to do indefinitely), or do as I have started to do in #1873 and include just the files we need in setup.py (probably better, but we need to be sure we don't miss any files/resources)?
- Do we need to include alembic files and other non-resource files in manifest.in, or just the files that the client relies on at runtime? If the latter then my PR should be good to go.
- Can we add a smoketest step to CI (after/part of piuparts?) that tests that not only can a package be installed/removed, but it at least can be run?

**Comment by rocodes** [comment]
It's EOD over here so I'm going to document where things have left off, and sign off. 

After modifying the `package_data` line a bit to include all the resource files we used (we'd probably be stricter, but I just wanted to see if I could build a working package)
```
    package_data={
        "": [  "*.css",  "*.ttf",  "*.gif", "*.svg" ]},
```

I unfortunately still hit some other snags after the package was built:

```
Traceback (most recent call last):
  File "/opt/venvs/securedrop-client/./bin/sd-client", line 5, in <module>
    from securedrop_client.app import run
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/app.py", line 41, in <module>
    from securedrop_client.gui.main import Window
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/gui/main.py", line 33, in <module>
    from securedrop_client.gui.widgets import LeftPane, MainView, TopPane
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/gui/widgets.py", line 76, in <module>
    from securedrop_client.gui.actions import (
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/gui/actions.py", line 17, in <module>
    from securedrop_client.conversation import Transcript as ConversationTranscript
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/conversation/__init__.py", line 1, in <module>
    from .transcript import Transcript  # noqa: F401
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/conversation/transcript/__init__.py", line 1, in <module>
    from .transcript import Transcript  # noqa: F401
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/conversation/transcript/transcript.py", line 12, in <module>
    loader=PackageLoader("securedrop_client.conversation.transcript"),
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'securedrop_client.conversation.transcript' package was not installed in a way that PackageLoader understands.
```

I've seen other folks mention this as a result of transitioning away from pkg_resources to importlib, so this may be a case for trying to build from https://github.com/freedomofpress/securedrop-client/commit/52c52054a0f51064d0aa12350d2b31948f48da40  then https://github.com/freedomofpress/securedrop-client/commit/c27f3679f4dc00de27200083c6b92ece70c62c8b  with the setup.py patch applied, to see which commit is responsible for the issue.

tbc with fresh eyes tomorrow :)

**Comment by rocodes** [comment]
Ok, it looks like just the manifest issue, nothing else -- re-including the client manifest does resolve the issue.  I have some other priorities to look at right now but then will come back to this to either revert the change for now, or make sure setup.py includes everything we need 

<details>
<summary>(manifest.in patch here)</summary>

```
user@sd-dev:~/projects/securedrop-client$ cat ~/patches/manifestin.patch 
diff --git a/client/MANIFEST.in b/client/MANIFEST.in
new file mode 100644
index 00000000..ac7c8840
--- /dev/null
+++ b/client/MANIFEST.in
@@ -0,0 +1,33 @@
+include requirements/build-requirements.txt
+include requirements/requirements.txt
+include README.md
+include LICENSE
+include changelog.md
+include setup.py
+include files/alembic.ini
+include files/client.ini
+include files/securedrop-client
+include files/securedrop-client.desktop
+include files/sd-app-qubes-gpg-domain.sh
+include files/usr.bin.securedrop-client
+
+recursive-include alembic *
+recursive-include securedrop_client *
+
+recursive-exclude alembic *.pyc
+recursive-exclude securedrop_client *.pyc
+
+
+# --- LOCALIZATION ---
+
+# Translations may appear in the tree before we consider them supported, so
+# don't include any by default.
+prune securedrop_client/locale
+
+# Explicitly include only supported translations, one line for each $LANG, like:
+#
+#     graft securedrop_client/locale/$LANG
+#
+# Please keep this list alphabetized.
+graft securedrop_client/locale/pt_PT
+graft securedrop_client/locale/zh_Hans
```
</details>

**Comment by legoktm** [comment]
Oh noooooo. I think we should just revert the MANIFEST.in patch for now and move towards the release. I also need to think a bit why I thought this was unused and update my mental model of how it's installed in the venv :/

**Comment by rocodes** [comment]
WFM. I got swept up in Tails testing (and still am), but I haven't thoroughly tested to make sure we aren't relying on the other manifests. But I don't think we are; I think the client is special because it pulls in so many extra files/resources. 

(I will amend #1873 to remove the `package_data` changes to setup.py, but I think I want to leave the `find_packages` change in because it's consistent with setup.py in the other components, and better than hardcoding)
