### ISSUE TITLE
Poetry fails with `system-site-packages` on bullseye

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1882]
## Description

Poetry configured with `virtualenvs.options.system-site-packages = true` (for e.g. <https://github.com/freedomofpress/securedrop-workstation/issues/936#issuecomment-1970461941>) fails on Debian bullseye, because one or more `dist-packages` have version strings that don't comply with [PEP 440](https://peps.python.org/pep-0440/).

## Steps to Reproduce

Apply:

```patch
--- /dev/null
+++ b/client/poetry.toml
@@ -0,0 +1,2 @@
+[virtualenvs.options]
+system-site-packages = true
```

Then do:

```sh-session
user@sd:~/securedrop-client/client$ poetry install -v
```

## Expected Behavior

Poetry creates the virtualenv, including `{dist,site}-packages`.

## Actual Behavior

```sh-session
user@sd:~/securedrop-client/client$ poetry install -v
Using virtualenv: /home/user/.cache/pypoetry/virtualenvs/securedrop-client-KGGbhkP--py3.9

  InvalidVersion

  Invalid PEP 440 version: '1.14.0-unknown'

  at ~/.local/lib/python3.9/site-packages/poetry/core/version/pep440/parser.py:70 in parse
       66│     @functools.lru_cache(maxsize=None)
       67│     def parse(cls, value: str, version_class: type[T]) -> T:
       68│         match = cls._regex.search(value) if value else None
       69│         if not match:
    →  70│             raise InvalidVersion(f"Invalid PEP 440 version: '{value}'")
       71│ 
       72│         return version_class(
       73│             epoch=int(match.group("epoch")) if match.group("epoch") else 0,
       74│             release=cls._get_release(match),

The following error occurred when trying to handle this error:


  InvalidVersion

  Invalid version '1.14.0-unknown' on package gpg

  at ~/.local/lib/python3.9/site-packages/poetry/core/packages/package.py:234 in _set_version
      230│         if not isinstance(version, Version):
      231│             try:
      232│                 version = Version.parse(version)
      233│             except InvalidVersion:
    → 234│                 raise InvalidVersion(
      235│                     f"Invalid version '{version}' on package {self.name}"
      236│                 )
      237│ 
      238│         self._version = version
```

## Comments

- **In bullseye:** https://packages.debian.org/bullseye/amd64/python3-gpg/filelist
- **The fix:** https://salsa.debian.org/debian/gpgme/-/merge_requests/4
- **In bookworm:** https://packages.debian.org/bookworm/amd64/python3-gpg/filelist

**Comment by legoktm** [comment]
Interesting, pip does less validation so it gracefully handles it (with triple equals) instead of erroring out like poetry. You do know the Debian package maintainer if we want to get the fix into bullseye :), but even then the next bullseye release is going to be a few months away (most likely), at which point we'd hopefully be on bookworm... (I think bookworm's pip would error out on it but that's not a major issue :))

**Comment by cfm** [comment]
Raised in <https://salsa.debian.org/debian/gpgme/-/merge_requests/4#note_471475>.

**Comment by cfm** [comment]
We may have a way forward per <https://salsa.debian.org/debian/gpgme/-/merge_requests/4#note_479936>.  @legoktm, I'll draft this and confer with you next week.
