### ISSUE TITLE
Reset alembic migrations for upcoming 4.2 fresh install

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-client#1961]
## Description

Because we are having everyone do a fresh install on 4.2, we should reset all the alembic migrations because we know users have no legacy data to migrate.

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?

Less unnecessary code running on each client startup.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?

Shouldn't.

**Comment by cfm** [comment]
@legoktm, do you want to include this in an `0.11.0-rc2`?  There's only one non-initial version in the Alembic history, so the optimization would be minimal.  But it's an easy chore and amenable to smoke-testing.

**Comment by legoktm** [comment]
I totally forgot about this; I think we're late enough in the cycle and also the value is pretty small that we should just skip.
