### ISSUE TITLE
Add support for viewing downloaded documents

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#20]
As a journalist I want to be able to view a file submitted by a source in a common format (e.g., PDF, JPG, DOC, AVI) so that I can inspect it for potential newsworthiness.

As shown in the [messaging prototype](https://eloquence.github.io/workstation-messaging/), after a document has been downloaded, it should be possible to launch an appropriate viewer application to  open a decrypted submission, ideally in a hardened disposable VM.

**Comment by redshiftzero** [comment]
Hey @ntoll this is the next highest priority ticket, which to replace the on click handler associated with the open button (that appears when a file is downloaded):

<img width="674" alt="screen shot 2018-11-04 at 7 30 28 pm" src="https://user-images.githubusercontent.com/7832803/47976625-206c7700-e068-11e8-930b-0f793c4ab617.png">

with a handler that will open the file. The desired behavior of the file handler is:

* On Qubes: subprocess out to `qvm-open-in-vm '$dispvm:sd-svs-disp' filename` (we'll have someone test your PR on Qubes to ensure that this part works as anticipated)

* On non-Qubes: ideally we'd subprocess out to either `xdg-open filename` (linux) or `open filename` (macOS), but as this is for developers only, getting open working is not super important and we can just log a line to indicate that `user opened file <filename>`, and that open is supported on Qubes only

The proxy attribute [here](https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/logic.py#L108) determines if the client is being executed on Qubes or not (True for Qubes, False for non-Qubes).

**Comment by kushaldas** [comment]
>On non-Qubes: ideally we'd subprocess out to either xdg-open filename (linux) or open filename (macOS), but as this is for developers only, getting open working is not super important and we can just log a line to indicate that user opened file <filename>, and that open is supported on Qubes only

:+1:  to this. Only logging a line in case of non-Qubes system sounds so better.

**Comment by ntoll** [comment]
On it. :-)

**Comment by ninavizz** [comment]
Still from prototype that demonstrates opening a doc in a Disposable VM. Note: activity messaging (top-left of screen) and dialog that appears to let the user know what's going on for the 3-5sec it will take to boot the Disposable VM. Implemented as-shown here, a Beta goal—leaving here for reference. https://projects.invisionapp.com/share/R8OODHKSWY3#/screens/326625556
