### ISSUE TITLE
securedrop-client's Config object should support non-str types

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-client#2041]
## Description

From https://github.com/freedomofpress/securedrop-client/pull/2006/files#r1619642194, where we want to have an `int` configured via QubesDB/environment. The `Config` object should validate at load time and convert it to an int so calling code doesn't need to.

**Comment by cfm** [comment]
I think we can keep this simple if we limit runtime type-checking to our own `Config.load()`:

```python
>>> from dataclasses import dataclass
>>> @dataclass
... class Config:
...   x: str
...   y: int
... 
>>> c = Config(x="foo", y=1)
>>> isinstance(c.y, Config.__annotations__["y"])
True
>>> c = Config(x="foo", y="1")
>>> isinstance(c.y, Config.__annotations__["y"])
False
```

Note that this wasn't really an oversight on our part: `FOO_TIMEOUT = os.environ["FOO_TIMEOUT"]` requires a manual `int()` anyway, and here at least we can do it declaratively and generally.

**Comment by legoktm** [comment]
After looking around a bit, I discovered the [`fields()`](https://docs.python.org/3.11/library/dataclasses.html#dataclasses.fields) method, which in addition to getting the type, also allows checking the default value.
