### ISSUE TITLE
Release securedrop-client 0.10.2

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-client#2049]
This issue tracks the SecureDrop Client release 0.10.2. It will be organized by:

- Release Manager: @rocodes 
- Deputy Release Manager: @cfm 

This will be a hotfix release based on 0.10.1, including the following changes:
- Update signing key for Qubes 4.1 (bullseye), with same expiry as #2035

To reduce testing overhead, the securedrop-keyring package may be released independently, leaving other deployed securedrop-client packages at 0.10.1.

SecureDrop maintainers and testers: As you QA this release, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the release milestone for tracking (or ask a maintainer to do so).

## Test plan

See https://github.com/freedomofpress/securedrop-workstation/issues/1057

## Release tasks

- [ ] Check if there are any security bug fixes waiting to be pulled into the RC
- [ ] Check if there are any translations:
    - [ ] pending merge into `main`
    - [ ] pending inclusion as a supported language in [`MANIFEST.in`](https://github.com/freedomofpress/securedrop-client/blob/main/MANIFEST.in)
- [ ] Update changelog
- [ ] Create test plan
- [ ] Refresh nightlies
- [ ] Begin formal QA using nightlies; refresh nightlies as needed
- [ ] Build production package in standard [build environment](https://github.com/freedomofpress/securedrop-builder/wiki/FAQ#how-do-i-create-a-local-environment-suitable-for-building-packages)
- [ ] Sign production package
- [ ] Perform final pre-flight testing using apt-qa.freedom.press
  - [ ] **Localization:** In a dispVM, change your locale (e.g.: `export LANG=es_ES.utf-8; dpkg-reconfigure locales`), run the Client, and confirm that the application is translated.
- [ ] Publish production package
- [ ] Publicize release via support channels

**Comment by rocodes** [comment]
Testing will be in conjunction with https://github.com/freedomofpress/securedrop-workstation/issues/1057, see test plan in that ticket

**Comment by rocodes** [comment]
Closed by https://github.com/freedomofpress/securedrop-apt-prod/pull/140, comms have gone out
