### ISSUE TITLE
Failing to export to veracrypt drive

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-client#2118]
* [x] I have searched for duplicates or related issues

## Description

Veracrypt device provisioned according to the docs, fails to get detected

## Steps to Reproduce

SDW 1.0.0. Followed the [provisioning instructions](https://workstation.securedrop.org/en/stable/admin/reference/provisioning_usb.html#creating-a-veracrypt-encrypted-drive).

## Expected Behavior

Drive properly detected on export.

## Actual Behavior

Fails to detect drive:

![drive](https://github.com/user-attachments/assets/4efb8e86-dbbe-4407-867f-dd43f66fec1d)

## Comments

This is the output in sd-log:
![log-output](https://github.com/user-attachments/assets/e452f225-a655-435a-8dd3-28b499d8cee8)

**Comment by rocodes** [comment]
@deeplow : what is the output of `udisksctl status` in sd-devices with this drive attached, and then followup, if the drive is detected, what is the output of `udisksctl info -b /dev/sdX`  ?

**Comment by rocodes** [comment]
Also, just for clarification: This is the error message that shows up when a VeraCrypt drive is locked. Per the instruction text [and the docs](https://workstation.securedrop.org/en/stable/journalist/submissions.html#exporting-to-an-export-usb) , you need to manually unlock the drive from sd-devices before you can export to it - if you're unlocking the drive and still seeing this error, the output of the above two commands in my previous comment will be helpful.  (Or, if you think the docs or the message in the wizard aren't clear enough, maybe we can improve on them too.) Thank you!
