### ISSUE TITLE
Failed to Print non-PDF document 

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-client#2119]
## Description

Failed to print

## Steps to Reproduce

SDW 1.0.0

Print ".doc" file (any should fail).

## Expected Behavior

File printed

## Actual Behavior

After clicking "continue" on the print dialog, the dialog goes away but nothing happens. I would have expected the xpp dialog to show up.

What's actually happening is some memory access issues due to grsec enforcement: (see paste [bellow](https://github.com/freedomofpress/securedrop-client/issues/2119#issuecomment-2231342486))

![deniedmmpa](https://github.com/user-attachments/assets/407ba94e-5174-489e-b396-d6f6cac56ce7)

However, from paxctld.conf this seems to be [a known situation](https://github.com/freedomofpress/securedrop-client/blob/4b7495cf8bd1dc11e2f52fb772fad55aaa01edab/workstation-config/paxctld.conf#L115). So I have questions about this being the source of the issue.

## Comments

I have tried `unoconf` in sd-devices and it worked fine. So, there is definitely some part of the program getting restricted from executing it.

**Comment by rocodes** [comment]
On 4.1, those loglines are present, but printing .doc (etc) files is successful.  On 4.2, I can reproduce the issue. I don't think it's a grsec problem, I think it's a client bug / QProcess problem - if you inspect the client loglines, the client thinks printing has occurred successfully.  I think the qprocess for conversion is completing and signaling to the client "a process is complete!" and so the client exits before the actual print operation can occur, but I'm not totally sure (and that isn't a compelling reason why it wouldn't work on 4.2). I'll investigate more tomorrow.
