### ISSUE TITLE
every call to ./run.sh starts a new gpg-agent process

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#215]
Every run of the development environment creates (by default) a new temp dir, and each of these get their own `gpg-agent` process. At fist glance, there doesn't seem to be a way around this that doesn't require changing global options.

From `man gpg2`, it can't be disabled:
```
       --use-agent
       --no-use-agent
              This is dummy option. gpg always requires the agent.
```

**Comment by redshiftzero** [comment]
Resolved in #252
