### ISSUE TITLE
Create Debian package

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#22]
As with other workstation dependencies, we should create a Debian package for the client so that it can be installed easily as part of provisioning. See https://github.com/freedomofpress/securedrop-workstation/issues/136 for background and discussion about packaging approaches.

**Comment by redshiftzero** [comment]
Next steps on this are:

- [ ] @kushaldas / @joshuathayer  to push first pass through the packaging process to https://github.com/freedomofpress/securedrop-debian-packaging
- [ ] @kushaldas to be onboarded to apt-test if not done yet for https://github.com/freedomofpress/securedrop-proxy/issues/6
- [ ] once #30 and #31 are implemented, we do a second pass through the packaging process, and push the changes up to https://github.com/freedomofpress/securedrop-debian-packaging
- [ ] @kushaldas to push deb package to apt-test 
- [ ] we file a followup issue to modify salt logic in the workstation repo to use this package

**Comment by eloquence** [comment]
@kushaldas and/or @joshuathayer, could you provide an update on the status of this ticket, please?

**Comment by kushaldas** [comment]
@joshuathayer Can you please push your `debian` directory to the packaging repo?

**Comment by conorsch** [comment]
Candidate PR submitted here by @joshuathayer : https://github.com/freedomofpress/securedrop-debian-packaging/pull/3

**Comment by redshiftzero** [comment]
That PR has been merged :tada: - so, we've done a first pass here, but we should _hold off on pushing a package to apt-test_ until we have some more functionality in `securedrop-client`. The reason for this is that once #40, #19, and #20 are completed, then we can modify `master` in the securedrop workstation repo to use `securedrop-client` instead of Tor Browser. 

I propose at the end of this week we evaluate the functionality that's been merged in and go from there.

**Comment by kushaldas** [comment]
Just now figured that we are missing the PR on this repo for the `setup.py` and `MANIFEST.in`, `requirements-build.txt` files, these are required to create the source tar ball from which we can create the Debian package.

**Comment by kushaldas** [comment]
>@joshuathayer Can you please push those in a PR?

I will add these up in the next PR I will make as those will be required to test out all the config/database changes I am going to make.

**Comment by kushaldas** [comment]
https://github.com/freedomofpress/securedrop-client/pull/86 has some related update, also in https://github.com/freedomofpress/securedrop-debian-packaging/pull/4 @redshiftzero Please have a look :)

**Comment by redshiftzero** [comment]
this is done: https://apt-test-qubes.freedom.press/pool/main/s/securedrop-client/
