### ISSUE TITLE
Support client side e2e encryption

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#221]
If a source provides a public key to the journalist, the journalist should be able to import the public key and automatically encrypt to it. This should be displayed in the UI some how.

Note: This is not the same as the the client encrypting replies before sending them to the SecureDrop API where they would ordinarily be encrypted with the application generated public key. This ticket means an additional layer of encryption.

**Comment by eloquence** [comment]
We're unlikely to provide a client workflow for importing reply keys, as any end-to-end encryption support will likely need to be significantly more user-friendly than manual GPG encryption. We're tracking ideas for E2E encryption in SecureDrop here:
https://github.com/freedomofpress/securedrop/issues/92 

We're tracking the idea of per-journalist keys here:
https://github.com/freedomofpress/securedrop/issues/144

Closing this issue for now until we have team consensus on how to approach end-to-end encryption.
