### ISSUE TITLE
use locks/mutexes to prevent race conditions when creating/destroying threads/attributes

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#222]
For example, we have `MessageSync` and `ReplySync` that are created at login. These should be stopped during logout. These creations/stops should be done via

```python
def __init__(self, ...):
    self.lock = threading.Lock()
    # moar stuff

def do_stuff(self, ...):
    with self.lock.lock():
        # do the stuff
```

(more or less)

**Comment by redshiftzero** [comment]
Thread safety issues should be resolved now, replysync and messagesync objects are both gone and this logic is done via a single queue (the general queue) now, closing
