### ISSUE TITLE
exercise `make regenerate-sdk-cassettes` in CI

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#2224]
## Description

Until we have #1992, we might want to add a CI job that runs `make regenerate-sdk-cassettes` against `securedrop`'s `make dev`.  We wouldn't commit the results; we'd just make sure that the regeneration process itself succeeds, proving that the Client and SDK test suites aren't bound to any particular server state.

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?

No user-facing implications.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?

No threat-model implications.

## User Stories

- #2223

**Comment by legoktm** [comment]
I haven't looked to see why this case isn't covered by it yet, but ideally we'd be able to reuse the existing sdk-with-server job for this purpose.

**Comment by cfm** [comment]
You're right: `sdk-with-server` *does* exercise `make regenerate-sdk-cassettes`.  Closing this and moving back to #2223.
