### ISSUE TITLE
UI doesn't re-render correctly

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#226]
I don't know how I did this, but I did. Switching away from the view and returning doesn't fix it.

![screenshot_2019-01-15_11-27-05](https://user-images.githubusercontent.com/3998464/51174645-938c3800-18b8-11e9-9645-14c57d3bb391.png)

**Comment by eloquence** [comment]
Hi @heartsucker, any additional information about this bug would be much appreciated. Is this on latest `master` or in a feature branch? Can you recall any specific actions that resulted in this state?

**Comment by heartsucker** [comment]
I saw this once in the past on a feature branch but crashed it before I got a screenshot. I would guess it had something to do with resizing the window? If I can reproduce, I'll add comments.

**Comment by eloquence** [comment]
In latest `master`, I can easily reproduce rendering issues if I

1) Create a new source via the source interface
2) Refresh the client
3) Add another message from that source via the source interface
4) Refresh the client

Before the new message is downloaded and displayed, there are more overlapping balloons than expected. This goes away once the message is downloaded. Not quite the same as the level of insanity in your screenshot, but possibly related.

![balloontrouble](https://user-images.githubusercontent.com/213636/51408401-6ab3af00-1b13-11e9-863e-a64e81b03edf.png)

**Comment by heartsucker** [comment]
I suspect these lines caused the error:

https://github.com/freedomofpress/securedrop-client/blob/d51748e023195b3a17430f3757810210eebd6d56/securedrop_client/gui/widgets.py#L670-L677

I thought the `takeAt()` method removed the widget, but maybe it doesn't.
