### ISSUE TITLE
Document application architecture

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-client#228]
As the application complexity increases, it might be useful to document (for example using a diagram) the high-level application architecture to better understand the different major components at a glance and how they interact with each other.

This will help both developers and newcomers, especially those not familiar with Qt and Qt-specific patterns.

**Comment by eloquence** [comment]
@redshiftzero and @creviera have been working on a GDoc with some initial notes; for the 7/24-8/7 document, we've committed to aim to clean up this document to a degree that it can readily be turned into a first docs PR. This will not include any architectural diagrams, just yet.

**Comment by creviera** [comment]
This is where we're keeping the WIP-architecture docs: https://github.com/freedomofpress/securedrop-client/wiki/Architecture, which right now is very minimal and hopefully will steadily grow and become more detailed as we devote a bit of time to them each week and build out the client.

**Comment by kushaldas** [comment]
I am approving the current document. We have to remember to keep updating it for any architectural change. @creviera Thank you for this.
