### ISSUE TITLE
[v0.0.6] signing in succeeds, but the further API calls return 403

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#232]
As in the title, signing in via the client succeeds, but the further API calls fail with Forbidden.

Server logs:

```
172.17.0.1 - - [24/Jan/2019 11:25:26] "POST /api/v1/token HTTP/1.1" 200 -
172.17.0.1 - - [24/Jan/2019 11:25:27] "GET /api/v1/sources HTTP/1.1" 403 -
```

I am running a mashup of versions of things:
- sd-client at v0.0.6
- sd-workstation at `0223bb0`
- sd at `5bbd3fa4a`.

The errors from the client logs are:

```
securedrop_client.logic:74(call_api) ERROR: Error in parsing JSON
securedrop_client.logic:82(call_api) INFO: Thread returned from API, but it had timed out.
```

Additionally, there is:

```
securedrop_client.logic:364(sync_api) DEBUG: You are authenticated, going to make your call
```

The root cause is that the client hits this line on the server (malformed token):

https://github.com/freedomofpress/securedrop/blob/b662cd136ee6c497dd0ebc044411bcea33e29cc8/securedrop/journalist_app/api.py#L42

This itself is caused by a different in behavior of the SDK and the docs.

The docs state that a valid auth header is of the form `Authorization: Token XXXXX` (note the capital `T` in `token`), to find it `grep` for the following line in the API docs:

```http
Authorization: Token eyJhbGciOiJIUzI1NiIsImV4cCI6MTUzMDU4NjU4MiwifWF0IjoxNTMwNTc5MzgyfQ.eyJpZCI6MX0.P_PfcLMk1Dq5VCIANo-lJbu0ZyCL2VcT8qf9fIZsTCM
```

The check in the code matches the API docs and was added by me in https://github.com/freedomofpress/securedrop/pull/4054. This change is stricter than the code we were running before which is why this divergence was not noticed until now.

The SDK uses a lowercase `t` in `token`.

https://github.com/freedomofpress/securedrop-sdk/blob/6263542e67f8ee361e691b1b404c8e95a2fc82ed/sdclientapi/__init__.py#L128-L133

Additionally, I think the client isn't (at this version or the current) able to bail into a logged out mode once the token starts 403-ing.

**Comment by kushaldas** [comment]
@heartsucker I am guessing there is a commit somewhere in the server which updated the `t` to capital. And, there was no follow up ticket got filed here to mark that API has changed.

**Comment by kushaldas** [comment]
We should add a proposal, nothing can be changed in the server API without a corresponding SDK issue to track.

**Comment by heartsucker** [comment]
The docs always said `Token` and the server never checked that the token preceding actual auth string was equal to `Token` (or anything at all). The divergence was always there and when we made the implementation (server) match the spec (docs), the client/sdk borked.

**Comment by redshiftzero** [comment]
We have in the API documentation and code `Token`, so how about we use `Token` everywhere - i.e. replace `token` with `Token` in the SDK. @heartsucker or @kushaldas want to make a PR making that change? Then we can do an SDK release. 

Note that to detect this kind of divergence going forward we'll want to do one or more of the following:
* Run the SDK tests against the latest version of the SecureDrop API 
* Implement https://github.com/freedomofpress/securedrop/issues/4030
* As PR submitters / reviewers, cross-check any change to the API with the SDK / client

**Comment by kushaldas** [comment]
> 
> Note that to detect this kind of divergence going forward we'll want to do one or more of the following:
> 
>     * Run the SDK tests against the latest version of the SecureDrop API
> 
>     * Implement [freedomofpress/securedrop#4030](https://github.com/freedomofpress/securedrop/issues/4030)
> 
>     * As PR submitters / reviewers, cross-check any change to the API with the SDK / client

I would love to have all 3 of those.

**Comment by eloquence** [comment]
I can confirm that updating to version 0.0.6 of the SDK resolves the issue in my local dev environment.
