### ISSUE TITLE
QXcbConnection error while client is running

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#236]
Non-fatal error printed to stderr.

```
QXcbConnection: XCB error: 8 (BadMatch), sequence: 590, resource id: 67108877, major code: 42 (SetInputFocus), minor code: 0
QXcbConnection: XCB error: 8 (BadMatch), sequence: 593, resource id: 67108877, major code: 42 (SetInputFocus), minor code: 0
```

**Comment by redshiftzero** [comment]
what are the STR for this one?

**Comment by creviera** [comment]
Here are the STR for a related error:

#### Error message

```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 606, resource id: 13886767, major code: 40 (TranslateCoords), minor code: 0
```

#### STR

1. Start the client
2. Close the login modal without logging in (leave the client window open)

**Comment by eloquence** [comment]
These STR no longer apply as the login window now closes the client. Needs repro or we can close if we're confident that we're no longer seeing this.

**Comment by creviera** [comment]
correct, this has been fixed for a long time but forgot to close
