### ISSUE TITLE
[replies] grey out replies box when the user is not logged in

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#243]
A user should not be able to send a reply when the journalist is not signed in. Instead the reply box should appear greyed out with a note indicating "please log in to reply to a source!" or something similar.

@ninavizz please drop any additional thoughts on this one!

As a not logged in journalist user, I want to see on screen how to reply to a source so that I know I need to log in. 

Note: The PR that addresses this issue should revert the changes in f8441082

**Comment by ninavizz** [comment]
So: the "top-bar" in the Client, should always show the text shown in these wireframes... but I dunno if the existing Client build, has such a bar. FYI. 

To see Online/Offline, toggle on the top bar of this clickable(ish) wire: https://invis.io/X4QEP5Y9EAT#/345671069_0_New_-_DR_On-_OFFLINE

- Delete Source functionality also goes away in Offline Mode
