### ISSUE TITLE
Latest version of PyQt (5.12) is causing segmentation fault

### ISSUE THREAD

**Issue by ultimatecoder** [freedomofpress/securedrop-client#248]
* **Description:** Latest version of PyQt5 which is `5.12` is causing `Segmentation fault`.

* **Steps to reproduce:**
    1. Update the python dependencies using `pipenv update` command.
    2. Run the SecureDrop client using `./run.sh`.
    3. Enter credential and OTP for demo journalist account.
    4. Click on one of a source from the source list menu on the left side.
    5. BANG!

* [**Video**](https://youtu.be/hDyyGW80x0Q)

**Comment by redshiftzero** [comment]
Note that as a workaround until #254 is merged one can use pyqt==5.10.1 which does not segfault
