### ISSUE TITLE
[client styling] Refactor client grid layout

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#259]
**Epic:** UX Parity between prototypes & coded client (#261) 

**This Story:** Re-Factor Client Grid
_Refactor layout of client according to "Functional Regions" as mapped-out in the screens at the below Zeplin link._

**Reference materials:** https://zpl.io/V4OMBzy

---
Details, This Story:
- Nina/Allie discussed in person, so hopefully much of that carries over to this
- Functional regions in "Alpha" screen reflects current state of Client build
- Functional regions in "Beta" screen reflects how it all should be re-jiggered to meet current UX vision
- Branding art for Beta & final icon for "Inbox" TBD (blocked by [SD-UX 36](https://github.com/freedomofpress/securedrop-ux/issues/36))
- Ignore things in the Branding pane (such as _Trash_, _Unreviewed_, _All Starred_ and  and the _Filter By Codename_ bar) that appear in screens and have no functional parity to what's already been built in Alpha. Those bits have yet to become formalized as features in Issues. 😈 
- See provided screens (at Zeplin link, above) for horizontal scaling of columns as window size is horizontally reduced
  - First reduce the width of the Messages/Reply column, while retaining the size of the Branding and Sources List columns
  - After the Messages/Reply column reaches its minimum-allowable width, begin to reduce the width of the Sources List column
  - With the 2 right columns reduced to their minimum widths, the window should not be able to scale-down further. 
  - Branding column should not scale
- Click on screens in Zeplin to see hex values, font styles, and padding specs. 😸

**Comment by eloquence** [comment]
For clarity, per our discussion, to consider this issue resolved, iconography does not need to be done yet; if it helps to get the sizing right or avoid weird text cut-offs, that's fine, but otherwise this can be done in subsequent PRs.

**Comment by ninavizz** [comment]
IOU a gradient for the background on the Messaging and Source List columns! Grateful to @eloquence's spreadsheet for reminding me of that! 😸

**Comment by eloquence** [comment]
This was moved to "Done" but not closed. Judging by the original issue description, which is chiefly focused on the layout, we can reasonably consider this first iteration done and handle additional changes in more tightly scoped follow-up issues and PRs.
