### ISSUE TITLE
Add mypy in the CI

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#26]
[mypy](http://mypy-lang.org) should run as part of CI.

**Comment by heartsucker** [comment]
I suggest we close this ticket and merge it with #25. Adding annotations but not a CI check will be an awkward blocker toward getting everything typed. It will also mean other PRs that land between #25 this ticket will undo the work of #25.

**Comment by redshiftzero** [comment]
agree with @heartsucker, closing in favor of #25
