### ISSUE TITLE
[client styling] Create and place auth widget

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#264]
**Epic:** UX Parity between prototypes & coded client (#261) 

**This Story:** Create and place auth widget
_Within the "Functional Regions" mapping, is a widget to sign-in/sign-out, which is different from today's static button. This Issue is to simply get a widget in place; styling may be as rich or as basic as is deemed necessary to get the Epic satisfactorily complete._

**Reference materials:** [Static spec uploaded to Zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5c86c91ea1202f046e7d92f4) (and shown in below PNGs)

![image](https://user-images.githubusercontent.com/8262612/54314807-dce7c380-4599-11e9-8d82-d1f24f30093e.png)
![image](https://user-images.githubusercontent.com/8262612/54314667-81b5d100-4599-11e9-8a10-f1c5d34d17a3.png)
![image](https://user-images.githubusercontent.com/8262612/54316701-a52f4a80-459e-11e9-9632-e5b9f04277ed.png)

---
**Design Spec:** See flat multi-state spec above! :)
**"Active" Button Animation:** [LDS Ripple](https://loading.io/css/)
```
.lds-ripple {
  display: inline-block;
  position: relative;
  width: 64px;
  height: 64px;
}
.lds-ripple div {
  position: absolute;
  border: 4px solid #fff;
  opacity: 1;
  border-radius: 50%;
  animation: lds-ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(2) {
  animation-delay: -0.5s;
}
@keyframes lds-ripple {
  0% {
    top: 28px;
    left: 28px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: -1px;
    left: -1px;
    width: 58px;
    height: 58px;
    opacity: 0;
  }
}
```

**Comment by ninavizz** [comment]
Note: Colors will be added-in to Zeplin spec & here, following 14 March's VisDe review.

**Comment by ninavizz** [comment]
If possible to implement this WITH lowercase letterforms in the ID badge, and with a TBD font, that would be awesome. 

I've been wavering between the necessity to do uppercase vs lowercase based on prior studies I did 13 years ago when at Yahoo!, but there are many more digital fonts available today... and based on how nicely the GitHub's chicklet labels look in [this test Issue](https://github.com/freedomofpress/securedrop-ux/issues/50), I'm going to try to find a font that might work to keep these lowercase. Can't do until Thursday afternoon, tho.

**Comment by ninavizz** [comment]
^ BUMP @creviera... added into spec the "Sign In" pane w/ error message. 

Per the acceptance criteria, "placement" is this Issue's goal—all styling optional, and a separate Issue will be created to nail that, after everything's been placed & made functional. 😃

**Comment by creviera** [comment]
This issue can be closed by this PR: https://github.com/freedomofpress/securedrop-client/pull/278

I captured things left to do from these tickets:
* auth widget styling: https://github.com/freedomofpress/securedrop-client/issues/285
* refresh status bar: https://github.com/freedomofpress/securedrop-client/issues/279
* login window: https://github.com/freedomofpress/securedrop-client/issues/286
