### ISSUE TITLE
Speech bubble size changes when "<Message not yet downloaded>"

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#269]
## Description 

Speech bubble style looks different when containing the message string `<Message not yet downloaded>` or `<Reply not yet downloaded>`. We want this to look more seamless between the two states where a message isn't download and a message is downloaded and displayed.

## Steps to reproduce

1. Run the client
2. Submit a message from a source that you already have selected in the client
3. Now _quickly_ hop over to the client and see the speech bubble size change before and after a decryption

**Comment by eloquence** [comment]
This is a very old issue; I don't see this in current versions of the client: the bubble styling and size is identical before and after loading (in case of a message that doesn't exceed the default size). Please reopen if I'm mistaken.
