### ISSUE TITLE
If GPG decryption fails, downloaded file is deleted causing message to never be displayed to user

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#276]
This bug was introduced in #262. I should have caught this during manual testing during my review.

# STR

1. Start the client
2. Before signing in, go to the `sdc-home` directory and run `gpg2 --homedir gpg --delete-secret-and-public-keys 65A1B5FF195B56353CC63DFFCC40EF1228271441` to delete the secret key
3. Sign in
4. Wait for submissions / replies to download (watch the logs)
5. Terminate the client
6. Start the client (`run.sh` will re-add the PGP keys)
7. Click on a source

# Expected Results

The client decrypts the replies.

# Actual Results

The client cannot find the encrypted file because it does not exist. The file is marked as downloaded, so the client will never attempt to redownload it. Thus, it will never be able to be displayed to the user.

# Root Cause

Note the `os.unlink` in the following snippet.

https://github.com/freedomofpress/securedrop-client/blob/03d4acdb401427454b447ed3bd263b428609d7e8/securedrop_client/crypto.py#L57-L66

This unlink happens regardless of success/failure of the decryption. We should only unlink the file after we have marked it as decrypted in the database.

**Comment by redshiftzero** [comment]
We should have the message and reply threads find messages and replies for which either `is_downloaded=False` or `is_decrypted=False` then attempt to take the relevant action based on the stage of the file processing (explicitly: it should download and decrypt if download was not completed, just decrypt if decryption was not completed). 

I think at a later date we will want to stop attempting to decrypt files if they have failed (e.g. if the workstation has been provisioned with the wrong submission key, the decryption will never succeed and we don't want to have threads continuously trying to retry), but we can implement that in a followup.
