### ISSUE TITLE
Create a top pane for refresh, messages, and errors

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#279]
## Description

* Apply text styles for Refresh timestamp, run through https://app.zeplin.io/project/5c807ea562f734bd2756b243/dashboard to get an idea of what colors and font to use
* Add Static & Active states to the refresh icon, see https://github.com/freedomofpress/securedrop-ux/issues/17#issuecomment-472163715

Parent issue: https://github.com/freedomofpress/securedrop-client/issues/261

**Comment by creviera** [comment]
Also add space in the center for displaying error messages

**Comment by heartsucker** [comment]
That Zeplin project requires a login.
