### ISSUE TITLE
Adjust clickable target area in auth widget and style sign-out menu

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#285]
## Description

Remaining work for auth widget from https://github.com/freedomofpress/securedrop-client/issues/264

- [x] Make clicking on journalist's name trigger the sign-out drop-down menu (https://github.com/freedomofpress/securedrop-client/issues/298)
- [ ] Match clickable target area to highlighted spec below
- [ ] Make sign-out menu white with an arrow pointing from drop-down menu

Once specific colors are decided on:

* Make journalist username's font color a lighter during hover-over action
* Change color of highlighted menu option

Auth widget selected:
![auth-widget-selected](https://user-images.githubusercontent.com/4522213/55119701-1d723180-50b0-11e9-93b7-d759e11487bd.png)

Auth widget clicked:
![auth-widget-clicked](https://user-images.githubusercontent.com/4522213/55119784-76da6080-50b0-11e9-933a-70b13e539e99.png)

**Comment by ninavizz** [comment]
Note: dotted-pink line and yellow highlight, were part of my annotations—not part of the intended design. 😄

**Comment by creviera** [comment]
This task can be marked as done once PR #293 gets merged:
* Make clicking on journalist's name trigger the sign-out drop-down menu

**Comment by eloquence** [comment]
I've updated the issue description per Nina's comment, and transformed the tasks into a checklist.

Ensuring that the clickable area matches the spec (and having a mouse cursor affordance for same - #415) is IMO especially important for usability. Right now, clicking the initials does not open the drop down menu.

**Comment by eloquence** [comment]
Adjusting the clickable target area to include the initials is a nice candidate issue for @ntoll so keeping on milestone for now.

**Comment by eloquence** [comment]
As clarified in #850 the sign-out design in this issue is outdated. #976 has improved the clickable target area, but is not fully to spec. I'm going to close this issue and open a new tightly scoped one to further tweak the click target area.
