### ISSUE TITLE
Implement download/decryption activity indicator (first iteration)

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#288]
Related to #261, but note that we currently do not have _any_ activity indicator in the client, so this is not merely a styling question.

Per @redshiftzero the current stages a successful download goes through are as follows:

1. Not downloaded
2. Download started - download user feedback begins
3. Download finishes - download user feedback ends
3. Decryption is attempted - decryption user feedback begins
4. Decryption is finished - decryption user feedback ends
5. "Open" is shown

Currently, the client skips directly from "Download" to "Open" without any activity indication in between.

@ninavizz has committed to delivering iterated designs prior to the 4/3-4/17 sprint kick-off, ideally these designs should cover:
- download activity indicator and place for contextual messages
- decryption activity indicator and place for contextual messages
- final "Open" state

For the purpose of a first iteration, the following are **out of scope**:
- displaying progress (0%, 25%, etc.)
- displaying filenames of decrypted files

**Comment by ninavizz** [comment]
[This spec](https://zpl.io/beD5dzl) was delivered back in April. I'll examine the numbers up above, and update it accordingly—asd well as a MOSCoW breakdown of how I'm seein' the ideal state coming together across iterations.

**Comment by ninavizz** [comment]
Also, this is how to determine grouping of files in one unified pane vs piecemeal, per the spec. Likely not going to make it into Beta, but putting this here to get it on the record:

_In order to make sense of the messages and files from a Source in the Messages Pane;_

**As a Journalist;
I want to see all messages from a Source, aligned to the left-edge of the Messages Pane.**

And I want to see all messages from myself and my newsroom peers, aligned to the right-edge of the Messages Pane.
I also want to see all items shown in descending chronological order, with the newest items towards the bottom and the oldest items towards the top.
Because this is an established pattern.
When both messages and files are sent within the same 12hr window

**Scenario: Source sends 1 message and 1 file, 2 hours apart**

> Given I'm a logged in Journalist, at 8am.
> When I select the Source "Benign Artichoke" in the Sources List.
> And “Benign Artichoke” sent 1 message at 2:30am and 1 file at 3:30am
> Then I see 1 message appear above 1 file, in a ‘single session’ grouping along the left edge of the Messages Pane.


**Scenario: Source sends 1 message and 2 files, over a 2 hour timespan**

> Given I'm a logged in Journalist, at 8am.
> When I select the Source "Deviant Potato" in the Sources List.
> And “Deviant Potato” sent 1 file at 4:32am, 1 message at 5am, and a second file at 6:20am
> Then I see 1 message appear above 2 files, in a ‘single session’ grouping along the left edge of the Messages Pane.

**Scenario: Source sends 1 file and 1 message, +12 hours apart**

> Given I'm a logged in Journalist, at 10am on a Thursday.
> When I select the Source "Disco Bunny" in the Sources List.
> And “Disco Bunny” sent 1 file at 2:30am on Monday and 1 message at 12pm on Wednesday
> Then I see 1 file appear, a gap of whitespace, then one message, along the left edge of the Messages Pane.

**Comment by ninavizz** [comment]
This is the current state of the Client, 28 May 2019:
![image](https://user-images.githubusercontent.com/8262612/58515962-4cae2900-815b-11e9-9cd1-ec697c562947.png)

@eloquence My own prioritization of Beta files pane stuff (and this ticket within that):

## MUST
1. Replace today's uglypants/temporary icon with a less unattractive icon — same size, etc.
2. Add "Active State" to today's widget, that would Show Icon and Text both at 40% alpha, and later be expanded to include an animation spinner.
3. **Implement "Things are happening, packets are flying" Global Network Activity Indicator to trigger when a download is started.**
4. Add `LDS-ring` animation atop icon for file's download/decrypt Active state. Retain "Active" UI state as decryption is happening, even though Global Network Activity Indication will cease at that point.
5. Tackle #163 

## SHOULD
1. Begin to apply proper/final [File Pane Styling](https://zpl.io/beD5dzl)

**Comment by eloquence** [comment]
Since the above comment this has undergone further revisions; the current proposed pre-beta and post-beta designs can be found here:
https://github.com/freedomofpress/securedrop-ux/issues/55#issuecomment-506007037

**Comment by ninavizz** [comment]
Spinner in Zeplin mockup: https://github.com/freedomofpress/securedrop-ux/issues/17#issuecomment-471733169

:)

**Comment by eloquence** [comment]
@ntoll: Noting that this is higher priority than #135 in this sprint.

**Comment by ntoll** [comment]
OK... I've taken a look into this. In terms of implementation, I'll initially follow what the "refresh" button does with its spinner. We can refine from there. :+1: Hopefully I'll have something to show by end of my afternoon.
