### ISSUE TITLE
Status messages displayed to the user

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#290]
## Description

This issue gives us a place to track the status messages we currently display to the user. Here we should decide which messages are helpful to display and how to word them.

## More info

Once changes in https://github.com/freedomofpress/securedrop-client/tree/issue-279-refreshing are merged, error messages will show up in the center of the status bar, and they will be clipped when necessary in order to remain one-line. Error messages will appear next to activity messages, which normally say something like `Last Refresh: just now`.

Right now the goal is to keep messages short and concise (for tips on useful error messaging, see https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4). @ninvizz any other good resources? 

We may want to eventually use a combination of `...` and hover popups to show the rest of the message. Also some languages with longer words will be clipped more often and that's not a good user experience.

## Current error messages

When a user cannot be authenticated:
> There was a problem signing in.
> Please verify your credentials and try again.

When a user needs to login to perform the specified action:
> You must sign in to perform this action.

When a timeout occurs while waiting for a response from the server (e.g. during refresh, login):
> The connection to the SecureDrop server timed out.
> Please try again.

When an API sync for a star/unstar update fails to successfully update the source:
> Failed to apply change.

When there is a failure to delete source:
> Failed to delete source at server

When delete operation times out:
> The connection to SecureDrop timed out. Please try again.

## Current activity messages

Default message that will only disappear when a new activity message temporarily replaces it:

> Last refresh: [time]

When a user clicks download:

> Downloading [filename]

When attempt to decrypt a file fails during file download action:

> Failed to decrypt file
> please try again or talk to your administrator.

When connection times out during a file download:

> The connection to the SecureDrop server timed out. 
> Please try again.

When the file is downloaded:

> Finished downloading [filename]

When file cannot be downloaded for some reason:

> The file download failed. Please try again.

---
Some of these messages clearly need to be moved to the error status section. This is just the current state.

**Comment by ninavizz** [comment]
Writing the error messages is going to have to be a team effort. No single one of us could likely write them to be clear or brief enough. 

Lots of resources on the [UX Wiki's Resources section](https://github.com/freedomofpress/securedrop-ux/wiki#general.

Google Material's writing guide (at the aforelinked page), imho is the best—but I highly recommend folks use some learning time to read through the USDS Plain Language guide (left nav needed to advance through pages—shitty UI). 

SO EXCITED TO SEE THE PROGRESS!

@creviera could you maybe create in the FPF GDocs, a spreadsheet for keeping all the above stuff? What the message is, what the action is that prompted it, where the message goes, seem like a good 4 columns to begin with. w00t!

**Comment by ninavizz** [comment]
Also: Active voice is VERY important for usability, and something I often see absent in messaging.
https://www.plainlanguage.gov/guidelines/conversational/use-active-voice/

**Comment by ninavizz** [comment]
Tentative mini-proto demonstrating messages: https://invis.io/W3RAEGUSUZP#/355297162_Reply_-_Error___Closed

**Comment by ninavizz** [comment]
Spreadsheet with messaging content: https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbYQxpO2-U/edit?usp=sharing

Updated prototype showing Activity Log, here: https://invis.io/XDRB535NR9Z#/355404383_Reply_-_Composing

Will update shortly, with a Beta stand-in for the Activity log (current IxD depends upon it).

**Comment by eloquence** [comment]
As mentioned, we are now using https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbYQxpO2-U/edit#gid=0 as a message inventory (needs to be updated, again); we're also tracking responsiveness of the app in https://github.com/freedomofpress/securedrop-ux/issues/110 which we'll be discussing in more detail next week. Closing this issue as it is a bit outdated at this point.
