### ISSUE TITLE
avoid passing around sdc_home and instead pass a session maker

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#296]
We have these lines in our code 3 times

```python
engine = make_engine(sdc_home)
Session = sessionmaker(bind=engine)
session = Session()
```

For simplicity, we may want to pass the `Session` around instead. This will also reduce the need to mock as heavily in tests.

**Comment by redshiftzero** [comment]
This is done in https://github.com/freedomofpress/securedrop-client/compare/refactor-session for very closely related ticket #382. Closing this ticket in favor of #382 so that we can track progress in one place
