### ISSUE TITLE
Apply gradient that spans the footprint behind the Source List, Conversation Pane, and Reply pane

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#299]
@creviera The gradient that spans the footprint behind the _Source List_, the _Conversation Pane_, and the _Reply pane_, is below. It may be a tad light, ping me when ya get it in. 

```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1224 792" style="enable-background:new 0 0 1224 792;" xml:space="preserve">
<style type="text/css">
	.st0{fill:url(#SVGID_1_);}
</style>
<radialGradient id="SVGID_1_" cx="609.095" cy="326.8184" r="279.7393" gradientTransform="matrix(2.065 0 0 1.9595 -644.4514 -243.4455)" gradientUnits="userSpaceOnUse">
	<stop  offset="0" style="stop-color:#F2F8F4"/>
	<stop  offset="0.4802" style="stop-color:#F2F3FA"/>
	<stop  offset="1" style="stop-color:#F8FCFF"/>
</radialGradient>
<rect x="1.9" y="0.5" class="st0" width="1222.9" height="792.9"/>
</svg>
```

_Originally posted by @ninavizz in https://github.com/freedomofpress/securedrop-client/issues/280#issuecomment-476053365_

**Comment by creviera** [comment]
Zeplin link for "No Content": https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cfe9244f033df15f09e72ec

**Comment by creviera** [comment]
@ninavizz Is this still the correct graient? https://github.com/freedomofpress/securedrop-client/issues/280#issuecomment-476053365. I can't find this gradient in the inventory list or in zeplin. Do you have a link?

**Comment by creviera** [comment]
to help, i can show you what the gradient provided in your comment looks like (granted this is not applied behind the sourcelist yet, which will require a code refactor to do):

![gradient-hard-to-see](https://user-images.githubusercontent.com/4522213/61913506-379f0d80-aef2-11e9-81b1-f1fbbe465752.png)

to make it easier to see that this is a radial gradient, i modified the colors (FOR DEMONSTRATION ONLY):

![radial-gradient](https://user-images.githubusercontent.com/4522213/61913557-65845200-aef2-11e9-9b2f-bd412491c723.png)

**Comment by ninavizz** [comment]
Yeeeeeahhh, no. As always, big affection & appreciation for your attention to detail! Lemme check...

**Comment by ninavizz** [comment]
Okee doke, now I remember why I created the gradient like that: because it has to span the full footprint beneath the Conversation Pane, and the Source List, and only the left 2/3 and the top 5/6th(ish) of that, are supposed to be regularly visible to users. Just like we discussed when we strategized about this over lunch at Laurelhurst.

For a variety of reasons, I feel it's too much work to "incrementally" do the gradient. Which is why I've never liked this issue existing as a thing to tackle, before the typography, re-factoring of the Source List, or re-factoring of the Reply box. It's basically the last cherry-on-the-sundae touch in the UI, for us to worry about.

Happy to discuss in further detail, in Monday's meeting.

**Comment by creviera** [comment]
This can be closed once the following issues are merged:
* https://github.com/freedomofpress/securedrop-client/pull/505
* https://github.com/freedomofpress/securedrop-client/pull/502

**Comment by eloquence** [comment]
Thank you, @creviera! Let's aim to merge #505, #502, and #510 in this sprint, but bump the master issue off the sprint for now. Thanks to your hard work, we're already significantly exceeding the UI commitments for the sprint, and I think it's fine to defer the final work required to match the spec a bit longer, so we can use the remainder of the time in this sprint to focus on getting closer to resolving #391.

**Comment by eloquence** [comment]
As noted above, was split into follow-up issues. Closing.
