### ISSUE TITLE
Add "Delete" button to Selected Source item in Source List

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#300]
Here you can see that the delete icon covers the attachment icon when source is selected: https://zpl.io/V4OMBzy

**Comment by ninavizz** [comment]
It occurred to me last night, that the scrollbar in today's `Source List` is kind of a blocker to implementing this; so #474 feels like a prereq. Thoughts?

**Comment by eloquence** [comment]
@ninavizz Could you elaborate? I don't see why the current scrollbar is a blocker for adding the "X" when a source is selected.

**Comment by ninavizz** [comment]
@eloquence My concern, is that in the original design there's more negative-space around the "X" and as such, it pops more. TL;DR, it's more elegant w/o the bulk/clunk of the QT widget scrollbar. 

Can I blame the Sudafed and the Robitussin some more, for influencing my designer-drama hyperbole? Agreed, it's not a "blocker," just not ideal. See study, below.

That said: Some `UI Polish` stuff short of doing the custom scrollbar, I do feel would help a lot. The below is literally just plopping the "X-delete" in there w/o any UI polish. Thoughts?

![X-Delete Study](https://user-images.githubusercontent.com/8262612/84556452-b56d3280-acd7-11ea-89ae-ade63e296b5b.png)

**Comment by eloquence** [comment]
We're currently re-evaluating this design, as the placement of the source list delete action in this design covers the date, which would be problematic if that's the only place where the date is visible (we're separately considering showing more menu actions, including a read/unread toggle, in the top right area, instead of the date that's currently shown there).

Marking this as "blocked" until we have final agreement on the design direction here.

**Comment by eloquence** [comment]
(Still no agreement that we want to add this feature, removing from near-term backlog for now.)

**Comment by ninavizz** [comment]
I am totally ok putting this ticket on indefinite hold, pending more learnings from users around deletion in general, and deletion in the Client. We should be learning a good deal more with another project, and once we get our Client findings together I feel that should inform how to proceed with this issue.

**Comment by eloquence** [comment]
For sure. I'll close it for now, if/when we revisit this issue, it'll probably take a different form then what was originally specified here.
