### ISSUE TITLE
Refresh and Error status can be cut off

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#301]
## Description

Refresh status is cut off when window is not wide enough (this might be related to the introduction of error_status and the width of my client which was set to 960 pixels wide)

https://user-images.githubusercontent.com/15223328/55972972-9649bf80-5c52-11e9-8278-bf12a453b341.png

Error status can also be cut offf when window is not wide enough. We do have minimum widget sizes for the sourcelist and conversation view which will prevent us from making the window _too_ small. These sizes will be added in PRs for each section.

Other things we can do are:
* make error status messages actual popup windows that closes when a message goes away. Right now it is a statusbar that has a reserved section of the main status bar. 
* make the error section smaller
* add some logic that will change the size of the acitivity status bar widget when the error status bar widget hides, so that it can take up more space when errors go away

**Comment by eloquence** [comment]
This no longer occurs with current "Last Refresh" behavior; we are tracking a recently observed similar example in #932. Closing this historical issue.
