### ISSUE TITLE
Segfault when runing without sdc-client home dir option

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#304]
## Description

Segfault happens when you run the client with no `sdc-home` option.

#### Logs (not much to go on)
```
./run.sh: line 44: 21070 Segmentation fault      exec python -m securedrop_client --sdc-home "$SDC_HOME" --no-proxy $@
```
## More info

This looks like the same upstream bug that we came up with a workaround for. This might have been re-introduced when moving CSS from instance to class variables. See https://github.com/freedomofpress/securedrop-client/issues/273 for more info.

**Comment by redshiftzero** [comment]
I can't reproduce this on latest master (8f69f01955840f571dc80d749cfae5f64923e631), my STR are just to execute `./run.sh` - do I need to login or take another action?

**Comment by creviera** [comment]
Ah, sorry. Forgot the STR...

# STR

1. `./run.sh` 
2. select a source

Do the same with the `sdc-home` option (this is how I normally test as I develop but will start testing both situations to catch bugs like this sooner) and see it *not* segfault

**Comment by redshiftzero** [comment]
ahh gotcha, I can indeed reproduce this on `master` with Qt 5.12.1
