### ISSUE TITLE
Refresh should be in "active" state while messages are being downloaded

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#309]
Currently the refresh icon stops being in active state (![image](https://user-images.githubusercontent.com/8262612/54233325-f6213f00-44c9-11e9-82fb-9506d038cec2.png)) as soon as the metadata for sources has been updated. 

Regardless of whether we keep around placeholders for un-downloaded messages or not, this has the potential to be confusing:

- If we keep the placeholders around in some form, the user may infer that they need to click Refresh again to fetch those messages;
- If we get rid of the placeholders, they may be confused that messages still appear after a refresh operation is "complete", which may cause them to not trust the "Refresh" function.

The state of the refresh icon should instead be dependent on the completion of all server actions directly associated with it, i.e. not just metadata but also message downloads.

This work is blocked on the completion of the queue (#224). Note also that the network activity indicator (#291) would provide an additional mechanism to tell the user that the client is busy, but they serve slightly different purposes and should be able to co-exist happily.

# User Story

As a journalist, I want to know when the client is fetching stuff for me, so that I'm not confused as to whether I need to do something to make it go.

**Comment by eloquence** [comment]
I'm intentionally not adding this to the beta milestone yet, but we may want to prioritize it based on additional validation with users or our own internal testing.

**Comment by ninavizz** [comment]
Spreadsheet to indicate how refresh icon and messaging should function w/in that widget: https://docs.google.com/spreadsheets/d/1jXalueqcT8RWWG7osGLFO8dsG6_EB9NdbfJfE_NEmqw/edit?usp=sharing

**Comment by creviera** [comment]
should we close this since it's a bit outdated with the refresh icon removal (https://github.com/freedomofpress/securedrop-client/issues/687) and we have this issue: https://github.com/freedomofpress/securedrop-client/issues/468

**Comment by eloquence** [comment]
Yes, good flag - closing
