### ISSUE TITLE
Style login dialog

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#311]
## Description

(Moved styling tasks out of https://github.com/freedomofpress/securedrop-client/issues/286)

**Note:** The login window has been updated to look more like the image include in this ticket instead of the image in #264 

* Placeholder Qt active state for "Sign in" button, do not render main window until sign in fully complete to minimize lag
* Minimize text consistent with the above design

**Comment by creviera** [comment]
Don't want to lose track of this comment, so linking to it here, where we'll likely address it:

https://github.com/freedomofpress/securedrop-client/issues/286#issuecomment-477406305

**Comment by creviera** [comment]
For the first iteration, I think we should style the form to look like the prototype below, but without the following:
* "Need help" link
* "Securedrop Desktop <version>" name
* Username dropdown
* Password eye icon

It **should** include the following:
* positioning and alignment of text and widgets
* wording
* white text
* background image

#### Current login dialog
![current-login](https://user-images.githubusercontent.com/4522213/60128608-e4496c00-9747-11e9-9c30-7ebde2323485.png)


#### Prototype
![first-iteration-login](https://user-images.githubusercontent.com/4522213/60128513-b6642780-9747-11e9-8fce-9ef340f93049.png)

**Comment by ninavizz** [comment]
There is no image on this ticket... perhaps add to clarify? :D

**Comment by creviera** [comment]
To see more details about this dialog, including contextual error messaging, which isn't in the scope of this ticket: https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5ca2a8fdb48fa83d9e5c7f48

**Comment by ninavizz** [comment]
Hooray! Yeah, I'm seeing as a great ordering of steps to tackle that implementation to 100%, picking-up from your starting point:
### Batch 1
- Add bg image
- Kill _Sign In_ `H1`
- Kill `body` content below `H1`
- Update label & button wording
- Position/alignment of fields, labels, buttons
- Add correct text styling to field labels
- Tighten padding between fields & labels
### Batch 2
- Update secondary action to be a (one-off styled) hyperlink and not a button
- Add/update to correct styling for _Sign In_ button 
- Add styling for _Use Offline_ hyperlink
- Add Appname & Version Number feature
  - Add text styling for above
- Update styling for text fields 
   - Add states: live, disabled, focus, hover
   - General: never rounded corners, often inner-shadow, static bg color, white color upon click-into
- Add styling for user entered text in text fields
### Batch 3
- Add show/hide functionality in Passphrase field
- Add "Need Help" link & content
### Batch 4
- Add dropdown username functionality
### Batch 5
- Create spec'd unique signin widget to sign-in from offline mode, so the above window only shows when the user opens the client app. 😄
