### ISSUE TITLE
Add conversations view

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#32]
When a user clicks on the source in the sidebar, they should see a conversation view as in @ninavizz's mockups, with the submissions and replies interleaved. There may be replies from multiple journalists. 

Unfortunately, SecureDrop server does not currently preserve timestamps on submissions: when a new submission comes in, we update the timestamp on all submissions (we also `touch` all those files on disk). This is to minimize information stored about sources: we only keep the time of their latest submission.

Fortunately, we do keep an ordering of submissions and replies, via the `filename` on the submission and reply objects. The integer starting each filename indicates the interaction count for the source. For example, `2-dejected_respondent-msg.gpg` is a message that was second in the conversation for `dejected respondent`.

**Comment by ntoll** [comment]
OK... this is the next "big" thing I'll implement in terms of UI. I'll make use of @ninavizz's dummy data while building the UI. Once "live" data is running through the app, "it should just work" :tm: ;-)

**Comment by redshiftzero** [comment]
opened #40 as the followup here, otherwise the UI parts were completed in #34
