### ISSUE TITLE
User hot keys for interacting with windows

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#321]
## Description

Currently, we don't support hot keys for hiding, showing, or closing windows. But maybe we want to! Here's where we can discuss this.

Note: Qt has default behavior for `QDialog` modals that makes it so that pressing the Esc key hides the window. For the securedrop-client, we decided to no longer allow this for our login dialog: https://github.com/freedomofpress/securedrop-client/pull/320

**Comment by eloquence** [comment]
Cross-linking #274 (keyboard navigation epic).

**Comment by eloquence** [comment]
Closing this issue as a bit stale; [Esc] now works in all dialogs.
