### ISSUE TITLE
Dialogs appearing in unexpected locations

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#322]
## Description

![wild-popup](https://user-images.githubusercontent.com/4522213/56542331-0560c700-6523-11e9-9bdd-7043f8936329.gif)

**Comment by creviera** [comment]
Note: Our other two popups appear in the center of the application window. The other two being the login dialog and the DeleteSourceMessageBox (when you click on the 'x' next to the source instead of using the menu as you see in the gif above).

It would make sense to make this popup appear in the center of the window like the others.

**Comment by heartsucker** [comment]
Also the login popup appears in odd place for me (xmonad, so ymmv).

### STR

1. Login
2. Logout
3. Click signin

It usually ends up in a weird place.

**Comment by creviera** [comment]
@heartsucker can you send a screenshot of what it looks like when it's not center aligned with the main window? Is it always in the same place? Turns out positioning dialogs is a pain!

**Comment by heartsucker** [comment]
![Screenshot_2019-04-28_15-12-20](https://user-images.githubusercontent.com/3998464/56864880-29f7eb80-69c8-11e9-8e5e-6c63dbc230b7.png)

This only happens after signing out. The initial sign in is always correct.

**Comment by creviera** [comment]
@heartsucker thanks, ill look into it -- xmonad looks pretty sweet

**Comment by eloquence** [comment]
For the 7/10-7/24, focus is exclusively on the deletion dialog triggered via the "..." button in the top right corner.
