### ISSUE TITLE
both on complete and timeout signals can fire for QThreads

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#323]
In `logic.py::Controller`, we use `call_api` to start `QThread`s for each API call. We attach a `timeout` callback to a `QTimer` that fires if the timer times out, and we attach an `callback` for completion to the thread itself.

Cleanup for the threads is done in `clean_thread`, `completed_api_call`, and `timeout_cleanup`. Between all these, there is a race condition between the timer timing out and the other signals from being disconnected. This means both callbacks may be hit with signals.

**Comment by redshiftzero** [comment]
We have an attribute, `i_timed_out` (we can rename this heh), that tracks whether or not a given API call has timed out. Not emitting the `call_finished` signal [here](https://github.com/freedomofpress/securedrop-client/blob/b7657e96cb867d19af303e4a38a703010ee3fbce/securedrop_client/logic.py#L82) should address this issue (as the comment above the if block suggests), no?

**Comment by heartsucker** [comment]
Setting / reading `i_timed_out` isn't atomic. We'd still need a `QMutex` to ensure these operations are thread safe.

**Comment by heartsucker** [comment]
I was asked to clarify:

This is the check that decide whether or nor to emit the completed signal:

```python
        if self.i_timed_out is False:
            self.call_finished.emit()
```

and this is the thread that sets `i_timed_out` and then emits the timeout signal:

```python
    def timeout_cleanup(self, thread_id, user_callback):
        if thread_id in self.api_threads:
            runner = self.api_threads[thread_id]['runner']
            runner.i_timed_out = True
```

The former conditionally acts assuming the latter hasn't timed out, and the latter assumes a timeout occurred. The `i_timed_out` flag actually needs to be ternary:

- `None` for neither completion nor timeout
- `True` for completion but no timeout
- `False` for timed out but no completion

The check/set needs to be atomic, and this needs to be wrapped by a mutex. So

```python
def __init__(...):
    ...
    self.i_timed_out = None
    self.lock = QMutex()

def on_timeout(...):
    ...
    with self.lock.lock(): # or whatever the call is
        if self.i_timed_out is None:
            self.i_timed_out = True
    if self.i_timed_out:
        do_stuff()
```
