### ISSUE TITLE
Failure to stop event loop on QThread after timeout

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#324]
In the `Controller`, we do not stop `QThread`s that have timed out. In `call_api`, we create a `QTimer` and a `QThread`. If the thread times out, the `timeout` signal is emitted which runs the callback that was passed in to `call_api` and attached to the signal.

However, we do not call `QThread.exit(1)` to stop the thread's event loop. The thread may still complete.

This is related to https://github.com/freedomofpress/securedrop-client/issues/323 in that it contributes to the chances that both callbacks for an API call will be executed.

**Comment by redshiftzero** [comment]
See my comment here: https://github.com/freedomofpress/securedrop-client/issues/323
