### ISSUE TITLE
thread un-safety in QThread handling in Controller

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#325]
In `logic.py::Controller`, we use `call_api` to start `QThread`s for each API call. Cleanup for the threads is done in `clean_thread`, `completed_api_call`, and `timeout_cleanup`. There is a race condition that means that `KeyError`s may happen because of concurrent deletion of threads from the `dict` that stores their state. This is related to https://github.com/freedomofpress/securedrop-client/issues/323

**Comment by redshiftzero** [comment]
Looks like `del(self.api_threads[thread_id])` only occurs in `clean_thread` - can you explain further or provide a test demonstrating how the `KeyError` can occur? It seems that this bug should only occur when #323 is in place, i.e. resolving #323 should resolves this.

**Comment by heartsucker** [comment]
`clean_thread` is called by both `completed_api_call` and `timeout_cleanup`, and as per #323 this can double fire. We could still guard against this by checking for a `KeyError` regardless to prevent future race conditions from causing errors.
