### ISSUE TITLE
Timeouts are too short for API calls

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#326]
In `logic.py::Controller.call_api`, we use a `QTimer` set to 20 seconds to timeout threads for API calls. 20 seconds is not long enough for large downloads over Tor.

This short timeout will cause the `timeout` callback to run but because of #323 and #324, the thread may still finish and then call the completion callback. This may cause the user to start multiple concurrent downloads of the same object.

**Comment by redshiftzero** [comment]
to handle with https://github.com/freedomofpress/securedrop-sdk/issues/79

**Comment by heartsucker** [comment]
#362 partially addressed this. What we should do is use some simple calculation to come up with a minimum bitrate we want for the download. The default is 60 minutes, but we probably don't want that much time for a 6kb message. Or we want longer for a 500mb file.

**Comment by creviera** [comment]
Since this issue contains details about bugs and threads that are no longer relevant to the adjustable timeout problem, I'm closing this issue in favor of a new issue: https://github.com/freedomofpress/securedrop-client/issues/430 that captures the minimum bitrate idea.
