### ISSUE TITLE
Iterate on placement of login UI 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#33]
In #29 we're adding login to the client application. Comparing to the latest wireframes, we have two login panels:

* One on application start, which has a button for whether the user wants to work online or offline and a place to indicate their username
* One when the user is already using the application, and wants to connect to the server. This is the login that we have implemented in #29, and in the wireframes it appears in a popup window. We should iterate on the design such that we are closer to the wireframe. 

Let's wait until EOD Thursday October 11th until picking this ticket up such that we have another round of user testing done and thus have high confidence on the best placement of the login UI.

**Comment by eloquence** [comment]
Current login wireframe: https://projects.invisionapp.com/share/72OJI1R8DTF#/screens/325169631

**Comment by ntoll** [comment]
Hi @eloquence, just catching up with this...

Ummm... why the dropdown for the username. That's totally unlike every other login box I've ever seen. It's hard to know for certain what's expected to be in the dropdown (I assume previously seen users?). Clicking on the wireframe doesn't give me any hints. Why don't we think users will remember their username. Also, providing a list of known usernames is sort-of leaking potentially useful information for would-be attackers IYSWIM. Quite understand (and quite likely) if I'm barking up the wrong tree here -- my job is to definitely implement what you specify... I'm just curious.

Also, just wondering how the Login is supposed to know it's at the "Daily Bugle"..? I'm not sure we have that information available.

Finally (sorry -- I just want to make sure I've got all the information I need), is this what the login "design" is supposed to look like... if so, where can I find things like the background image and colour hex for the CSS.

Sorry for all the Q's... just mentioning @ninavizz 'cos I know she's probably got all the answers I need.

Thanks! :-)

**Comment by eloquence** [comment]
> Ummm... why the dropdown for the username. That's totally unlike every other login box I've ever seen. 

The idea here, I believe, was to use an autocompleting [combobox](https://en.wikipedia.org/wiki/Combo_box), that is, a dropdown that also allows text entry. And indeed, it would remember previously (successfully) used users, simply for the purpose of saving time typing.

I consider this a minor detail and of no relevance for the alpha, so feel free to stick to a simple input for now. Regarding security considerations, I think the risk here is quite low (an attacker would have to already have achieved physical compromise of workstation and associated credentials for full-disk encryption;  a username doesn't get them much farther), but flagging this discussion to @emkll as well.

> Also, just wondering how the Login is supposed to know it's at the "Daily Bugle"..? I'm not sure we have that information available.

We do not; see https://github.com/freedomofpress/securedrop/issues/1575 . So ignore that for now.

> Finally (sorry -- I just want to make sure I've got all the information I need), is this what the login "design" is supposed to look like... if so, where can I find things like the background image and colour hex for the CSS.

It's not final by any means, hence monochrome. But Nina may be able to provide you these assets if we have time to do a little bit of polish for the alpha.
