### ISSUE TITLE
Show placeholder content in conversation view when client is empty or no source is selected

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#340]
## Description

Instead of displaying a blank conversation view, display a placeholder that @ninavizz will provide for the cases where we don't know the user's last-seen source, a user is offline, and there is an empty source list. There will likely be a separate placeholder for empty source list.

#### Application start: offline mode
   1. application starts
   2. user logs in in offline mode, sees placeholder that @ninavizz will provide

#### Application start: A's first session or A's last-seen source was deleted by another user
   1. application starts
   2. user logs in as A, sees placeholder that @ninavizz will provide

#### There are no sources in the list
    1. application starts without sources in the list or user deletes the last source in the list
    2. user sees placeholder that @ninavizz will provide

**Comment by eloquence** [comment]
The reviewed and approved placeholder designs can be found here:
https://github.com/freedomofpress/securedrop-ux/issues/54#issuecomment-500510184
