### ISSUE TITLE
Reply button inside text box in offline mode

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#349]
## Description

Show the Reply send button inside the reply box as you see in this Screen:
https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5ca3fb289972713e0053fa66 ([static public copy](https://scene.zeplin.io/project/5c807ea562f734bd2756b243/screen/5ca3fb289972713e0053fa66))

And disable it in offline mode as you see here:
https://projects.invisionapp.com/share/5ZQY2ATPA3S#/screens/351556425

**Comment by eloquence** [comment]
(Updated Zeplin links.) This is done for the logged in view but not yet in offline view. Retitled and added to beta milestone but low priority, hence stretch.

**Comment by eloquence** [comment]
Per discussion w/ @ninavizz we'll forego the airplane icon in offline mode.
