### ISSUE TITLE
SIGINT does not terminate modals

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#355]
Related to #210. This isn't a problem when the app is started via `python -m securedrop_client`, but this odd behavior indicates that we might be initializing the signal handlers in a bad way.

### STR

1. Start client with `.run.sh`
1. Attempt to login in once using bad credentials
1. Confirm login failed by seeing red warning text
1. `^C` in the terminal

### Expected

The app quits and the modal disappears

### Actual

The app quits, but the modal does **not** disappear

**Comment by eloquence** [comment]
This appears to no longer be an issue with the current login flow. The app does terminate after ^C, regardless of login state (though it takes several seconds to do so).
