### ISSUE TITLE
Add spinner for replies in process of being sent

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#359]
As indicated in [this design](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d5b183a152c905223e5fab0) ([publicly viewable static link](https://scene.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d5b183a152c905223e5fab0)), when a reply is in the process of being sent, and until a signal is received that it was successfully sent, we want to show a blue spinner vertically aligned with the comment, to show that is in the process of being sent.  

This progress indicator disappears as soon as the reply has been sent.

This is another indicator to the user that this reply has not been sent, along with the greyed out state (#350).

**Comment by creviera** [comment]
The screen in this spec is not available anymore. @ninavizz do you know which screen this should point to now?

**Comment by ninavizz** [comment]
Blue spinny Erik references above, is in [these screens](https://app.zeplin.io/project/5c807ea562f734bd2756b243/dashboard?seid=5cbea90def626b1fb8bd27a9)... « (and that link is for the section, not a specific screen, so shd always remain live)

**Comment by ninavizz** [comment]
...but since u asked, [blue spinny screen](https://zpl.io/VkXN9xW). :)

**Comment by redshiftzero** [comment]
hey @ninavizz can you drop a public link to the spinner screen and a link to the asset? this one is a good hackathon issue i think

**Comment by eloquence** [comment]
Updated design links in top-level issue. Note that we may want to kick off the spinner the moment a reply is added to the queue, per https://github.com/freedomofpress/securedrop-ux/issues/84#issuecomment-566318853

**Comment by eloquence** [comment]
From 2022-08-22 review with @nathandyer @cfm @gonzalo-bulnes @eloquence:
- Closing for now, we'll revisit in context of broader UX reviews whether a spinner or other progress indicator makes sense here (in addition to the already existing logic for changing the styling of the reply itself).
