### ISSUE TITLE
can no longer login in qubes after timeouts merge / securedrop-sdk 0.0.9

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#375]
# Description

Login to external server no longer works on latest `master` (06df84c) after merge of #362

# STR 

1. Set up the dev env in Qubes on latest `master`
2. Run the client without passing `--no-proxy`

# Expected behavior

I can log in to my staging server.

# Actual behavior

`AuthError`

# Comments

I have not debugged this yet, I inferred that the above was causing the problems by:

1. Reverting back to `securedrop-sdk==0.0.8`
2. Reverting back to bad39fa80a82774d36ee7f5c48fe974efba9b1ce

It's unclear yet if the fix involves this repo or the corresponding change made in the SDK: https://github.com/freedomofpress/securedrop-sdk/pull/80

I discovered this during test of my fix to #363 (will put a draft PR until the underlying issues here are resolved), which is another Qubes only issue. I'm going to file a PR to update our merge policies so that we are testing and catching these issues in Qubes prior to merge.

**Comment by creviera** [comment]
This is a good reminder that we should be testing client changes in Qubes. Will remember to add that to PR test plans until it becomes the norm.

I got my qubes machine running and can help debug the timeouts issue.

**Comment by kushaldas** [comment]
I can login to my environment using Qubes Proxy + securedrop sdk 0.0.9 on the latest master of the client repository.

**Comment by redshiftzero** [comment]
OK thanks @kushaldas - this must have been a local error... will debug, closing this for now
