### ISSUE TITLE
Timeout / No Auth

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#379]
>There is no signal for for ApiInacessibleError or RequestTimeoutError, and there needs to be as these being raised requires action from the user. As it stands now, either of these errors will either abort the thread (with no way to restart) or crash the app. I haven't tested.

~heartsucker

---
see https://github.com/freedomofpress/securedrop-client/pull/374 for more info

**Comment by redshiftzero** [comment]
Proposal: when `ApiInaccessibleError` occurs in the queue, we should emit a signal that `on_action_requiring_login` listens for, which will cause this UI action:

<img width="355" alt="Screen Shot 2019-06-05 at 12 16 59 PM" src="https://user-images.githubusercontent.com/7832803/58983504-d8433d80-878b-11e9-94b6-cc20aa0213d0.png">

**Comment by creviera** [comment]
Good idea. We also should make sure to stop users from performing actions ahead of time when in offline mode.

**Comment by redshiftzero** [comment]
OK after more consideration I think we want to do the following:

1. `ApiInaccessibleError`: this means that either the user is logged out OR their token expired. We should pause queue execution and should probably open a customized version of the Login UI indicating that they have been logged out and should login again (or continue in offline mode).
2. `RequestTimeoutError`: if we've implemented #384 and we STILL see this, it means that network connectivity is lost to the server. We should pause queue execution and open a window indicating: “We’ve lost contact with the server: Go to offline mode (this is a button) or Try again (this is a button)”

**Comment by eloquence** [comment]
> ApiInaccessibleError: this means that either the user is logged out OR their token expired. We should pause queue execution and should probably open a customized version of the Login UI indicating that they have been logged out and should login again (or continue in offline mode).

Given the 8 hour expiry, throwing user back to login dialog makes sense to me, would be nice if we had a way to pass along a "reason" message to the UI, even if placement is temporary for now.

> RequestTimeoutError: if we've implemented #384 and we STILL see this, it means that network connectivity is lost to the server. We should pause queue execution and open a window indicating: “We’ve lost contact with the server: Go to offline mode (this is a button) or Try again (this is a button)”

This is spec'd out in #391 (it currently doesn't have an "offline mode" action, but that's a good place to discuss that).

**Comment by creviera** [comment]
Doing a little cleanup...

I'm closing this issue because it's outdated now, and I made sure we have more recent issues that make it easier to see work left to do (see below) and nothing gets lost here.

> 1. `ApiInaccessibleError`: this means that either the user is logged out OR their token expired. We should pause queue execution and should probably open a customized version of the Login UI indicating that they have been logged out and should login again (or continue in offline mode).

We are now pausing the queue on `ApiInaccessibleError`, and opening a customized version of the Login dialog is being tracked [here](https://github.com/freedomofpress/securedrop-client/issues/517).

> 2. `RequestTimeoutError`: if we've implemented #384 and we STILL see this, it means that network connectivity is lost to the server. We should pause queue execution and open a window indicating: “We’ve lost contact with the server: Go to offline mode (this is a button) or Try again (this is a button)”

We've implemented:
* https://github.com/freedomofpress/securedrop-client/issues/384
* https://github.com/freedomofpress/securedrop-client/pull/531
* https://github.com/freedomofpress/securedrop-client/pull/530

And as eloquence mentioned, this is being tracked in #391.
