### ISSUE TITLE
Add functional tests

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#381]
While we have unit tests, for maintainability it would be useful to additionally have functional tests that verify the behavior of the application from the perspective of the user. There's a [pytest-qt plugin](https://pytest-qt.readthedocs.io/en/latest/tutorial.html) which enables one to test in this manner by simulating the user's mouse clicks/keyboard input.

**Comment by eloquence** [comment]
We discussed today that for the 2/5-2/19 sprint, it would be useful to do an exploratory spike on this -- meaning, evaluating e.g. the pytest-qt plugin to see if we can automate some of the scenarios covered in the [client test plan](https://github.com/freedomofpress/securedrop-client/wiki/Test-plan) and and the [beta acceptance tests](https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests).

Potentially a good issue for @ntoll, but any release blockers he can help with should take priority.

**Comment by ntoll** [comment]
:+1:
