### ISSUE TITLE
No longer pass session_maker to widgets

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#382]
Follow-up for https://github.com/freedomofpress/securedrop-client/pull/374, which introduces passing around sqlalchemy's scoped_session to GUI widgets in order to access up-to-date database objects.

See if we can instead use the Controller to remove this sqlalchemy dependecy in the GUI.

**Comment by heartsucker** [comment]
Are you suggesting passing a full reference to the `Controller` to each widget?

**Comment by creviera** [comment]
I think we need to stop passing around session unless we really need to. See my latest commit to resolve this issue: https://github.com/freedomofpress/securedrop-client/commit/e21084ea3fbbe14b86ecbc3a653f19171f1c8cca

**Comment by creviera** [comment]
This has been fixed.
