### ISSUE TITLE
Enable configurable number of retries for each API job

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#384]
We should have the queue retry each API job N times for robustness (e.g. when Tor is particularly flaky). See my comment here: https://github.com/freedomofpress/securedrop-client/pull/374#discussion_r286635469

**Comment by eloquence** [comment]
Recap of rationale based on chat (please jump in if I'm misunderstanding): While we may want to effectively retry operations indefinitely even without explicit user action, there are at least two reasons why it makes sense to limit retries:

1. We do want to keep track of retries so we can indicate that there are network problems to the user after a certain number of failures.

2. If a queue item fails repeatedly, we'll want to use another, independent operation to check network conditions (e.g., refresh), in case it's just this particular queue operation that is being flaky in unexpected ways.

**Comment by redshiftzero** [comment]
status of this ticket: I have a wip diff in `retry-jobs-if-failed` that needs tests adding and a rebase after #404 is merged
