### ISSUE TITLE
Sync icon should be disabled during active sync

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#388]
Double clicks on the sync icon seem to be triggering double syncs. The first click on the sync icon should disable the sync icon, preventing subsequent clicks from causing syncs (@creviera flagged to me that this is complicated by the fact that the disabled state is now the offline icon). Then the existing logic in `RefreshButton._on_refresh_complete` should update the icon back to active when the sync has completed.

**Comment by eloquence** [comment]
We discussed this briefly today. For the first iteration, we can keep the icon state as-is -- if the user clicks repeatedly, it'll still only add one job. We can revisit the use of a spinner or disabled state in future iterations.
