### ISSUE TITLE
Download and decrypt messages

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#40]
In #34 we have dummy messages in the conversation view for now. We should add logic to fetch messages (both replies from journalists and messages from sources), decrypt them, and store the decrypted messages on disk. 

Note: this has a dependency on the decryption logic in securedrop-workstation repo (this decryption occurs in another VM), so needs to be done in Qubes once we have the scaffolding in place to test, i.e. #161 is implemented. Then we'll need to provide mocks / dummy data for people developing in non-Qubes OSes

**Comment by redshiftzero** [comment]
after a sync occurs, we want to as a background task, always download any new messages, decrypt them, and display them in the conversation view for each source. 

this is in contrast to #19, which will be for downloading _files_ upon request by the user. the reason for the difference is that files may be large (up to 500MB, which can take up to 120 mins over Tor) and we only want to do it on demand.

**Comment by joshuathayer** [comment]
As an update, I'm working on this issue in https://github.com/freedomofpress/securedrop-client/tree/download-messages. Messages are downloading, decrypting, and being stored appropriately, but I'm not sure how we're going to thread messages and replies (and indeed how we're going to order messages themselves).
