### ISSUE TITLE
What can make an API call [Discussion]

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#400]
### Description

I want to open a discussion issue around where we make api calls from in the client.

We reference the SDK API from many places:

```
securedrop_client/logic.py:
securedrop_client/message_sync.py:
securedrop_client/queue.py
securedrop_client/storage.py
securedrop_client/api_jobs/base.py
securedrop_client/api_jobs/downloads.py
```

After we move reply and message sync logic to api jobs, we should consider creating the `sdclientapi.API` instance in `RunnableQueue` to help separate concerns. If a user logs out, the queue can pause and make sure no api calls are made.

**Comment by redshiftzero** [comment]
having one place that mediates network calls / auth state is a good idea... though we do the sync from `logic.py`. we _could_ add a third queue that only does syncing of metadata and move the sync logic from `logic.py` to `queue.py`, then the queue could be that place

**Comment by eloquence** [comment]
This is an old discussion-only issue from 2019 that hasn't received traction since then, so closing for now.
