### ISSUE TITLE
Add update_version.sh to automate version bumps for nightly builds

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#407]
We're working towards nightly builds of the `securedrop-client` and `securedrop-proxy` packages (https://github.com/freedomofpress/securedrop-debian-packaging/issues/8). Each nightly build will have a unique version string.

The nightly build job will automatically make a commit to this repository, updating the version string. To do so, this repository should provide an `update_version.sh` script (the naming convention was established in the SecureDrop repository) that performs this version bump.

Part of this task is building consensus on the version string format and the increment policy during development. One requirement is that each version string must be unique, not just at the day level resolution, as we may want to kick off builds manually in between nightly runs.This could be satisfied, for example, by a format for development releases like `0.1.0-dev-20190607-121822` (with date and time) .

**Comment by redshiftzero** [comment]
status of this ticket: https://github.com/freedomofpress/securedrop-client/pull/422 contains the `update_version.sh` script that is needed here - but I'm leaving this ticket open and unassigned as the remaining task here is determining a good versioning scheme for the nightly builds of securedrop-client

**Comment by redshiftzero** [comment]
Looks like `$latest_release_tag-dev-$timestamp` does what we want here:

* devs will upgrade to latest nightly from latest prod release:

```
$ dpkg --compare-versions 0.0.8-dev-20190607-121822 gt 0.0.8 && echo true
true
```

* devs will upgrade from nightly release to subsequent nightly release:

```
$ dpkg --compare-versions 0.0.8-dev-20190608-000000 gt 0.0.8-dev-20190607-121823 && echo true
```

* if there's a more recent prod tag than the nightly release, devs will upgrade to that:

```
$ dpkg --compare-versions 0.0.8-dev-20190607-121823 lt 0.0.9 && echo true
true
```
