### ISSUE TITLE
Show first name/last name and initials in AuthWidget if set

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#411]
**This task is blocked pending completion of  SDK support (https://github.com/freedomofpress/securedrop-sdk/issues/87).**

As of https://github.com/freedomofpress/securedrop/pull/4425 and https://github.com/freedomofpress/securedrop/pull/4459, we have support for setting a first name and last name for a given Journalist Interface user, and for retrieving this data via the API. First and last name are optional, and are not used for authentication.

The first use case for this data is the "AuthWidget", the area in the top left of the client that shows who's currently logged in, and that provides access to signing out via a caret menu.

If first name and last name are set, the client should use this information *instead* of the username, both for showing the initials, and for the long form display of the username next to the initials.

See the [screens tagged authwidget](https://app.zeplin.io/project/5c807ea562f734bd2756b243/dashboard?tag=authwidget) for the design spec.

# Acceptance Criteria

**Given** that a first name and a last name are configured for my account
**When** I log into the SecureDrop Client
**Then** the first name and the last name should be shown, instead of my username
**And** the initials should be derived from my first and last name, instead of my username.

**Given** that a first name and a last name are _not_ configured for my account
**Then** the behavior should be the same as before (username and username-derived first two letters).

# User Story

As any user, when I am signed into the SecureDrop client, I want to see my first and last name reflected in the UI, because that feels more human and natural than seeing my username or email address.

[See the [user stories spreadsheet](https://docs.google.com/spreadsheets/d/1DQEQp-0e6zN-pCPa0qqY-MGtmpc2SN5mzUsR4nEkpCQ/edit#gid=0) for current prioritization of this functionality.]

**Comment by eloquence** [comment]
(With the sprint load as high as it is, flagging that this is a good candidate to get bumped off the sprint, so let's treat it as lower priority relative to other tasks for now.)

**Comment by creviera** [comment]
for easy ref, this is the auth widget showing first and last name instead of username, with ellipsis, and no hoverover, which is what we're doing for first iteration:

![user-profile](https://user-images.githubusercontent.com/4522213/60377909-d73eae00-99cf-11e9-8620-520b43661fcd.png)

**Comment by creviera** [comment]
also note from nina's prototype:
