### ISSUE TITLE
Star/unstar sources using general queue

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#412]
Similar to #389: we should add `StarSourceJob` and `UnstarSourceJob` objects which are ran in the general queue

**Comment by kushaldas** [comment]
Currently we do a `self.sync_api()` call if the update star is successful. Should we keep doing that? Also, in my mind just having a single `UpdateStarJob` is simpler for this operation. Please let me know what do you think. I am also trying to figure out the tests.

**Comment by redshiftzero** [comment]
For the purposes of this ticket which is just scoped to moving these starring operations to the queue, I think continuing to do the sync after success is best (while #69 also exists regarding changing that behavior, in the interest of keeping changes small, I think doing them as separate tickets is best). 

If your idea is a single `UpdateStarJob` that we pass an arg specifying whether the job should star or unstar, that sounds like a reasonable approach to me.
