### ISSUE TITLE
Update error state for login dialog

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#437]
## Description

This issue is scoped to creating an error banner in the login dialog and moving current error messages into that banner. This issue icludes:
* Adding the error banner as seen in the prototype
* Moving current error messages into the banner

Note: Currently we show error messages until there is a new error message or the user logs in.

#### Prototype error state
![login-dialog-error](https://user-images.githubusercontent.com/4522213/60130947-18735b80-974d-11e9-971e-4b07995f91be.png)
(see https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cbe59fd1048ad4c2ff569f7)

#### Current error state
![login-dialog_invalid-password-length](https://user-images.githubusercontent.com/4522213/60131067-540e2580-974d-11e9-83a2-b35f28f849c2.png)

![login-dialog_invalid-username-password](https://user-images.githubusercontent.com/4522213/60131006-3c36a180-974d-11e9-8574-90ff685b4113.png)
![login-dialog_missing-field-text](https://user-images.githubusercontent.com/4522213/60131007-3ccf3800-974d-11e9-91f2-07b3f13160d1.png)
![login-dialong_invalid-username-length](https://user-images.githubusercontent.com/4522213/60131011-3d67ce80-974d-11e9-8da5-8d01f65fc47c.png)

**Comment by redshiftzero** [comment]
done in #444
