### ISSUE TITLE
Implement Key Text Styles

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#438]
While the client is shaping-up wonderfully well, it remains difficult to measure progress without any final text styling applied to the majority of elements. This ticket is to address that need by touching as many things as possible, moreso than making any one thing perfect. This will also inform later _polish_ tickets with closer-to-final recommendations. 
![image](https://user-images.githubusercontent.com/8262612/60134165-be29c900-9753-11e9-8464-e7c440b596f7.png)

## Priorities
- All text in the client needs to be shown as either Source Sans Pro, or Montserrat 
- Create default text styling that is more on-par with defined style, then current default styles
  - All headers are Montserrat, all body text and most links, SourceSansPro
  - Default color should be `#424348`
     - `#000000` only to be used very sparingly
     - Yes, they're different.
  - General fonts info (about, weights, licenses) [here in the Styleguide(ish)](https://github.com/freedomofpress/securedrop-client/wiki/Styleguide(ish)#typography)
  - Default style for a not-styled bit of text shd be: 
      ```SourceSansPro;
      font-size: 15px;
      color: #303030;
      font-weight: normal;
      font-style: normal;
      font-stretch: normal;
      line-height: 1.53;
      letter-spacing: normal;```
- Primary UI elements, correctly styled according to CSS in [Zeplin Styleguide](https://app.zeplin.io/project/5c807ea562f734bd2756b243/styleguide/textstyles)
- See items in [Components library w/in Zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/styleguide/components?coid=5ca3e2bdb94a0d6c24d84439), for additional layout particulars

**Comment by creviera** [comment]
Once is https://github.com/freedomofpress/securedrop-client/pull/502 merged and https://github.com/freedomofpress/securedrop-client/issues/503 is resolved then this issue can be closed.

**Comment by eloquence** [comment]
Closing out this old issue in favor of the clearly scoped follow-up issues we have regarding styling and spacing (#503, #867, #959).
