### ISSUE TITLE
Source timestamp not updating in UI

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#442]
## Description

The timestamp in SourceWidgets are no longer updating in the UI

**Comment by redshiftzero** [comment]
ah looks like this is also true of the `LastUpdatedDate` in the `SourceProfileShortWidget`, i.e. the "seconds ago" part here won't update:

![Screen Shot 2019-10-17 at 8 24 59 AM (2)](https://user-images.githubusercontent.com/7832803/67008556-bc479500-f0b7-11e9-8839-8d4da5839295.png)

**Comment by creviera** [comment]
I just checked the server-side's `last_updated` values in the `sources` table and see that the value is not being updated when a source sends a new message. This would explain why it's not showing up correctly in the client.

**Comment by eloquence** [comment]
This has other implications e.g. for journalist notifications, so we've agreed to investigate `last_updated` behavior in core at a high priority as part of this sprint.

**Comment by ntoll** [comment]
I've just looked into this and observe the same behaviour mentioned by @creviera. As far as I can tell once the server side issue is fixed, "it should just work" :tm:

**Comment by eloquence** [comment]
> I just checked the server-side's `last_updated` values in the `sources` table and see that the value is not being updated when a source sends a new message. This would explain why it's not showing up correctly in the client. 

I can't reproduce this in `develop`. What I'm doing is:

1) Spin up a development environment with `make dev` on latest `master`
2) Create a new source via the source UI
3) Submit a series of messages/documents as the source, and verify the `last_updated` timestamp in the Docker dev container (including with logout/login cycles)

Here's what I'm seeing as I'm sending new messages/documents:

```
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:01:43.698790
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:01:49.435621
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:01:58.341733
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:02:03.356957
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:02:10.194386
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:02:22.511501
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
ecstatic countrywoman|2020-02-04 20:02:32.010802
sqlite> select journalist_designation,last_updated from sources where journalist_designation='ecstatic countrywoman';
```

The timestamp is _not_ updated when a journalist sends a reply, but I believe that's the expected behavior as it's currently tracking last activity by the source.

**Comment by creviera** [comment]
it sounds like this is a misunderstanding of what "last activity" meant. i was expecting to see the "last activity" timestamp update when new replies were accepted by the server.

**Comment by ntoll** [comment]
It appears not:

![last_update](https://user-images.githubusercontent.com/37602/73918163-efa56e00-48b8-11ea-85bb-7a32ef9cced0.png)

Note how the timestamp on the source widget *is* updated, whereas the timestamp above the conversation isn't working. 

However, if I restart the app, then the correct date is shown above the conversation. The problem appears to be the timestamp update doesn't happen when a new message is received from the server. I'll investigate and create a fix now.
