### ISSUE TITLE
Create login overlay for main window

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#448]
## Description

The login screen used when signing in from offline mode should no longer use the same login screen when signing in for the first time. Instead the login window should look like [this prototype](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cf1b9bd07ad921abfeef78e) as you see here:

![login-from-offline-mode](https://user-images.githubusercontent.com/4522213/60291459-c9a1ff00-98cf-11e9-8f55-2f2e5edb7eca.png)

**Comment by eloquence** [comment]
Please note that this is out of scope for the beta.

**Comment by eloquence** [comment]
I'm going to close this for now; we have no plans to implement this in the foreseeable future as the benefits seem relatively marginal and not justified by the implementation/maintenance effort.
