### ISSUE TITLE
Create overlay widget for truncated usernames

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#456]
## Description

Create a widget to truncate a word and add ellipsis. When the user clicks on the truncated text in this widget there should be an overlay with the full text string. 

See prototype example: https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cd3ca7ef7cf61683e3aa249

For easy ref, this is the auth/user profile widget showing first and last name with ellipsis:

![user-profile](https://user-images.githubusercontent.com/4522213/60377909-d73eae00-99cf-11e9-8620-520b43661fcd.png)

Also note from nina's prototype:

> 18 = The allowable characters for the user's name (including the space between the first and last name). After 18, dot-dot-dot

The overlay should look like:

![overlay](https://user-images.githubusercontent.com/4522213/60378157-3baf3c80-99d3-11e9-8863-f708365ca84c.png)

**Comment by eloquence** [comment]
This seems duplicative of #677, I suggest we close this and more fully specify the truncation and hover behavior in #677.

**Comment by ninavizz** [comment]
Roger that. Closing per forthcoming spec on #677
