### ISSUE TITLE
polish message bubble styling

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#465]
Couple of remaining styling tasks for the message bubbles:

- [ ] apply padding as speced in zeplin within the message bubble
- [ ] apply box-shadow as speced in zeplin: note the `box-shadow` CSS option is not supported by Qt so this will need some research

Font changes and the user badge are tracked separately

**Comment by eloquence** [comment]
@ninavizz Could you link to the preferred Zeplin that shows the intended final message bubble styling?

**Comment by eloquence** [comment]
Stale issue as padding was tweaked e.g. in #496, #1029, #1059. Closing, we can track any further tweaks in new issues.
