### ISSUE TITLE
Spacing between messages not consistent

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#466]
## Description

The spacing between messages and replies in the conversation view should  be a consistent size, but is not, see examples below:

Example 1:
![spacing](https://user-images.githubusercontent.com/4522213/60747488-6ac92f00-9f3a-11e9-8b94-5f71ae4314b5.png)

Example 2:
![spacing-1](https://user-images.githubusercontent.com/4522213/60747489-6ac92f00-9f3a-11e9-8471-a29ef327f409.png)

Example 3:
![spacing-3](https://user-images.githubusercontent.com/4522213/60747490-6b61c580-9f3a-11e9-8898-b431fae98ffb.png)

Example 3 also shows a weird UI issue where the bar is drawn below the message with empty space in between

**Comment by redshiftzero** [comment]
Hmm I can't trigger example 3 - can you provide STR for that case?

**Comment by creviera** [comment]
## STR

1. Create a long message, maybe 50 lines or so.
2. Display message in the conversation view by clicking on the refresh icon.
3. Double-click the window's title bar to resize it (trick is not resizing by dragging the corners), and see the bar separated from the message. If that doesn't work, I will work to create a more precise STR by running more manual tests.

**Comment by creviera** [comment]
Note: I'm only able to repro this on the `message-bubble-color-bar` branch

**Comment by redshiftzero** [comment]
Ahh yeah that repros, thanks! There's this additional space above and below the message box (as it overflows?) that moves the color bar down...
