### ISSUE TITLE
New messages not getting added to existing conversation

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#467]
### STR

1. Send a message as a source A - stay logged in this source account
2. Log into client, view source A. See that the message gets downloaded/decrypted
3. Send a second message as source A
4. Log into client, click refresh and view source A. 

### Expected Behavior

The message appears.

### Actual Behavior 

The message doesn't appear, but viewing the logs it's getting downloaded/decrypted.

**Comment by redshiftzero** [comment]
The diff [here](fix-conv-refresh) resolves this bug but is just a demonstration of the problem as the fix is not the best imho: we should move away from redrawing the conversation view on source update. Right now, the current signals/slots will update all _existing_ message bubbles without needing to redraw the conversation view. The problem is that when a conversation item is added to an _existing_ source and the message bubble wasn't initially created when the conservation view is created, we don't have any slot that will create the corresponding bubble in the source conversation view of interest. I think the best fix here should be to implement that functionality so that we don't need to redraw the entire conversation view anymore.

**Comment by creviera** [comment]
Resolves #463 

^ just tested and confirmed

**Comment by creviera** [comment]
> The problem is that when a conversation item is added to an existing source and the message bubble wasn't initially created when the conservation view is created, we don't have any slot that will create the corresponding bubble in the source conversation view of interest.

Exactly. I think it's a good idea to use your fix in the meantime, but it doesn't makes sense to delete and redraw the entire conversation each time there is a new message. 

To implement this in a more ideal way, I think we would need to stop creating conversation views on the fly whenever a new source is selected and deleting it whenever a source is unselected. Instead we should create the conversation view for each source ahead of time the way we create all the sources in the list ahead of time. When a source is selected we select the corresponding conversation. We could do a lazy load kind of thing too, but I don't think it makes sense to recreate it every time.

**Comment by creviera** [comment]
Just a note that I don't see a UI flicker from your change in the diff.

**Comment by creviera** [comment]
Update: I see the flicker now. Here are my steps to repro:

1. Select a source
2. Send a bunch of messages from a NEW source (5 should be enough)
3. Click refresh and see a flicker of widgets getting created in the conversation view for the new source
