### ISSUE TITLE
Pane Resizing: Conversation Pane

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#472]
This issue is within Epic #471 

---
## Make it small
![image](https://user-images.githubusercontent.com/8262612/60930485-9580f380-a26a-11e9-97d0-198fe28178d5.png)
_Note: In above image, the selected Source in the `SourceList` and the conversation view in the `ConversationPane`, are visually disconnected. That kinda sucks, but I'm not sure of a better way to do it._

### Decreasing Height
Within the `ConversationPane` the `SourceHeader` will remain fixed to the top-edge; the `ReplyPane`, to the bottom-edge. All that will scale is the area messages, files, and the timestamp are in. Neither the `SourceHeader` nor the `ReplyPane` will decrease in height.

The Client should have a total minimum-height of 600px, and a total minimum width of `1255px`. See [this spec](https://zpl.io/bAl96Lq) of the above image. Likewise, please also see [this screen recordin](https://drive.google.com/open?id=1ThxjkcTaUncjqZ8YMBVxC2KXz55uYFIC)g of me resizing & futzing with my Slack client's window, as a general reference for elegant client window scaling & min-size hard-stopping.

### Decreasing Width
- [See Spec ](https://zpl.io/a3jZ64W)for particulars.
   - Values the same as the min-height AND min-width spec, posted above
- Margins and padding all change slightly, in the Source Header and in the Conversation view. 
- Reply pane changes in total width, but margins and padding all remain the same. 

### Increasing Height
Within the `ConversationPane` the `SourceHeader` will remain fixed to the top-edge; the `ReplyPane`, to the bottom-edge. All that will scale is the area messages, files, and the timestamp are in. Neither the `SourceHeader` nor the `ReplyPane` will increase in height.

### Increasing Width
- The `ConversationPane` will scale horizontally in width
  - The `ReplyPane` will scale-up in width 1:1 with the `ConversationPane`, with all margins/padding maintained and text reflowing as the pane's width increases.
  - The `SourceHeader` will also scale-up in width 1:1 with the `ConversationPane`, with the `Star` and `SourceName` both remaining fixed at their left-edge positioning, and the `date/more-menu` coupling will remain fixed to the right side of the pane as it scales-up in size.
  - Messages & files from the Source will...
     - Remain fixed to their left-edge position
     - Increase 1px in width for every 2px that the `ConversationPane` is scaled-out to
     - Files will scale either in more characters allowed in a truncated name, or in the span of the line between the filesize and the end of the name.
  - Journalist messages will...
     - Remain fixed to their right-edge position
     - Increase 1px in width for every 2px that the `ConversationPane` is scaled-out to
  - Timestamps will...
     - Remain fixed to their right-edge position

**Comment by creviera** [comment]
This needs to be updated to support new minimum requirements, see https://github.com/freedomofpress/securedrop-ux/issues/110

**Comment by creviera** [comment]
Closing due to outdated pixel values and new minimum requirements noted here: https://github.com/freedomofpress/securedrop-ux/issues/110
