### ISSUE TITLE
Add support for printing documents

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#477]
Along with export to USB (#21), print is frequently used by journalists to safely exchange documents via SecureDrop (the methods are about equally popular according to our user survey). As a result, basic print support is a must-have requirement for any production deployment, including for the pilot.

# UX Design

In progress, see https://github.com/freedomofpress/securedrop-ux/issues/63

# User Story

As a journalist, I want to be able to print a submitted document, so that I can use the "analog hole" to redact hidden data, or share the document securely.

**Comment by creviera** [comment]
https://github.com/freedomofpress/securedrop-client/pull/547 added support for communication between the sd-svs and sd-export-usb VMs, so adding print support to the client means:

* Enabling the `PRINT` button in the GUI
* Adding a "Preparing printer" placeholder screen for running preflight checks like we have for exporting to the usb disk drive.
* Adding placeholder messaging that handles printer status codes (see https://github.com/freedomofpress/securedrop-export/blob/master/README.md):
```
3. `printer-test`: prints a test page that returns:
    - `ERROR_PRINTER_NOT_FOUND` if no printer is connected
    - `ERROR_PRINTER_NOT_SUPPORTED` if the printer is not currently supported by the export script
    - `ERROR_PRINTER_DRIVER_UNAVAILABLE` if the printer driver is not available
    - `ERROR_PRINTER_INSTALL` If there is an error installing the printer
    - `ERROR_PRINT` if there is an error printing

4. `printer`: sends files to printer that returns:
    - `ERROR_PRINTER_NOT_FOUND` if no printer is connected
    - `ERROR_PRINTER_NOT_SUPPORTED` if the printer is not currently supported by the export script
    - `ERROR_PRINTER_DRIVER_UNAVAILABLE` if the printer driver is not available
    - `ERROR_PRINTER_INSTALL` If there is an error installing the printer
    - `ERROR_PRINT` if there is an error printing
```

**Comment by creviera** [comment]
Completion of this issue is blocked until https://github.com/freedomofpress/securedrop-export/issues/23 is implemented.
