### ISSUE TITLE
Dev script fails on first run in Qubes

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#482]
## Description

Missing users table error on first run of the client in Qubes.

## STR 1

Run script fails on first run in Qubes:

1. create the virtual environment and pip install dev-requirements.txt.
2. execute `./run.sh`

#### Expected
login window opens

#### Actual
`slite.OperationalError: no such table: users`

**Comment by redshiftzero** [comment]
is this using a tmp dir for sdc-home?

**Comment by conorsch** [comment]
> slite.OperationalError: no such table: users

Sounds like a race condition given the backgrounded tasks at the `wait` action. As currently written:

https://github.com/freedomofpress/securedrop-client/blob/d255fc9c7e8cbc93e26146769a365bcdc0a4e656/run.sh#L37-L44

the create-dev-data task and the app start will run nearly simultaneously. The latter half of commit e9159077f9f0e01c236e8339e43f7150614ac573 also made the `exec` call backgrounded, dropping the & and setting the `wait` call to _before_ the `exec` of the app start should resolve.
