### ISSUE TITLE
Client crashes on logout if server is gone (dev env)

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#488]
## Steps to reproduce

1. Launch development environment
2. Log in with client
3. Stop development environment
4. Log out with client

## Expected behavior

A friendly error message, encouraging the user to not give up hope

## Actual behavior

Client crash:

```
Traceback (most recent call last):
  File "/home/erik/Code/securedrop-client/securedrop_client/gui/widgets.py", line 516, in _on_logout_triggered
    self.controller.logout()
  File "/home/erik/Code/securedrop-client/securedrop_client/logic.py", line 471, in logout
    self.call_api(self.api.logout,
AttributeError: 'API' object has no attribute 'logout'
```

**Comment by redshiftzero** [comment]
what version of securedrop-sdk are you using?

**Comment by eloquence** [comment]
Looks like that was it, I was still on `pipenv` using 0.0.9.
