### ISSUE TITLE
Support qubes-split-gpg with run.sh in qubes

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-client#497]
https://github.com/freedomofpress/securedrop-client/pull/490/files introduced the ability to open submissions in disposable VMs within a Qubes development environment. An extra step would be to support qubes-split-gpg from the development environment.

**Comment by eloquence** [comment]
Closing this for now; we agreed in 3/29 backlog review that it makes more sense to focus on re-assessing the overall developer experience in Qubes (we mostly use the `python -m securedrop_client` method to test with `sd-gpg`). 

See also #507 for improvements to the run script.
