### ISSUE TITLE
UI polishing for empty conversation view

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#509]
## Description

Polish EmptyConversationView after there is more design clarity on how it should be positioned and adjust with window size changes.

Right now we have the following Zeplin screens with fixed pixel widths instead of percentages, which is actually what we want to use but is apparently not supported in Zeplin:

* https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5ceed1e215e53e1b4487ba40
* https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cfe9244f033df15f09e72ec

Instead of using Zeplin, we can discuss how this should be positioned, specific percentages or pixel values, etc. here in this ticket.

**Comment by eloquence** [comment]
In the current implementation, the empty state text has a fixed width, but is always centered in the conversation view. If we want to tweak this further, we need to come up with a clear specification, but no action necessarily required at this time.
