### ISSUE TITLE
Add transparency to SourceList and ConversationView

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#512]
## Description

The SourceList is programmed to have a background-color of #fff (white). This matches the Zeplin screens, however it has come up during a design review that the background-color should actually be a bit transparent in order to pick up the color of the widget behind it. So the color should remain white, but have an opacity value of around 0.8. The view_holder that holds the conversation view should have an opacity value of 0 (completely transparent) so that it completely shows the background of the underlying widget. When a source is selected, it should change the opacity to 0 also to show the underlying background color.

**Comment by ninavizz** [comment]
Not _entirely_ sure what the above describes, but just so it's clear (cuz Zeplin is not entirely awesome at translating my Sketch files... which also sometimes don't reflect how something is to be implemented): 
- When there are _Sources_ populating the _Source List_ container, each un-selected _Source_ has a background color of #FFF @ 100%. 
- When selected, that should be #FFF @ 0%. 
- On _Empty_ mode, however, the _Source List_  container should have one giant block of #FFF @ 40% in it, with the fadie-lines implying slots for non-existing _Sources_. 
   - I may need to create art for the latter, for you. 

Happy to discuss more in a 1:1 or forthcoming Monday Meeting.

**Comment by creviera** [comment]
Moved this issue to a new issue in the UX repo (https://github.com/freedomofpress/securedrop-ux/issues/115) so that we can have more discussions with Nina around this idea.
