### ISSUE TITLE
Logout and display login dialog if token is invalid/expired

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#517]
## Description

The queue should pause if it ever hits an auth error because it means the user token expired or is invalidated.

This will require the user to log out and log back in again.

**Comment by creviera** [comment]
To clarify, currently the queue pauses if the token is invalid, but we need to automatically log the user out and display a customized version of the Login UI indicating that they have been logged out and should login again (or continue in offline mode).

**Comment by creviera** [comment]
Also, here is a useful and relevant comment made by @emkll:

> The client does not automatically logout when it has not been in communication with the server for more than the token duration (8h). The assumption that the Client with continuously refresh with the server.
> 
> Steps to reproduce:
> 1. log into the client
> 2. Disable network to client (sd-whonix or the whole computer, or put it to sleep)
> 3. wait 8h00m01s for the token to expire
> 3. Observe 403's in the client logs, but the client always is logged in locally
> 
> This should not happen in normal situations, only if there's an network outage (no communication to the server for 8h)). 
> 
> In the current format (where the client does not encrypt submission for at-rest-storage) there isn't a very significant impact. However this will pose an issue if #552 is implemented
>

**Comment by redshiftzero** [comment]
resolved in #750
