### ISSUE TITLE
Update star icon

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#523]
# Description

- star should be vertically centered with source name
- replace star with inventory list star

**Comment by creviera** [comment]
Also:
- update selected color: #2a319d and unselected color: #d3d8ea

**Comment by ninavizz** [comment]
Red lines indicate the "visual grid" for aligning all the top items in the Source widgets. :)
![image](https://user-images.githubusercontent.com/8262612/62657697-ef351600-b91b-11e9-91b3-dbaf4885b1ab.png)
