### ISSUE TITLE
Inventory and review warning/error messages

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#53]
While we have plenty of time to iterate on error/warning messages for various situations (connection/credential failures, decryption failures, handler application failures, etc.), we should build an initial inventory so we can review them from a UX and security perspective. There may be some intersection with audit concerns, especially where there's an underlying user / sysadmin error, or a security concern the user should be aware of.

I will take a first stab at this, starting from what's in the current client code and the user stories required for the alpha, so we can kick this around asynchronously.

**Comment by eloquence** [comment]
WIP here, this is based on the current client UI, will add more based on missing user stories and review/iterate with @ninavizz:
https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbYQxpO2-U/edit#gid=0

**Comment by ninavizz** [comment]
I created this a month ago—might it be relevant? Yet to complete for the next release of the web UI. https://docs.google.com/spreadsheets/d/1POYRsmSyHIuf7F6Wx2sXP3Y-Szrg4ECCsXRV_b2HZo4/edit?usp=sharing

**Comment by eloquence** [comment]
A few immediate changes we identified as a round 2 of updates:

- For now, we should use "Two-Factor Code" and not "Two-Factor Number", just like in the web UI. 
- Like the web UI, the client should remind the user to wait for a new 2FA code after an authentication failure.
- We'll come up with a friendlier message for "Failed to apply" (starring failure).

Will submit a PR along these lines.

**Comment by eloquence** [comment]
I've pulled the current status and error messages into this document and simplified the spreadsheet a bit:

https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbYQxpO2-U/edit#gid=0

@ninavizz, please suggest any further edits in the "Proposed change" column. I've highlighted in yellow messages where I'm not 100% clear about the current client behavior and would appreciate clarification from Jen or Allie.

**Comment by eloquence** [comment]
Note: I'll make one more PR for the small dialog text tweaks in this spreadsheet. Further inventory/updates can be done post-beta.

**Comment by eloquence** [comment]
Closing this out now; we can open a new clearly scoped issue when we do additional review here.
