### ISSUE TITLE
Need a pending source deletion state

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#534]
# Description

When you tell the client to delete a source from the source list in qubes, it takes a while before it actually happens, so it would be helpful the uesr to show an activity message or some kind of pending state.

Once we have a pending state, we can readd a failed deletion job back to the queue on timeout so it will be retried after the connection issue is fixed. This is because it'll be more apparent to the user that the deletion is pending. For other errors we will display the error message "Failed to delete source at server" which could use a rewrite to be more user-friendly.

**Comment by eloquence** [comment]
@ninavizz has done some UX exploration on this, I believe the solution we settled on was to try for a placeholder screen in the conversation area similar to the "Nothing to see here" one we show on first-run of the client.

**Comment by ninavizz** [comment]
## Deletion Flow
_Note: Some of the below states and screens reflect post-Beta additions._
- [Zeplin Screens](https://app.zeplin.io/project/5c807ea562f734bd2756b243/dashboard?seid=5e3207a42b5bdc7f2045c05c)
- Delete button hover
  - The delete button as shown, I don't believe is in the current client, nor is it scoped-in as a priority for Beta. As such, ignore if tpr
- In Progress deletion
  - Selected source
  - Not-selected source
  - Note: Use same spinner created for Download, but size according to this Zeplin thingy

**Comment by eloquence** [comment]
Thanks, @ninavizz. That's a great starting point to arrive at a scope sufficient to address this issue for beta.

I believe [this screen](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5e32070a7b308098eb1cfa52) is very close to what we ultimately want. I do worry about the complexity of the alpha overlay. We'd have to ensure that no interaction with any of the clickable elements for a source in this mode is possible, and we'd probably want to disable all hover/active states as well.

I would love an assessment from one of the implementers on the complexity of the **alpha overlay** portion:

![Screenshot from 2020-01-29 15-42-38](https://user-images.githubusercontent.com/213636/73407472-13135c00-42ae-11ea-98c8-8c5c4575965e.png)

Regarding the **source list portion**:

![Screenshot from 2020-01-29 15-39-33](https://user-images.githubusercontent.com/213636/73407394-cfb8ed80-42ad-11ea-9cee-771e04fbb3f5.png)

I'm not sure that removing the source name for a source whose deletion is in progress is a good idea. That makes it impossible for the journalist to know exactly what's being deleted if they switch away from the source. I would prefer to keep the designation visible in the list.

I think the simplest possible iteration would be:
- Use the preview snippet area to hold a "*Marked for deletion*"
- If the user selects the source, show content similar to the conversation area content of the [empty state screen](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cfe9244f033df15f09e72ec). The text could say something to this effect: "Marked for deletion. This source will be removed once it has been deleted on the server".

**Comment by eloquence** [comment]
@creviera @redshiftzero Any thoughts on the implementation complexity of the translucent overlay "pending state" design for the conversation area, highlighted in the comment immediately above? My fear is that ensuring that all states are correctly disabled (including hover states for buttons, reply box "send" button, etc.) while a source is in "pending delete" mode could turn out to be pretty complex.

Do you think it would make sense do a time-boxed investigation of that translucent overlay, or would you prefer for @ninavizz to design a simpler iteration more like the text placeholder we put in the conversation area when there are no sources yet?

**Comment by creviera** [comment]
>   * Use the preview snippet area to hold a "Deletion in progress" text

:+1: 

>   * If the user selects the source, show content similar to the conversation area content of the empty state screen. The text could say something to this effect: "Deletion in progress. This source will be removed once it has been deleted on the server".

:+1:


> Do you think it would make sense do a time-boxed investigation of that translucent overlay, or would you prefer for @ninavizz to design a simpler iteration more like the text placeholder we put in the conversation area when there are no sources yet?

I think this should be investigated post-beta

**Comment by eloquence** [comment]
@ninavizz will take a stab at a more minimalist design and we can decide if we can still realistically implement a version of this, which may be important for deletion to behave in a consistent way that's not confusing.

**Comment by ninavizz** [comment]
Per today's UX meeting, below is the solution for Beta that was discussed.
[Zeplin, here](https://zpl.io/bP8NoZm).

Mockup reflects updated styling to the `No Source Selected` screen, as a generalized template for empty screens. Since the `No Source Selected` screen is shown just after this one when the deleted source is still selected, it'd be extra awesome if that transition could be [as elegant as the Invision here suggests](https://invis.io/VUWAHO38DR6)*... but, as always, totally understood if that's not in the cards given all the other priorities. :)

NOTE: Invision has no hotspots, click on a screen and navigate w/ cursor keys.

![image](https://user-images.githubusercontent.com/8262612/76025774-73677000-5ee2-11ea-9a0c-e858395032a8.png)

**Comment by creviera** [comment]
closed by https://github.com/freedomofpress/securedrop-client/pull/911
