### ISSUE TITLE
Reply box accepts rich text input

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#539]
The client currently accepts rich text input in the reply box, e.g., via copy and paste:

![Screenshot from 2019-08-19 23-48-26](https://user-images.githubusercontent.com/213636/63323963-dfcea900-c2db-11e9-949b-b482177648f8.png)

While such input will be filtered when sending a reply, it should not be accepted at all, i.e. the reply box should act similar to an HTML `<textarea>`, treating all input as plain text.

**Comment by deeplow** [comment]
This might be simple fix: `sed -i 's/QTextEdit/QPlainTextEdit/g' securedrop_client/gui/widgets.py`

**Comment by ninavizz** [comment]
@eloquence Why shouldn't this accept rich text? I could see journalists liking this bug as a feature, tbh.

**Comment by eloquence** [comment]
- HTML is less safe to deal with than plain text and creates potential injection vectors for JavaScript or other malicious code. This is probably close to a dealbreaker issue for adding such functionality unless it's critically needed.
- SecureDrop will not currently accept or render such replies and would need to be modified to do so (server-side change).
- A rich-text control without any obvious way to disable or use it (e.g., toolbar) is of dubious value and more likely to cause random surprises when copying text from other contexts (exactly like the odd random icon in that screenshot).

**Comment by ninavizz** [comment]
Cool, cool...

Your third point i was mostly curious about receiving feedback on, in the pilot; also somewhat expecting the user-surprise factor, but curious nonetheless. The first two points sound like clear dealbreakers to me, too, though... so, **_nevermind!_**

Ignore the ux kid waving her hands in the corner, and sortie-forth with debugging!
