### ISSUE TITLE
Create an offline priority queue [Discussion needed]

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#551]
## Description

We currently have a priority queue that pauses when there are network issues. There are some jobs that are non-networked jobs, e.g. exporting files to a thumb drive, that we do not want to pause. This is why I did not add a new queue job for export.

For design coherency, I think it would make sense to also have an "offline" priority queue for our tasks between non-networked VMs add to move tasks like this into jobs.

**Comment by eloquence** [comment]
Do you view this as necessary to unblock functionality or stability goals for a beta release (used in pilot newsrooms), or an architectural improvement that can wait until later?

**Comment by creviera** [comment]
:point_right: architectural improvement that can wait until later

this can be a helpful placeholder when we're ready for architecture discussions about offline mode and queue management in the client

**Comment by redshiftzero** [comment]
Provided that we block the user from triggering exports until the current export is cancelled, failed, or successful (i.e. to prevent concurrent exports), then I think we can hold off on implementing this

**Comment by creviera** [comment]
Agreed. And I just want to note that even if we decide not to support concurrent export jobs, that is, allowing the user to start another export while files are being transferred from a previous export, it still might be worthwhile to move export to an inter-vm offline queue for code consistency. Since this is pretty far out from being implemented let's leave the "Needs Discussion" tag!

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes @eloquence:
- Closing as stale.
- Let's continue to discuss concurrency considerations in the context of ongoing conversations about export/batch processing architecture.
