### ISSUE TITLE
Switching drives mid-export

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#554]
## Description

Make sure we support this use case in some way

> I wonder how realistic this case would be:
> 
>     1. user enters usb stick
> 
>     2. user prompted for passphrase
> 
>     3. passphrase incorrect, user wants to use another usb disk
> 
>     4. swaps drives
> 
> 
> The user would need to click cancel and start the export process again (this seems like an edge case)

~ @emkll

**Comment by eloquence** [comment]
@creviera will test as part of debugging https://github.com/freedomofpress/securedrop-export/issues/66; this may have been resolved via https://github.com/freedomofpress/securedrop-workstation/pull/324

**Comment by creviera** [comment]
Switching between drives mid-export works as expected: (1) when there's no drive connected, the next screen will show that you need to insert an encrypted USB drive, and (2) when a new drive is inserted, the next screen will ask to enter a passphrase for that drive.

There are several stages where things could go wrong when a user yanks out a USB drive during an export, but I think in all cases this is fine:
* While **unlocking the luks-encrypted drive**, the client will show that the passphrase did not work and ask for the user to re-enter or it will show for a split second that the passphrase did not work and then immediately show the screen that asks to insert the encrypted USB drive. In either case this is gracefully handled.
* While **mounting/unmounting the volume**, the client will show `ERROR_USB_MOUNT` along with the `lsblk` error message, and the user will have to start the export over again by clicking either "DONE" or "CANCEL". The user may continue to see this error until they manually restart `sd-devices`.
* While **transferring the submission**, the client will show the screen to insert encrypted USB drive (if the file transfer is large the client may continue to show that the transfer is in progress for a few more seconds before the new screen appears.
