### ISSUE TITLE
Add "Export Successful" message

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#556]
## Description

When an export is successful, there will be several Qubes popup notifications in the upper right-hand corner of the screen and a SecureDrop Export VM popup notification that says the export was successful.

If we want to add another message to the user that the export was successful from the client, we need to first agree on what the message should say, how it should look, and remove the popup from the Export VM.

You can see a video of a successful export and all the popups here: https://drive.google.com/file/d/19AXGtArSdYnqcDCTsBfkC6Y7R1Lz__0Z/view?usp=sharing

**Comment by redshiftzero** [comment]
sick video! so I was thinking about this while working on #561 (when I was deciding how to use a usb export success signal) - I think something in the export dialog that says "Export successful!" and then letting the user click OK to close that box might be nicer since as a user I'm conditioned to look primarily at the client UI to get feedback.

**Comment by redshiftzero** [comment]
ah right right so we have [this](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d11b947b6a1b7712ceb28f2) in zeplin:

![Screen Shot 2019-10-10 at 5 22 47 PM](https://user-images.githubusercontent.com/7832803/66607787-00500c80-eb83-11e9-9cac-a59dd2964f65.png)

**Comment by ninavizz** [comment]
Sorta revisiting this, given the new modality of the Export overlay. Will discuss tomorrow, Allie! :)

**Comment by eloquence** [comment]
We'll need to revisit this soon as the Qubes notification is going away. The above messaging/styling ("Success! `$number` file(s) saved to USB drive.") works for me.  Obviously nicer if we can have singular/plural messages.

**Comment by ninavizz** [comment]
If we can't do singular/plural, I don't think anyone would wince or be confused if we just went with plural-only `files` for Beta, then did plural/singular as an enhancement.

**Comment by eloquence** [comment]
The client does show an "export successful" message now, so closing this issue. Polish of that message is tracked in #713.
