### ISSUE TITLE
Don't close Export Dialog when the user clicks outside of it

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#557]
## Description

**Update:**
https://github.com/freedomofpress/securedrop-client/issues/557#issuecomment-544640423

~Ensure clicking outside of the overlay prompts the user with an "Are you sure?" message when a transfer is in progress. This needs further discussion since we don't have a mechanism in place for canceling an export.~

~!https://user-images.githubusercontent.com/4522213/65459966-cacac580-de05-11e9-9771-bf8f50e5f9bd.png~

**Comment by eloquence** [comment]
I think we have to distinguish clearly between:
1) An **Are you sure you want to cancel?** confirmation once the export process has started (we're past the pre-flight checks)
2) An **Are you sure you want to cancel?** confirmation in earlier stages of the process.

My sense is that 1) is almost certainly off the table, given how difficult it is to observe or control the behavior of the export VM once the process has been kicked off. Instead, it may make more sense to prevent the overlay from being dismissed during this stage.

As for 2), IMO it could make sense to prompt the user before closing the overlay **if and only if** they have entered some text or performed other steps they would otherwise have to repeat. So, if you're in the middle of typing a long passphrase, clicking outside the overlay should probably bring up the confirmation dialog.

**Comment by creviera** [comment]
#### Another idea:

Don't allow the Export Dialog to close when the user clicks outside of it at any point during the export flow.

Instead we could provide a "Cancel" button so it's more obvious to the user how to cancel export.

That means when the user is prompted to insert their USB device or to enter their passphrase and continue, they should also have a cancel option. Once the transfer begins, we can either a) keep the dialog open with an "Exporting" message until the file finishes transferring, or b) close the dialog window and display a message to the user that the export has finished.

**Comment by creviera** [comment]
To visualize this idea, run:
`--gpg-sign` when making a commit and you'll see this behavior. You'll also see how it blocks user interaction with the Terminal and other applications when prompting the user to do something. Here's the "happy path" behavior:

1. user is prompted to insert their yubikey with an option to continue or cancel
2. user inserts yubikey and clicks continue
3. user is prompted to enter their pin with a continue or cancel option
4. user enters pin and clicks continue
5. yubikey dialog immediately closes and you see yubikey flash a few times
6. user can type in the terminal and do other things before the signing finishes, but eventually (very quickly in this case) the signing finishes and the terminal shows output showing a success.

**Comment by eloquence** [comment]
> Don't allow the Export Dialog to close when the user clicks outside of it at any point during the export flow.

We discussed this today, and agreed that this is the approach we want to take. @ninavizz will propose final designs & update flows consistent with that approach.

> Once the transfer begins, we can either a) keep the dialog open with an "Exporting" message until the file finishes transferring, 

We've agreed to follow this approach for now. We can consider alternatives post-beta.

**Comment by ninavizz** [comment]
Nit: "Design" is never a plural. "Design Solutions" is the appropriate plural. 

Yes, many—too many—in tech, use the plural of "designs." Happy to engage in further chinrubbing if desired... but this'y here practitioner begs cessation of the plural of "designs."

P.S.: Yes, some designers also use this plural... but typically only the HCI-trained designers from academia, and not practitioners with actual design training. Design is a discipline, and its outputs are solutions or solution opportunities; its outputs are never "designs."

**Comment by eloquence** [comment]
"design solutions" it is :P

**Comment by creviera** [comment]
I nominate this for next sprint now that we've agreed to make this a modal instead of an overlay

**Comment by creviera** [comment]
This is a WIP, but it clearly shows that we will now show a "Done" (what I was referring to as "Continue" in previous comments) and "Cancel" option for all steps that you can cancel out of. The prep step and export-in-progress step will not have "Cancel" or "Done" options because you can't actually cancel them, but you can still "Close" the window.

[Export_MessagingDraft_Nov19-01b.pdf](https://github.com/freedomofpress/securedrop-client/files/3843475/Export_MessagingDraft_Nov19-01b.pdf)
