### ISSUE TITLE
User removes device during an export

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#559]
## Description

If the user removes the transfer device before an export operation on the Export VM, the Export dialog should prompt the user to insert their usb device, see [flowchat](https://projects.invisionapp.com/share/WKTCW3J7B34#/screens/377942793) and the green-highlighted path here: 
![Screenshot from 2019-09-23 13-47-37](https://user-images.githubusercontent.com/4522213/65461650-221e6500-de09-11e9-90fa-db98d78a1eb8.png)

If the user removes the transfer device during an export operation on the Export VM, the client will not know whether or not the transfer was complete without a return code.

**Comment by creviera** [comment]
Related: https://github.com/freedomofpress/securedrop-client/issues/554 (perhaps a duplicate)

**Comment by eloquence** [comment]
Just tested; this is the current behavior (you can remove the drive on the "Enter password" stage, and it will correctly prompt you to re-insert it).
