### ISSUE TITLE
Do not display messages until user has signed in or selected offline mode

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#56]
As indicated in the most recent [interactive wireframes](https://projects.invisionapp.com/share/R8OODHKSWY3#/screens/326526192), we don't want to show decrypted messages until the user has either signed in or selected offline mode.

The reason is that [user testing](https://github.com/freedomofpress/securedrop-ux/wiki/Qubes-Journalist-Workstation#01-oct-2nd-round-of-uxr-testing-begins) has shown that users are confused to see decrypted messages immediately appear after they launch the application. Since we haven't explained offline mode to them at this point, it's easy to misunderstand this behavior.

Instead of displaying a modal login window in front of a populated client window, we can paint the client window only after the user has either logged in or selected offline mode.

Let's use the text in the current wireframe to access offline mode ("You may also use SecureDrop offline to access messages and files that are already on this machine"), but we can skip the idea of a separate offline sign-in for now.

**Comment by ntoll** [comment]
This appears to already be the current behaviour on `master`. I'm not sure who/what PR fixed this issue (otherwise I'd reference it). But closing this since it appears fixed.
