### ISSUE TITLE
update requests to a more recent version

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#570]
I just ran the latest nightly in qubes (0.0.9-dev-20191016-060534) and got a `RequestsDependencyWarning` about urllib3 (1.24.3) or chardet (2.3.0) being not a supported version for requests. 

Checking the version of requests we're using (2.2.0), it is indeed the case that those dependencies might not work with requests: https://github.com/psf/requests/blob/v2.20.0/setup.py#L44.

Let's update requests (and depending the version of requests we bump to, we might need to update chardet also) to be a version that works well with urllib3 which was bumped to 1.24.3 since there was a CVE in earlier versions.

**Comment by eloquence** [comment]
Outdated issue; we're currently using `requests` version 2.22.0.
