### ISSUE TITLE
[ui polish] Add states (Download, Decrypt) to Files display

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#571]
## Add following states to existing display of _Files_ w/in the client's conversation pane
- [Updated Zeplin](https://zpl.io/bz6r5p3) thingy
- **Downloading**
  - Needs to show while files are downloading to the machine from SD server(s)
- **Decrypting**
  - Should always show for a set timeframe; 2-3 seconds, I suspect?
  - Does not need to map to actual decryption time; point is just to regularly reinforce to users, that this happens.
- **Opening**
   - Should show immediately after user-action to open file has been triggered; just before disp-vm begins its launch.
   - Should revert to static/downloaded state as (tbd) seconds after invoking, to allow disp-vm to launch so user is not hopelessly confused.
   - Cursor should also change to show i-bar with sand-clock thingy icon for the same duration.
   - Point is to tell user "yo, something is happening!" until visual affordance of the new disp-vm window opens atop `sd-svs` vm pane

**Comment by eloquence** [comment]
We do have a Download spinner now. I somewhat question the value of separating out the Decryption stage, but this may become more important for larger downloads in the context of #1104.

**Comment by zenmonkeykstop** [comment]
Closing - we'll revisit the UX for files in the conversation view separately. The current implementation is a bit cluttered already.
