### ISSUE TITLE
[ui polish] Sync/Timestamp widget styling/behavior

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#573]
## Mature Sync/Timestamp widget to align with UX spec
- Make spinny icon animate <3
- Add arrow/hand cursor switcheroo affordance
- Correct "nothing happening, this is the status" text color `#D3D8EA`
   - When a thing is happening, it should remain `#FFFFFF`
- Add character/letter-spacing to `Last refresh:` and active behaviors text(s)

**Comment by eloquence** [comment]
Superseded by #687
