### ISSUE TITLE
[ui polish] Global arrow/hand cursor switcheroo

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#574]
_State names based on [Mozilla's handy-dandy guide](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)_
**On Active item hover**
  - Whenever a user hovers their cursor over an active item, it should transition from `default` to `pointer` (an arrow to the mickey-mouse gloved pointy finger hand)
**On text-area hover _or_ click-into**
  - Whenever a user clicks into the _Reply_ pane (or any other dealie-o that lets them edit things) their cursor should transition from `default` to `text` (an arrow to the i-bar)
**STRETCH GOAL: Progress/Wait cursor indicators**
  - Whenever a user invokes any of the below _non-modal actions_, the cursor should transition from `default` to `progress`. Upon the activated task's completion, the cursor should return to `default`.
     - Opening a file
     - Checking the server for updates (manually invoking sync)
  - Whenever a user invokes any of the below _non-modal actions_, the cursor should transition from `default` to `wait`. When the activated task has been completed and the rest of the screen may be interacted with, the cursor should return to `default`. 
     - None, as of now. Export/Print should not do this, as that would be frightfully obnoxious.

**Comment by eloquence** [comment]
I am copying the above recommendations to #415, which this issue duplicates, and closing this.
