### ISSUE TITLE
Use `gettext` and not `_` because it's way more clear

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#58]
... especially when skimming code.

**Comment by heartsucker** [comment]
Ok, so closing this then, but I strongly disagree with what Python is doing because... yo that is is super not clear and people often use `_` for other things which would lead to possible fuck ups. Also, link to docs to satisfy my curiosity plz.

**Comment by ntoll** [comment]
Apologies: https://docs.python.org/3/library/gettext.html (see "Typical API example" for the sort of thing I'm on about). FWIW, it's a pretty common / well understood pattern for i18n in Python.

**Comment by harrislapiroff** [comment]
(I'll drop in to confirm that `gettext` is the first thing I expect a `_()` function to do when I see it in Python)
