### ISSUE TITLE
[ux polish] Launch/Window-scaling choreography

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#582]
[**»»» Reference Video «««**](https://drive.google.com/open?id=1yXXKGvH4AQFEo-os4m3KLQryCBk6LFni)

In the above video, the launch choreography between each application's `login` and `primary` panes is shown for 3 different experiences:
**1. Evernote
2. Zoom
3. Skype**

My intention when designing the 2 panes for the SecureDrop client, had been to mimic Skype's pre-Microsoft-acquisition experience. Today's Skype experience is terribly awkward, however—and I never did a recording of the pre-acquisition experience. :((

That said, my envisioned animated (insert designer doing interpretive dance here) ooh-yea kinda morphy-flow would likely be far more complicated/complex than would merit the effort—and I really like Zoom's snappy/clean experience. So: TL;DR...

## Ask
- **Have the SecureDrop client exist as a single-window experience, transitioning from the`login` to`primary` panes within the same VM window upon client launch.**
  - As an interstitial step (before scaling-up in size) when signing-in to `online mode`, the login pane should [show the dot-dot-dot animation with "Greetings, <%user_first-name%>"](https://zpl.io/bljv49P).
   - Window should increase in size from login-small to main-app large, w/o an animation.
     - Sizing increase should fill ~75-90% of the user's available desktop, as to not create kludgy confusion with how to scale-down the Qubes/Linux window size from 100% 
        - As a non-Linux user, re-sizing down from a 100% window is very confusing; and I suspect this will be the same for SD journalists, whom are also non-native Linux peeps.
        - If a user wants to juggle between multiple `export` or `disp` VMs, it's my suspicion they'll want to do this on the desktop between multiple window panes.
   - Will post an animation demonstrating precise bits, at a later date.
   - This should only ever happen upon the client's launch. 
   - Do mimic _Zoom's_ launch choreography in above video (2nd app shown)
     - ...don't mimic _Zoom's_ security properties, ahem.
- **Replace Alpha's stacked/dual-window experience.**
   - Today/Alpha has the login open in its own VM window, and then it opens the client's `primary` pane in a new VM window behind another VM window containing the `login` screen, which feels needlessly messy.
## Dependencies
- Fix bug that currently has a seconds-long delay between opening the `primary` window in `offline mode` view, and showing newly downloaded content in `online mode` view.
- Ideally, the cleaner`login` modal to sign-in from Offline mode, as [shown here](https://zpl.io/bL5MGG7) would exist... although if a single-pane dealie in Alpha would be easy, I'd be ok with the launch login showing as a modal, temporarily.
- Above window to be invoked, by clicking on `Sign In` button in offline-mode ui.

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes 
@eloquence:
- Closing as stale; we'll revisit this problem in the course of future UX reviews/discussions.
