### ISSUE TITLE
[ui polish] Offline Mode UI differences

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#583]
## Top Bar
When the client is in offline-mode, the [top bar's gradient is different](https://zpl.io/Vqv0vwJ) from when the client is in online mode. 

## Branding Bar
When the client is [in offline-mode, the SD Cube is paler](https://zpl.io/Vqv0vwJ) than [when the client is in online-mode](https://zpl.io/a7QkoEp).
- NOTE: All cube-artwork needs to be updated, and I will post artwork for both states of the branding bar, when that has been done. TBD.

**Comment by deeplow** [comment]
I am working on this
