### ISSUE TITLE
[pairing polish] Messaging Font Weight

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#588]
The text inside the message bubbles in the conversation pane was spec'd via Sketch/Zeplin to show at `400` weight, however in the code it looks heavier—despite Allie verifying it is indeed coded to spec. 

This ticket is for Nina/Allie to pair in a forthcoming co-working session to look at if `300` is a more suitable weight, or what other options might be.

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes @eloquence:
- Closing as stale, can be revisited as part of future UX reviews/discussions.
