### ISSUE TITLE
[ui polish] Selected Source Name in list

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#589]
## As it is
Currently, all source names are styled the same, in the Source List.

## Made to shine!
- [ ] Font weight should be +100 from what it is now
  - The Selected Source should be bolder than the "Read" sources, and the same weight as the "Not Read" sources; but we don't have the latter built-in yet.
   - Unsure if it's currently set to `400` or `600`; see [typography spec in styleguide](https://github.com/freedomofpress/securedrop-client/wiki/Styleguide%28ish%29#typography) for options with the font family, `Source Sans Pro`
- [ ] Color should be `filepane-blue` `#102781`

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes @eloquence:
- Closing as stale, UI has changed since this issue was filed (read/unread was added; selection styling has changed - see https://workstation.securedrop.org/en/stable/_images/screenshot_sdapp_main_view.png)
