### ISSUE TITLE
[ui polish] Star colors

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#590]
## As it is
Currently Sources in the _Source List_ follow an incorrect color convention. Starred sources are a black fill with no outline, and un-starred sources have no fill and a black outline. When this feature extends to the the _Source Header_ atop the _Conversation Pane_ for the selected source, the below will apply as well.

## Made to shine!
- SVG art, [here in the Content Inventory](https://github.com/freedomofpress/securedrop-ux/issues/17#issuecomment-472163715)
- Un-starred stars have hover states, but starred stars do not. 
- **Within the Source List,** stars should be styled...
   - [ ] [Starred](https://zpl.io/aw6K50n): `{width: 17px; height: 16px; box-shadow: 0 0 3px 0 #ffffff; background-color: #2a319d;}` <—aka `GrimaceBlue`
   - [ ] [Un-Starred](https://zpl.io/bA7pE4x): `{width: 17px; height: 16px; box-shadow: 0 0 3px 0 #ffffff; background-color: #d8d8d8;}`
   - [ ] [Un-Starred, hover](https://zpl.io/V0g0MlE): `{width: 17px; height: 16px; box-shadow: 0 0 10px 0 rgba(5, 237, 254, 0.73); border: solid 2px rgba(42, 49, 157, 0.59); background-color: #ffffff;}
   - Note: in Zeplin, only the selected Source shows the `box-shadow`, but to keep things simple it's ok if all of them have the white `box-shadow`
- Inside the **Source Header at the top of the Conversation Pane**, stars should be styled...
   - _NOTE: The below are only applicable once the Starring feature has been extended to include this location; as of the writing of this Issue, there is no starting in the Source Header._
  - [ ] [Starred](https://zpl.io/aw6K50n): `{width: 31px; height: 29px; box-shadow: 0 0 12px 0 rgba(255, 255, 255, 0.6); border: solid 1px #ffffff; background-color: GrimaceBlue;}`
  - [ ] [Un-Starred](https://zpl.io/bA7pE4x): `{width: 31px; height: 29px; box-shadow: 0 0 12px 0 rgba(255, 255, 255, 0.6); border: solid 1px #ffffff; background-color: #e3e8f8;}`
  - [ ] [Un-Starred, hover](https://zpl.io/V0g0MlE): `{width: 31px; height: 29px; box-shadow: 0 0 12px 3px #ffffff; border: solid 2px rgba(42, 49, 157, 0.53); background-color: #f8fafe;}'
  - Note: In the above Zeplin mox, the stars are two different sizes and one has a decimal value. Please follow sizing, above. As with the _Source List_ stars, both starred and un-starred inside the Source Header can maintain the white `box-shadow`.

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes @eloquence
- Closing as stale, UI has changed since this issue was filed (see e.g. #1003 #952).
