### ISSUE TITLE
[ui polish] Files display: add hover + small tidbits

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#591]
## As it is
- `SDBlue` is used for the _Print_ and _Export_ buttons, while `GrimaceBlue` is used for the filename.
- _Print_ and _Export_ are right next to each other, with only space between them.
- Neither _Print_, _Export_, nor the filename, have hover states.

## Made to shine
Per the [Zeplin spec](https://zpl.io/bo6P7Zo)...
- [ ] Change _Print_ and _Export_ to be `GrimaceBlue` when static
- [ ] Add a hover state to _Print_, _Export_, and the filename, that is `CuteBlue #05a6fe` 
- [ ] Add the `&middot;` between _Print_ and _Export_ (as shown in Zeplin) in `SDBlue`

**Comment by creviera** [comment]
in case the zeplin link isn't public yet, attaching screenshot of the image
![Screenshot from 2019-11-18 16-14-21](https://user-images.githubusercontent.com/4522213/69104865-9860d180-0a1e-11ea-8b88-b90ef3256bc9.png)

**Comment by creviera** [comment]
forgot to mention that the hoverover color (the light blue) is `#05a6fe`.

**Comment by eloquence** [comment]
(Removed mouse pointer stretch goal from issue descriptions as we consider this in scope of #415)

**Comment by eloquence** [comment]
This was closed a bit prematurely; we still need the hover state for filenames.

**Comment by eloquence** [comment]
We now have the hover state for filenames. Closing.
