### ISSUE TITLE
[ui polish] letter-spacing in reply box (offline mode)

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-client#599]
Followup issue of https://github.com/freedomofpress/securedrop-client/issues/503#issuecomment-519276447.

Description
--------------

Implement letter spacing (`0.25px`) in "Sign in" text on reply box in offline mode. ([zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cd3b87518e9f734ae0218bb))

Qt does not have the `letter-spacing` property in its CSS, but a way to overcome this is documented in https://github.com/freedomofpress/securedrop-client/issues/503#issuecomment-519276447

contributes to closing #503

**Comment by zenmonkeykstop** [comment]
Closing.
