### ISSUE TITLE
"sign-in" clickable text in reply box (offline mode)

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-client#600]
Description
--------------

Implement clickable sign-in button in the reply box as show in [zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5db224926e3b3a234108e7de).

![sign-in](https://user-images.githubusercontent.com/47065258/67858914-43622780-fb12-11e9-9618-b670095d6975.png)

**Comment by creviera** [comment]
Final offline-mode replybox design for pilot is here: https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cd3b87518e9f734ae0218bb

Note that the "Sign in" link is navy #2a319d until you hover over it and see the "cute blue" #05a6fe color with the hand icon you linked to above.

**Comment by eloquence** [comment]
Also a candidate issue for @ntoll.

**Comment by ntoll** [comment]
OK... so after some investigation here's the situation:

* The `ReplyTextEdit` widget is set as disabled when in a logged off state (so you can't type text into it - a fundamental behaviour for this aspect of the UI).
* Once in a disabled state, clicking it has no effect and Qt enforces the mouse over cursor change to an arrow (I've checked the events that are fired [or not] when in this state and tried to hack my way around this but failed).

As a result, I suggest this feature request is impossible to fulfil (i.e. mark as "won't fix") without a huge amount of work to make the UI code more complicated (something I'm keen we avoid). While we *could* do something to work around it (i.e. by completely re-writing a new widget to work in the way we need), a far easier option is to shrug and say, "well, that's just standard Qt UI behaviour" and trust folks will see the rather obvious "login" button. ;-)

**Comment by eloquence** [comment]
Leaving open for now, worth a spike; if it really is too much work, we should probably restyle the "Sign in" text because right now it is styled to look clickable. Should be considered together with the changes proposed in #593.

**Comment by zenmonkeykstop** [comment]
Closing as WONTFIX as per ntoll's analysis
