### ISSUE TITLE
Add keyboard shortcuts for sending replies

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#606]
We've [agreed](https://github.com/freedomofpress/securedrop-client/issues/572#issuecomment-545076629) that we don't want `[Enter]` to send a reply, to avoid accidental replies to sources when a journalist is composing a longer response. Instead, a user should be able to send a reply as follows:

- By clicking on the airplane (already supported)
- By pressing `[Ctrl]` + `[Enter]` (commonly used in email applications)
- By pressing `[Tab]` so the airplane is in focus, then pressing `[Space]` or `[Enter]`.

It is up to the implementer how to organize the PR(s), but this issue should only be resolved once both keyboard methods for sending a reply have been implemented.

**Comment by eloquence** [comment]
Discussed at UX meeting today; we agreed to the following:
1) While this is the intended behavior for now, we want to manage expectations for the pilot that behavior like this may change, and be responsive to user feedback. E.g., if journalists typically type short responses, `[Enter]` to send may be a better default behavior.

2) Because the `[Ctrl]` + `[Enter]` behavior is less discoverable and more platform-specific, our first priority is to get the tab selectability of controls (not limited to the "Send" button) right. If for whatever reasons implementing the `[Ctrl]` + `[Enter]` shortcut turns out to be tricky to do, it can wait til after the beta.

**Comment by kushaldas** [comment]
>Because the [Ctrl] + [Enter] behavior is less discoverable and more platform-specific, our first priority is to get the tab selectability of controls (not limited to the "Send" button) right 

Do we have any document in the UX side with numbered selection via `TAB` for the UI? @ninavizz

**Comment by ntoll** [comment]
So, I've been looking into this. In order to use `TAB` we'll need to define / set some sort of TAB order (it works just like the way you do it on the web). The various widgets which can have focus all have a `setTabOrder` method to make this work. Keyboard shortcuts are easy to implement via the `QShortcut` class.

I notice we've not used either the `setTabOrder` method nor `QShortcut` in the client yet. Ergo, I'm going to implement *something* with what I believe are "first stab" values for things like tab order.

**Comment by creviera** [comment]
I've been trained by Slack to think [Ctrl] + [Enter] adds a line break so now I never know if [Enter] or [Ctrl] + [Enter] will send a message in my email/messaging apps. I think the best way to make it easy to not use the mouse is to [Tab] to Send button then press [Enter].

**Comment by creviera** [comment]
test
