### ISSUE TITLE
Suggested improvements to OSX setup instructions

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop-client#614]
I just went through the OSX setup instructions on macOS 10.14.6. Feedback inline with the instructions below.

```
# install and select the latest version of python 3.7.x
pyenv install 3.7
pyenv local 3.7.x
```

I would suggest changing `install 3.7` to `install 3.7.x`. I was just zooming along copy-pasting shell commands and this tripped me up, since you must specify completely specify the version of python to `pyenv install`.

```
brew install pip
```

When I run `brew install pip` I get an error:

```
Error: No available formula with the name "pip"
pip is part of the python formula:
  brew install python
```

I think it's unnecessary to `brew install pip`. pip appears to be included with the pyenv shims:

```
$ which pip
/Users/garrett/.pyenv/shims/pip
```

Otherwise, the setup went smoothly and I was able to get the local Qt application running at the end. 🤘🏼

**Comment by redshiftzero** [comment]
sweet thanks for running through this - if you want to make a wee PR implementing these changes that'd be dope
