### ISSUE TITLE
Add "Speedbump" screen at beginning of Export flow

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#618]
# Description

If the `Preparing to export your file...` screen takes longer than 15 seconds display text:

> Qubes is launching the Export-VM. This can take up to 2 minutes, depending on
available system memory.

![Screenshot from 2019-11-13 12-49-30](https://user-images.githubusercontent.com/4522213/68803194-21899a00-0614-11ea-83a5-a56ed8e61d58.png)

**Comment by ninavizz** [comment]
No more timer! Instead, this will now be a "Speedbump" with a `cancel` `continue` user-triggered binary, along with the preflight being split into 2 as to not create concurrence issues (I think I got that right?).

[Zeplin Draft](https://zpl.io/blArpK5), from **24 Nov** meeting to agree on messaging and basic flow.

Text may be copy/pasted from draft. Because there is not a specific GH Issue for content, alone, I will keep the canonical source-of-truth in copyediting for these windows, in Zeplin.

**Comment by ninavizz** [comment]
...also see [This UX Repo Issue](https://github.com/freedomofpress/securedrop-ux/issues/57) as canonical source-of-truth for allthings Export.

**Comment by eloquence** [comment]
**Context:** The purpose of the speedbump is to invite users to read some instructional language that informs them about risks, _before_ pushing files to a USB drive. Therefore, it is important that the user take an affirmative step before an export starts.

>  along with the preflight being split into 2 as to not create concurrence issues (I think I got that right?).

I believe we (very briefly!) discussed the following potential split when we went over the export screens last week:

1) When the user clicks "Export" for the first time in a session, we immediately launch a command with zero side effects (think the equivalent of "what time is it?") in the `sd-export-usb` VM. This ensures that the VM is up and running as quickly as possible. As shown in your screens, they have to explicitly click "Continue" to actually initialize the export.

2) When the user clicks click "Continue", the pre-flight checks are run.

3) In subsequent "Export" actions in the same session, there is no "Cancel/Continue", and the pre-flight checks are run immediately, as shown in your screens.

Question especially for implementers: Does this split make sense? (How does Qubes handle repeated attempts to initialize a VM that's not running, i.e. if the user clicks "Continue" while the VM is still starting?) If so, is it easy enough to do that it's worth pulling into beta?

**Comment by creviera** [comment]
This is the latest design for the "Speedbump"
![preparing](https://user-images.githubusercontent.com/4522213/70943184-1eb00980-2005-11ea-9be5-47fb95d1d241.png)
