### ISSUE TITLE
Add drive name to passphrase step

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#619]
# Description

Add drive name to passphrase step.

![Screenshot from 2019-11-13 12-53-37](https://user-images.githubusercontent.com/4522213/68803475-a70d4a00-0614-11ea-8024-cb624b3474c3.png)

**Comment by eloquence** [comment]
Judging by the pink text, I believe the intent here was to reflect the drive/volume label, so I have retitled/edited the issue accordingly. This is a nice-to-have enhancement for the beta, so adding to Post-Beta milestone for now.

**Comment by creviera** [comment]
ah yes nice catch

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes @eloquence:
- Closing as stale, to revisited in the context of overall export flow conversations.
- This may not be feasible in the proposed form as the volume label is part of the information that is decrypted using the passphrase.
