### ISSUE TITLE
replybox placeholder hides when file finishes downloading

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#624]
## STR

1. Download a file and wait until it finishes

## Expected

ReplyBox placeholder shows

## Actual

ReplyBox placeholder hides

**Comment by eloquence** [comment]
Cannot reproduce in dev env. Qubes-only or resolved?

**Comment by creviera** [comment]
reported this after seeing this happen on nina's qubes laptop, so sounds like if you can't repro on a non-qubes machine, then it's qubes only

**Comment by eloquence** [comment]
(This was likely resolved - we've not seen this since it was first reported. Please re-open if you see it again.)
