### ISSUE TITLE
There should be some obvious way to give feedback to the user

### ISSUE THREAD

**Issue by ntoll** [freedomofpress/securedrop-client#63]
Sometimes, when the app is busy doing something, or some error condition has occurred there needs to be a way to indicate to the user this status update.

Some suggestions (and comments):

* Spinner / beachballs. (Fill me with dread when I see them, and they're not informative about what's going on).
* Footer containing textual status updates. Easy to implement, but can be easily missed by users.
* Alert modals. But far too clippy / interrupt-y.

Thoughts? FWIW, we do a footer in Mu (see, for instance the beginner's tutorial here: https://codewith.mu/en/tutorials/1.0/start)

**Comment by ntoll** [comment]
+1 OK... d'ya mind if I try to fix this quickly..?

**Comment by redshiftzero** [comment]
go for it!

**Comment by ninavizz** [comment]
@ntoll Working on this, right now, in the prototype. The framework as I have it does not have a footer, and I'm only hesitant seeing you put it in your footer, because I don't want technical debt created for later.

**Comment by ntoll** [comment]
Aha... right... so some of my work is blocked by not being able to signal to the user in a simple / obvious way stuff like "File download failed" etc.... Quite understand etc... adding a status bar / footer is an easy thing to do in Qt (at least something is!). ;-) Happy to be guided by you.

**Comment by ninavizz** [comment]
Yes, this is exactly what I'm working on right now. We should probs start doing daily syncs now, anyway, to chat through much of this stuff—now that you're clearly out of the Scaffolding phase and making rad headway with user-facing bits! :)

**Comment by redshiftzero** [comment]
OK @ninavizz and @ntoll and I just had a quick call about this and since the constraint is that we need to implement some simple feedback mechanism to unblock the main functionality development we are going to stick with the footer for now - we will indeed have to iterate further on the user feedback based on @ninavizz's prototype (this will happen before alpha and beta)

**Comment by ninavizz** [comment]
Seven comments on a half-hour old GitHub issue feels like a productivity record!

**Comment by ntoll** [comment]
See #65

**Comment by redshiftzero** [comment]
merged! closing for now
