### ISSUE TITLE
Sending a reply results in autoscrolling to top of conversation pane

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#635]
## STR

1. Send enough replies so that you can see the scrollbar appear in the conversation pane and see how you are autoscrolled to the top of this window. 

This code may need to be re-examined: https://github.com/freedomofpress/securedrop-client/blob/ff394d511497ff462294c5434c1ccf857e1a235f/securedrop_client/gui/widgets.py#L2179-L2181

**Comment by deeplow** [comment]
I definitely remember doing this part. The change was introduced in one of my PRs (https://github.com/freedomofpress/securedrop-client/pull/249). At the time it seemed to work, but the code was indeed a bit fragile and needs re-examining.
