### ISSUE TITLE
segfault when sd-whonix is shutdown while logged in [Buster Only]

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#636]
## STR

1. shutdown sd-proxy and sd-whonix vms while logged into the client
2. click refresh 

## Expected 

sd-whonix and sd-proxy start (takes about 30 seconds or so), sd-whonix shows that it's connecting to Tor, then sync request finishes OR the sync times out and you have to retry syncing

## Actual

sd-whonix and sd-proxy start (takes about 30 seconds or so), sd-whonix shows that it's connecting to Tor, when I click in the client it segfaults.

**Comment by eloquence** [comment]
While those VMs shouldn't be shut down, we've agreed that it warrants further investigation.  @emkll pointed out that it may be due to inconsistent use of the `SecureQLabel` class, which includes [this fix](https://github.com/freedomofpress/securedrop-client/pull/630/files#diff-b10067eb4710c24d62b7134b35c2257fR159).

We've agreed to an investigation during 12/5-12/18 sprint, timeboxed to 4 hours.

**Comment by eloquence** [comment]
I was not able to reproduce w/ December 6 nightly on Buster. sd-svs shows that it's running Buster as expected:

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

What happened for me is that I was no longer able to reliably send replies -- they seemed to get stuck in pending state -- but other operations seemed to continue to work.

**Comment by kushaldas** [comment]
Tested with today's client builds. No error/segfault. `sd-svs` is running Debian Buster. The auto-refresh or other queue operations are starting the `sd-proxy` and `sd-whonix` VMs (if they are in shutdown mode). When I tried to send in a reply, it was on the client GUI as deactivated text (grayed out), and when both the VMs started properly, it became darker black (as a successful comment).

**Comment by eloquence** [comment]
@creviera Are you still able to repro this on recent builds?

**Comment by creviera** [comment]
This no longer is happening to me either. Also on the latest. I think it's safe to close given that @kushaldas and @eloquence are not seeing the issue either. Thanks!
