### ISSUE TITLE
Gracefully handle edge case of sources without public keys

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#639]
If no keypair was generated for a source because of a low entropy pool, the client needs to gracefully handle this case. At minimum, it should not offer a reply option for this source.

This is independent of supporting "flag for reply" in the client (#247), which may be unnecessary if we can get rid of these entropy checks altogether (https://github.com/freedomofpress/securedrop/issues/1584). Even if we do, however, some news organizations may have historical sources without a corresponding public key to encrypt to, so handling this edge case in a reasonable way is a must-have change for beta.

**Comment by eloquence** [comment]
The plan of record is to eliminate "Flag for reply" and the entropy check logic, see discussion in https://github.com/freedomofpress/securedrop/issues/1584. This will likely be done _after_ SecureDrop 1.3.0.

Once this is done, there are still limited circumstances where a source may not have a keypair; most notably, if the keypair generation was interrupted by a nightly reboot. The plan of record is for the keypair to be generated _automatically_ the next time the source logs in.

To keep things simple, I propose that any UI changes should be made under the assumption that "Flag for reply" no longer exists. Instead, we simply let the journalist user know (as comprehensibly as we can) that:
- this source doesn't have a keypair yet
- they can't reply to the source until the source logs in again.

In the docs for the pilot, we can mention that sources have to be flagged manually through the web-based Journalist Interface for now.

**Comment by ninavizz** [comment]
I'd previously designed two screens for FFR, in the client:
- Journalist [needs to flag-for-reply](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cef266a0548ac04913c78c9)
- [Awaiting keypair](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cef266686ef376f60f59507)

@eloquence I'd love to chat to see how y'all feel the _Awaiting Keypair_ screen from the FFR explo, may serve as a good starting point. In a cursory look, I'm thinking that either the icon (weeble/checkmark) shd go away entirely, or be updated to not show the checkmark—as the preceding action the checkmark spoke to, now no longer exists.

**Comment by eloquence** [comment]
> I'd love to chat to see how y'all feel the Awaiting Keypair screen from the FFR explo, may serve as a good starting point.

Sounds good, we can discuss Tuesday during sprint UX review. With the necessary modifications you mention, I agree this is a good starting point.

**Comment by eloquence** [comment]
We didn't get to discuss this today; @ninavizz perhaps we can kick this around at Thursday's UX mtg.

**Comment by eloquence** [comment]
Nina and I talked about this last week; given that this is an edge case, we can stick to a very simple design here, styled similar to the one [spec'd here](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cef266686ef376f60f59507) for the "Flag for reply" use case.

However, please note these important differences:
- We will _not_ use the icon with the person and the checkmark, which doesn't make sense in this context. For now, let's stick to plain text.
- We will _not_ have a "Learn more" link just yet.

The text and styling otherwise seem fine to me: "**Awaiting action** from the source to enable replies", with the bolded text in the color seen in the Zeplin spec.

**Comment by ntoll** [comment]
If you can give me copy for the text to display when the source has no public key, then I can update the behaviour shown in the screenie below.
![Screenshot from 2020-02-03 15-42-42](https://user-images.githubusercontent.com/37602/73667314-fefba000-469b-11ea-948c-7cc5636bf82f.png)
