### ISSUE TITLE
Replies with `<>&` are escaped with HTML entities

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#645]
## STR

Send the following reply:
`hi, you & I should discuss -> signal?`

## Expected result:
Reply shows up as typed.

## Actual result:
Reply shows up as `hi, you &amp; I should discuss -&gt; signal?`

**Comment by emkll** [comment]
This was likely introduced via https://github.com/freedomofpress/securedrop-client/pull/630/commits/ab77ac7ea708d363ce71e9a9a8e3bcc5d702972b .

It seems like the easiest path to resolution would be to call `setTextFormat(Qt.PlainText)` before calling `setText` and not using html.escape. We could also consider overriding setTextFormat in SecureQLabel to prevent setting the text format to something else).

**Comment by ntoll** [comment]
See #703
