### ISSUE TITLE
"This may take a while, and it may fail server-side" <— Surfacing such things to users

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#650]
This is an epic to track all such issues, so we can consistently cross-reference.
---

All of the below scenarios are likely. They should all happen in a consistent fashion, and in a way to give users agency to make decisions accordingly. 

How can we prepare the Client for the Pilot in such a fashion that anticipates a mature handling of all the below, and working towards that for a GA release?

**Comment by eloquence** [comment]
IMO our focus for the beta should be:
- making all operations as responsive as possible
- warning the user if they attempt to exit the client with pending user-initiated operations.

If a Qubes shutdown overrides such a warning, we may also want to have a simple "pending operations" visual indicator in the UI.

**Comment by creviera** [comment]
I agree with the warning approach also mentioned here (except instead of prevention we would warn and ask the user if they are sure they want to exit with pending operations): https://github.com/freedomofpress/securedrop-client/issues/69#issuecomment-565582585

**Comment by eloquence** [comment]
Many of these issues have since been resolved, and we have separate follow-up issues such as #420. Closing.
