### ISSUE TITLE
Use decorators for failure and success callbacks

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#651]
# Description

Follow-up for https://github.com/freedomofpress/securedrop-client/pull/612#discussion_r355670574:
> create a decorator `@success_callback` and put any per-success logic in there along with our explanation of why it's needed, and then decorate any success callbacks with it. It's the same size diff, but it's a bit more extensible. We could also do the same for the failure callback to ensure that all failures have a log line (since most of our failure callbacks have a debug line to log a failure, we could put that in a generic place too to ensure that we're logging these failures).
~@redshiftzero

**Comment by eloquence** [comment]
From 2022-08-15 review with @gonzalo-bulnes 
@eloquence:
- Closing as stale, refactor target would need to be specified a bit more clearly on the basis of the current code and behavior.
