### ISSUE TITLE
[refactor] Separate MetadataSync and UserMetadataSync

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#655]
# Description

We handle errors for metadata syncs differently depending on whether or not it was user-initiated. In the future we may also change the priority of a user-initiated metadata sync vs background metadata sync, so it makes sense to create a separate job for this. Name ideas (because I love naming things): `UserMetadataSync` or `RefreshMetadataSync`

**Comment by eloquence** [comment]
This refactoring is necessary as part of the work get us to greater responsiveness for user-initiated actions and higher frequency of syncs (see #652 and #657), so added to beta milestone.

**Comment by eloquence** [comment]
Stepping back: Given the planned higher frequency of background syncs, do we want to keep user-initiated metadata syncs around at all? There was a justification for having them if the user had to wait several minutes otherwise -- but if we're basically syncing as fast as we can, constantly, there may be little value in maintaining this additional logic, and indeed, it may cause the user to waste emotional energy worrying about something the application takes care of.

**Comment by creviera** [comment]
Good question. I agree with removing this refresh feature once we increase the frequency of background syncs. Unless we want to allow an admin to configure the sync frequency so that it could potentially be >30 seconds between syncs, I think we don't need this feature.

**Comment by eloquence** [comment]
> Unless we want to allow an admin to configure the sync frequency so that it could potentially be >30 seconds between syncs

Are you thinking about that from a perspective for maintaining longer "radio silence" for security reasons? If so, I think offline mode is the better option here -- and post-beta, putting more time into making offline mode more useful seems a better investment of time to me.

@ninavizz and I discussed this a bit today, and she'll do a small exploration about the UX implications of not having user-initiated sync (e.g., does it even make sense to have a refresh icon, if we go down this route). I'll add a bit more background on #343 as well.

**Comment by redshiftzero** [comment]
Let's proceed with moving the MetadataSyncJob to a more frequent time interval (tracked in #652) and then we won't need to have User initiated syncs, so closing
