### ISSUE TITLE
Deprioritize background jobs over user-initiated actions

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#657]
To ensure the client is consistently responsive, we should always treat user-initiated actions  (replies, starring, deletion, user-initiated sync) as higher priority than background operations (currently: automatic metadata syncs and jobs it adds to the queue). 

Fully closing this issue is blocked on #655.

**Comment by eloquence** [comment]
WIP in branch: https://github.com/freedomofpress/securedrop-client/compare/deprioritize-downloads

**Comment by creviera** [comment]
the only thing we shouldn't deprioritize is `MetadataSyncJob` but looks like @redshiftzero's WIP branch doesn't do that so this is fine

**Comment by eloquence** [comment]
Added to milestone; IMO must-do for beta as part of the critical work to optimize responsiveness of the client. See #652 and #657 as well.
