### ISSUE TITLE
No longer sync on successful delete or star operation

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#658]
# Description

Now that [metadata syncs have been moved to the queue](https://github.com/freedomofpress/securedrop-client/pull/640) and are top priority, we should no longer call `sync_api` when it's not necessary. When a source successfully deletes, we should delete the source locally without calling sync_api. When a star successfully is updated, we should untoggle the star (with the current error messaging to the user) without calling sync_api.

**Comment by redshiftzero** [comment]
To redraw the UI element (e.g. the star) when this change is made, a signal should be emitted to update just the relevant widget (this is one of the reasons why sync_api is being used everywhere).

**Comment by ntoll** [comment]
OK... I'm looking at this. I've already done the star updating. Onto delete.
