### ISSUE TITLE
Hide/Show Password on Login Screen

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#659]
Picking-up on Issue #446...

## Problem
I cannot see what I am typing-in, when I type my 5-word long passphrase into the SecureDrop client. That super sucks. While the same can be said for the first dialogs on booting the machine, separate tickets are being filed with those teams (once given the green light to, of course) to request the same from them.

## Solution
One of two paths. The easiest, would be to make "Show" the one view option for passphrases on the Client. I suspect there's legit over-the-shoulder concerns for that, however—but for the Pilot, I feel we can more reasonably beat it over user heads "DO NOT use this in a cafe or other public place w/ over-the-shoulder or camera options."

The second option, of course, is to fully implement the hide/show pattern implied in the mockups. Icons for the hide/show control, are in the Content Inventory (in this repo's wiki's styleguide, and also in the Content Design ticket in the ux-repo).

**Comment by eloquence** [comment]
Note that we will likely soon want a similar widget on the export drive passphrase dialog.

**Comment by ninavizz** [comment]
@kushaldas! I added you to the Zeplin project for this, but it shows you have yet to accept that invitation. The icon asset is in the securedrop-ux repo; all icons for the Workstation are tracked [within this issue](https://github.com/freedomofpress/securedrop-ux/issues/17), which is pinned to the top of the ux repo's issues page. Let me know if you have any troubles, and enjoy your time over the US holidaze with family!

**Comment by ninavizz** [comment]
Oops—on second thought Kushal, I just noticed I have an out-dated icon in that inventory. I'll update it tomorrow (Monday) my time, with the correct art. I have a lot of clean-up to do on that table, evidently!
