### ISSUE TITLE
No longer sync on reply success

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#660]
# Description

Right now we sync the api when a reply succeeds in case we need to redraw the GUI to show messages that came in during the 5-minute sync window. Once we change the 5-minute window to something much shorter, like 15 seconds, we no longer need to worry about syncing after sending a reply. We can just refresh the GUI if we pull in any changes from the more frequent syncs.

**Comment by eloquence** [comment]
This is blocked by completion of #473.
