### ISSUE TITLE
"You must be signed in" error appears when starring source in client, even though I am signed in

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#661]
Saw this only once in client on Qubes (latest nightly), immediately after login. Since then starring actions seem to be working fine, so perhaps an issue in the initialization stage?

**Comment by creviera** [comment]
I can repro, will look into this

**Comment by redshiftzero** [comment]
Is this still an issue?

**Comment by eloquence** [comment]
Can't repro on current builds and there's been a lot of changes since this report, so I think we can close until/unless we see this again in QA.
