### ISSUE TITLE
Network error after signing out

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#662]
STR:
- Send a reply that takes a while to send (easy if you can repro #653)
- Sign out while the reply is pending

Expected result:
- (For now) Reply immediately shows up as failed
- (Likely post-beta) A prompt warning about pending operations before signing out

Actual result:
- Reply stays in pending state, and we get a "server cannot be reached" error eventually, _while the client is in offline mode_.

Screenshot:
![Screenshot_2019-12-12_20-23-52](https://user-images.githubusercontent.com/213636/70762572-d5f70880-1d05-11ea-97c0-f7e2c9b086a5.png)

**Comment by eloquence** [comment]
(Added security label in case network operations are being attempted while the user expects to be offline, which may violate their opsec expectations.)

**Comment by eloquence** [comment]
Actually also seeing this after just signing out without doing anything, so may be related to sync or other network operations as well.

**Comment by redshiftzero** [comment]
see related change in https://github.com/freedomofpress/securedrop-client/pull/404/files#diff-dfebdbc5258e6805fadd416909ed2a90R45

when we sign out we invalidate the token, but we should probably both add some additional logic around ApiInaccessibleError (right now we pause the queue which is why this "server cannot be reached" error pops up) and either empty the queue when the user signs out or stop the threads

**Comment by creviera** [comment]
> when we sign out we invalidate the token, but we should probably both add some additional logic around ApiInaccessibleError (right now we pause the queue which is why this "server cannot be reached" error pops up)

Exactly! We should just stop the "server cannot be reached" error that results from the queue being paused (intentionally by invalidating the token) if the user is signed out

>  and either empty the queue when the user signs out or stop the threads

I think emptying the queue makes sense, we already persist pending replies so these should show up as failed if the user logs back in, I believe.

**Comment by creviera** [comment]
i will work on this

**Comment by creviera** [comment]
ah yes @rmol this is closed when #750 is merged
