### ISSUE TITLE
No longer trigger sync when files are missing

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#670]
## Description

Remove the areas of the code that sync with the server when a file is unexpectedly missing, e.g.
https://github.com/freedomofpress/securedrop-client/blob/7dc80f8aa7ac0a9f55b2cb77002ac288fc9957df/securedrop_client/logic.py#L647-L649

Instead of waiting until a sync to update missing files so that they can be redownloaded by a user, do this immediately: https://github.com/freedomofpress/securedrop-client/blob/7e3cfca9eb0082a9dd71521a65de54a5e0068fb2/securedrop_client/logic.py#L425

**Comment by eloquence** [comment]
Per discussion at sprint planning today, this is blocked by completion of #473; it may make sense to wait until #288 is completed, as well.

**Comment by ntoll** [comment]
Hi, I'm blocked on starting this until my outstanding PR's relating to the two issues mentioned by @eloquence are merged. Happy to pick this up once they're merged.
