### ISSUE TITLE
Trigger sync without calling sync_api after login

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#671]
## Description

Since we want our background process to sync every 15 seconds or so (exact number of seconds TBD) and for it to be the only area of code that creates a MetadataSyncJob, we will need to remove this line of code:

https://github.com/freedomofpress/securedrop-client/blob/7dc80f8aa7ac0a9f55b2cb77002ac288fc9957df/securedrop_client/logic.py#L336

Instead we should restart the thread that periodically syncs with the server so that a MetadataSyncJob is immediately run. This helps ensure that MetadataSyncJob is only ever created in one place and only one at a time.

**Comment by eloquence** [comment]
Is this blocked on #652 or can it be done before then?

**Comment by creviera** [comment]
correct

**Comment by ntoll** [comment]
Removing this line means that upon application start, and after logging in, the user doesn't see any sources. I suggest we *definitely* want to `sync_api` on login so the user gets an accurate and up-to-date state of what's on the server.

(I'm probably missing something here)

**Comment by creviera** [comment]
The idea is to simplify our metadata sync code so that we have a continuous background thread that runs a MetadataSyncJob every X seconds. Currently we call sync_api all over the place and are trying to remove this. Instead when a user logs in, the metadata sync thread should start the background process of making calls to get metadata from the server. When the user logs out we should stop this thread. So it's just one thread, one loop, if the MetadataSyncJob fails it pauses the main and download queues, and keeps trying every X seconds (we may want to ramp down on retries in the future). When it succeeds, it resumes the queues.
