### ISSUE TITLE
Close User Auth Menu when mouse moves away

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#678]
# Description

There is a bug with the User Auth popup where it remains on top of the main window until the user clicks outside of it. A buffer is fine but it should not remain open when the user moves the mouse to a different section of the client.

**Comment by eloquence** [comment]
From 2022-08-22 review with @nathandyer @cfm @gonzalo-bulnes @eloquence:
- Closing as stale since the UX for user login has changed significantly since this was filed.
