### ISSUE TITLE
Replace refresh icon with non-interactive sync activity indicator

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#687]
- Blocked by #652, though a preliminary pass may be included as part of it.
- Blocked by UX work described in https://github.com/freedomofpress/securedrop-ux/issues/97

Since we are planning to shift from on-demand syncs to continuous syncs, it makes no sense for the refresh widget to be interactive. Instead, we just want to let the user know the following:

1) whether they're online or offline;
2) whether they're currently receiving new messages/replies;
3) (if they're offline, or network operations are paused) when the last refresh has taken place.

**Comment by ninavizz** [comment]
Item #2 from above has yet to be spec'd on the UX front, but items #1 and #3 have been [added to the UX issue](https://github.com/freedomofpress/securedrop-ux/issues/97#issuecomment-576049307). Will post here when #2 has been posted.

**Comment by eloquence** [comment]
See https://github.com/freedomofpress/securedrop-ux/issues/97#issuecomment-576891785 for proposed prioritization.

**Comment by creviera** [comment]
I'm beginning work on this one
