### ISSUE TITLE
Document sync process

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#690]
To better reason about UI & network improvements, it would be useful to have a quick write-up of what's involved in a sync operation with the server.

E.g., say that there are 300 sources with typically 3 messages, 3 files, and 3 replies on the server. Out of those 10 sources are completely new to the client.

What is the sequence of steps that the client performs:
- in order to get the initial metadata
- in order to download messages and replies it doesn't have yet?

When does the UI currently get updated during those operations?

**Comment by creviera** [comment]
Here's a start: [doc](https://docs.google.com/document/d/1Wb7OVdD6vDgAgntrB_HF2k6IeSWAdQQT8szFUroqzaY)

And see issue https://github.com/freedomofpress/securedrop-client/issues/468 where I've also documented the sync process

**Comment by eloquence** [comment]
The doc is awesome, thank you. <3 Left a couple questions there.

**Comment by creviera** [comment]
are you happy with closing this issue @eloquence ?

**Comment by eloquence** [comment]
Yes, we can close. Thanks again for putting this together. :)
