### ISSUE TITLE
Fix file widget layout

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#694]
# Description

The file widget's bar and file size are out of alignment and the download bar is now not the right width, see:
![Screenshot from 2020-01-10 14-56-52](https://user-images.githubusercontent.com/4522213/72192180-8580d280-33b9-11ea-8211-9c67b854cd9d.png)

**Comment by creviera** [comment]
Also, the spacing between file widgets grows after a download. This is a separate issue but related and also small.

STR
---
1. Send 3 files in a row as a source
2. Download each file one by one from the client and see spacing grow

**Comment by ntoll** [comment]
@creviera this is (accidentally) fixed in #702

**Comment by creviera** [comment]
hey @ntoll i missed your comment from earlier, it looks like the file widget's bar and file size are out of alignment with the export and print buttons and filename. i just tested the latest changes on `master` and it still looks like it does in the issue description. maybe it's not as obvious to others as it is to me, so here's a gif:

![Peek 2020-02-03 18-30](https://user-images.githubusercontent.com/4522213/73708553-8d2f5080-46b3-11ea-8301-3c5e1e000889.gif)

**Comment by ntoll** [comment]
@creviera hah..! I remember obsessing over lining this stuff up. I wonder what's happened..? I'll take a look and get my screen ruler out. :-)

**Comment by ntoll** [comment]
@creviera screenie of new look:

![file_hovers](https://user-images.githubusercontent.com/37602/73745143-3cb70200-474a-11ea-8471-4ed493c83271.gif)

**Comment by ninavizz** [comment]
So... I tried my best to evoke my Russian ballet teacher, with how this is spec'd. Imagine a terse woman with her hair drawn-back too tight, thwacking this mockup with a stick in-hand and occasionally barking indecipherable words atop an out of tune piano playing, as you review it. If that helps, that is. <3 

https://zpl.io/aw6K50n

Also:
- The spacing between the end of the filename and the beginning of the line, as well as between the "r" in the word SERVER and the beginning of the line, should always remain the same.

**Comment by eloquence** [comment]
See also the reports in #987, in particular, this extreme case ("1KB" trying to escape) reported by @ninavizz:

https://user-images.githubusercontent.com/8262612/77475538-381bdb00-6dd6-11ea-8ce5-cef3c4523e8b.png

Worth testing on demo instance to see if others see this issue for that source. In my own testing, behavior appears consistent _per source_, so some are better-aligned than others.

**Comment by eloquence** [comment]
I don't see more than subtle pixel differences in my non-Qubes env; this may be difficult to reproduce in its full severity without testing against a prod instance that exhibits pathological cases. Nonetheless flagging as candidate issue for @ntoll's last day.

**Comment by ntoll** [comment]
Hmm... I've had a look into this and I don't see any problems on my dev box.

As far as I can tell:

* [X] The spacing from the final word (such as "SERVER") and the line before the file size is always consistent on my machine.
* [X] Everything is aligned properly from a vertical point of view (see the very long filename in the screenie below).

Not sure what might be causing the Qubes related problem, but one though that occurred to me is that perhaps the fonts used by Qt in Qubes are different to the fonts (or different versions thereof) of those on my Ubuntu 18.04 LTS laptop. However, this definitely feels like I'm clutching at straws.

![file-lineup](https://user-images.githubusercontent.com/37602/77662264-8ca88d00-6f73-11ea-9487-5d29609cb1e8.png)
