### ISSUE TITLE
Qt error related to TAB order

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#697]
While testing a PR, on master I saw the following `Qt` error messages on the terminal.

```
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
```

The only line where we are touching TAB order is at https://github.com/freedomofpress/securedrop-client/blob/15314aeb9e2e28ad0bd7e983cfd9e232a6e32f33/securedrop_client/gui/widgets.py#L2573

## How to reproduce?

- [ ] Run securedrop-client
- [ ] click on a few sources, and then check the terminal

**Comment by redshiftzero** [comment]
duplicate of #693
