### ISSUE TITLE
Make export success message green with checkmark icon

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#713]
# Description

Followup for #666 

The "Export successful" message should be [green with a checkmark icon](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5ddc3b8b9d9aab94be0542d5): 
![Screenshot from 2020-01-21 01-18-51](https://user-images.githubusercontent.com/4522213/72791398-1f335580-3bec-11ea-8517-619a559ba721.png) (language can be updated if there is another push towards #549)

**Comment by eloquence** [comment]
From 2022-08-22 review with @nathandyer @cfm @gonzalo-bulnes @eloquence:
- Closing as stale since this does not describe the current export behavior.
