### ISSUE TITLE
No longer create and delete copies of files

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#714]
# Description

In order to open, export, or print documents we must have a file with the original filename, so we have been creating hardlinks (copies) to the file the user wishes to interact with. This has become a bit confusing because we will have two copies of the same file after an open operation. For export and print, we have a cleanup handler that deletes the copies when the operations complete, however this theoretically creates a race condition in the case that the Qt signal handler doesn't finish before say the user clicks "Print" or "Export" again for the same document. If the file still hasn't been deleted, then the check that it exists could pass and then later the client could try to access it during export and crash. I ran into this race condition before I made the fix to only allow one Print/Export dialog to be open at a time, but since signal handling is asynchronous, this race condition condition could still occur. 

I propose we first remove the signal and signal handler for deleting copies of files when the operation that uses the copy completes. Then, instead of continuing to store two copies of files whenever a user tries to open, export, or print, we would store files with the original filename on disk in the first place, after they've been downloaded.

---

### Update

I hit the race condition on `master` branch by clicking on export two times quickly.

**Comment by redshiftzero** [comment]
(haven't investigated, just noting I just hit a FileNotFoundError during review of #666 due to this)

**Comment by creviera** [comment]
ah, I forgot about  #579 and your comment:

> taking a step back: do we need these hard links? I think it's a lot easier to reason about the application's behavior if keep as much state as possible stored in the database. We could remove the hard links entirely if we:
> 
>     * modify the sync logic to not download a message or reply if `is_downloaded=True`
> 
>     * don't overwrite `filename` for objects that are downloaded since `filename` will be set to the original if extraction completes.
> 
> 
> Then the application accesses whatever is on `object.filename` for export and open. When `object_filename` is deleted, then it's gone and we don't need to clean up any hard links.

I agree, and we can move forward with this issue and close the other issue describing the problem and used for discussion.
