### ISSUE TITLE
Add debugging tips to docs

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#72]
This would massively help with debugging the app esp with calbacks and multi threading.

This function could even be something like 

```python
def log_debug(func, logger):
    if os.environ.get('SDC_DEBUG'):
        # wrap / log
    else:
        return func
```

just to completely noop this in non-dev environments.

**Comment by heartsucker** [comment]
Nice. https://docs.python.org/3/library/sys.html#sys.settrace

**Comment by ntoll** [comment]
Here's a useful trick I know... if you're just looking to drop to the debugger (pdb) try dropping these lines of code somewhere:

```
        from PyQt5.QtCore import pyqtRemoveInputHook; pyqtRemoveInputHook() 
        import pdb; pdb.set_trace() 
```

The poke away a la: https://docs.python.org/3/library/pdb.html#debugger-commands :-)
