### ISSUE TITLE
Sync removes focus from replybox

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#726]
# STR

1.  click in the reply box (you can type something or not)
2. wait until bg sync (increase frequency in the client to make this waiting period less painful or get a cup of coffee)

# Expected

For the cursor to remain in the replybox

# Actual

The replybox is no longer selected. If you were typing your have to click back into the replybox to continue typing.

**Comment by eloquence** [comment]
I was able to reproduce this easily. I only had to wait a few seconds, I think because there may have been multiple MetadataSync jobs in the queue from previous actions, and it just kept stealing the focus repeatedly.

**Comment by ntoll** [comment]
This took a little unpicking to find a simple solution. You can see WiP on my `sync-docus-replybox` (typo for `focus`). Just need to add tests for coverage.
