### ISSUE TITLE
Implement GPG home / functionality

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#73]
We need to have a GPG home dir so we can can encrypt replies to a source. This is required by the API. This blocks #16.

**Comment by redshiftzero** [comment]
want to implement this as part of #16?

(also cool to do in a separate PR)

**Comment by heartsucker** [comment]
Yeah, I think we need to do: GUI -> GPG -> API/DB wiring

**Comment by heartsucker** [comment]
Closed by #184
