### ISSUE TITLE
Speech bubbles are appearing more than once in conversation view

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#734]
## Description

I haven't been able to successfully repro, but once while testing #688 I saw speech bubbles drawn multiple times in a conversation with some reordering:

https://github.com/freedomofpress/securedrop-client/pull/688#pullrequestreview-348849771

If anyone runs into this please provide details of your steps.

**Comment by eloquence** [comment]
Did you encounter it in Qubes or in a non-Qubes dev env only?

**Comment by creviera** [comment]
I've only tested non-Qubes so far

**Comment by redshiftzero** [comment]
so - i've def seen this too, along with bubbles redrawn without their content, trying to get some STR (maybe related, maybe not)

**Comment by redshiftzero** [comment]
hard to verify due to no STR but i think this should be handled in #762 since any widgets that do not have corresponding items in the source collection will be deleted

**Comment by creviera** [comment]
i also just saw another hard-to-repro issue related to this where a speech bubble is the wrong size and out of place:

![Screenshot from 2020-02-03 19-19-28](https://user-images.githubusercontent.com/4522213/73711067-8f48dd80-46ba-11ea-8e6b-fc50984aba0d.png)

Also, it's hard to say, but I think this may have to do with the way we asynchronously update speech bubbles inline and call update_sources to update the entire source list on a successful sync.

**Comment by redshiftzero** [comment]
if anyone sees this again in the next few days please comment on this ticket, else we will close as resolved by #762

**Comment by ntoll** [comment]
I've tried to recreate the problems described here, but fail. If anyone can provide STR I'll jump right on this, but my intuition is that the recent speech-bubble / inline conversation updates changes fix / mitigate this stuff happening again.

**Comment by redshiftzero** [comment]
thanks for investigating, I still haven't seen this either in recent days, so I'm gonna close this.
