### ISSUE TITLE
Missing required package reference at the documentation

### ISSUE THREAD

**Issue by ultimatecoder** [freedomofpress/securedrop-client#74]
* **Description:** [README.md](https://github.com/freedomofpress/securedrop-client/blob/master/README.md) file is mentioning steps to make the build and run tests. It is causing a reference error if [xvfb-run](https://packages.debian.org/sid/xvfb) package is not installed. The package **xvfb-run** is part of [xvfb](https://packages.debian.org/sid/xvfb) package. The documentation should mention [xvfb](https://packages.debian.org/sid/xvfb) as prerequisite for running the tests.

**Comment by ntoll** [comment]
Duplicate of #84.
