### ISSUE TITLE
Blank client during large metadata sync when client starts up

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#745]
# Description

Since the sync icon only plays for 2 seconds, a large metadata sync, where there is actually a lot of new information, takes anywhere between 3 to 40 seconds (40 seconds is our current timeout) looks like this static image the whole time:
![Screenshot from 2020-01-29 11-34-49](https://user-images.githubusercontent.com/4522213/73390759-a0918480-428b-11ea-9d43-fef7e819d505.png)

We might want to consider adding a message in the conversation view to say "hold tight" or something. We also could show the active sync animation as soon as we realize there's new information on the server. This needs discussion, but it would be useful to only play the sync animation when there is new information and to continue showing it as active until the sync is complete. If there is not new information, we shouldn't show the animation at all.

**Comment by eloquence** [comment]
We were previously showing the "Content will appear soon" placeholder text in the conversation area, do we have a regression there?

**Comment by creviera** [comment]
Ah perhaps this is a regression, we do have a "Nothing to see just yet!" message in the client. This should be a quick fix.

**Comment by creviera** [comment]
# STR:

1. NUM_SOURCES=200 make dev
2. start the client after 200 sources have been added to the local db

## Expected

To see a populated source list with "Select a source" message

## Actual 

Blank screen until metadata sync completes

# STR 2: 

1. connect the client to a server with 200 sources
2. make sure all sources are removed from the local database
3. start the client

## Expected

To see a blank source list with "Nothing to see just yet" message until the metadata sync completes, in which case we switch to seeing "Select a source" message

## Actual

Blank screen until metadata sync completes
