### ISSUE TITLE
Client should check for new messages in background

### ISSUE THREAD

**Issue by ultimatecoder** [freedomofpress/securedrop-client#75]
Problem: A Journalist is logged in and playing with existing messages. During that time if a Source is posting a new message or sharing a document, The journalist will not be notified for it. The only way to get those messages/documents is by doing re-login to the client.

Userstory: As a Journalist, I would expect SecureDrop client to check for new messages automatically in background and display when available.

**Comment by ninavizz** [comment]
See "Clickable Interaction Patterns." https://github.com/freedomofpress/securedrop-ux/wiki/Qubes-Journalist-Workstation#production-things

The "Activity Messaging" item demonstrates the app opening (click the desktop icon, then 'Sign In'). Tentatively, the top-left messaging pattern shown in the prototype for when the app opens, I also think would work well to surface the background task activity you're proposing here. Thoughts?

**Comment by ntoll** [comment]
LGTM. Click on the "Refresh" button to kick off a sync, right..?

**Comment by ultimatecoder** [comment]
@ninavizz The prototype is great! It is such an impressive that went through it multiple times initially when you shared.

Sync with a refresh button is not looking like a good option to be honest. To me, this client application is similar to Signal app or Inbox of email (preferably web). Does a User click a refresh buttons for getting new mails/messages? No! The app server push new things to a client. Even showing last sync when user isn't interested in being offline is unappropriated. At present, automatically firing a pull request at short interval can replicate the sync behavior. In the future, there are other ways to solves this. I am not investing my energy to explain them in detail here. Thanks!

_Note: On my comments, I assume Network (Tor) is not too much slow for our Journalist._

**Comment by ninavizz** [comment]
So, to clarify—users in testing have demonstrated a desire to see a "Refresh" button there. 

As with GMail, there's a sense of reassurance that the manual option is there. It's nice to have the option to check one's email 2 minutes after the last automated every-10-minutes background fetch. Much as that's appeasing an irrational emotional need, it's still assuaging user anxiety... which while irrational, is important. Especially in high security contexts. Kind of like an elevator's "Close" button. 

That's literally the only reason it exists. Does that make sense @ultimatecoder?

The idea has **_not_** been to depend upon manual syncs, but to rather do syncs automatically—to train users to expect these automated syncs with the persistent activity messaging—and then next to that messaging, having available to them a button to repeat that behavior as-needed. @ntoll Does that make sense?

**Comment by redshiftzero** [comment]
the email comparison makes a lot of sense to me, thanks for the explanation @ninavizz :)

So @ntoll added functionality to automatically sync every 5 minutes in #87 :tada:

@joshuathayer has a refresh button in a branch (want to make a separate PR with the refresh button @joshuathayer?) then I think we can close this ticket.

**Comment by ninavizz** [comment]
5 minutes is a great refresh timbox, all sounds good! :)
