### ISSUE TITLE
SourceList is displaying Rich formatted text

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#751]
The sourcelist is showing the richtext as in the message text. The difference can be seen between the last message at right and the message below the source codename in the left.

![bold_text](https://user-images.githubusercontent.com/272303/73426483-78bd2200-435a-11ea-83b5-77db532c5909.png)

**Comment by eloquence** [comment]
This should have been resolved by #720. I don't see it in a non-Qubes dev env running `master`:

![Screenshot from 2020-01-30 00-58-23](https://user-images.githubusercontent.com/213636/73434562-d0787080-42fb-11ea-9d27-c7b3dececaf6.png)

What environment & commit hash are you testing in?

**Comment by kushaldas** [comment]
I was testing a PR, and yes, I can not see this in the other PR I am testing. I will close this after I test in master.

**Comment by kushaldas** [comment]
Closing as this is fixed as shown in the above comment in the master branch.
