### ISSUE TITLE
downloading animation never ends if the file cannot be decrypted

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#754]
# STR

1. Click on "Download" next to a file that you know will fail to decrypt with `gpg --decrypt filepath` because of a bad key, missing encrypted file in the expected filepath, etc. For repro purposes I suggest raising CryptoError during the decryption step of a file.

# Expected

"Failed to download" message and the "Download" button to replace "Downloading" animation

# Actual

"Failed to download" message and the "Downloading" animation continues indefinitely:

![Peek 2020-01-31 14-44](https://user-images.githubusercontent.com/4522213/73579760-3538e580-4438-11ea-89f1-6ce650a03ab8.gif)

**Comment by redshiftzero** [comment]
@rmol started working on this today

**Comment by creviera** [comment]
A recent change that was merged to `master` made it so that the downloading animation never ends, even if the file is successfully downloaded and decrypted.

**Comment by creviera** [comment]
Actually I decided to make a issue, because it looks like the issue started when we mismatched the slot and signal signatures, which the open PR fixes.

**Comment by rmol** [comment]
The animation problem was because we used to use a timer to start the animation, and if the download process finished before the animation started, regardless of success or failure, the stop request happened early so the animation kept going.

This was fixed in #768.
