### ISSUE TITLE
Checking for existing gpg keys causes frequent keyring popups

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#757]
# Description

"Keyring access from domain: sd-app" popup appears every time we sync. Once you see this every 15 seconds you stop closing the popup window and just expect it to be there the entire online lifetime of the client.

**Comment by eloquence** [comment]
Why does the client have to access the keyring every time we sync, even if there are no changes?

**Comment by creviera** [comment]
Ah, it looks like this is the result of making a call to https://github.com/freedomofpress/securedrop-client/blob/078c3d036e31c1de8e9fa77fb8c147d2b1691da5/securedrop_client/crypto.py#L149 in order to make sure we don't import fingerprints that have already been imported.

**Comment by eloquence** [comment]
Per @creviera the now highly frequent popups are extremely distracting. The high frequency also diminishes the value of these notifications as a security feature. Tracking as release blocker.

Per comment by @redshiftzero in standup today, if we set the fingerprint after successful key import, then we can only import key (i.e. access gpg keyring) if fingerprint column is null, which should reduce `sd-gpg` access to a reasonable level.
