### ISSUE TITLE
Downloaded files removed when updated

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#758]
Yesterday (Sat 01 Feb) I updated my Workstation for the first time in at least a few days. 

a) The updating process took over 20min, and checking for updates took around 5min or more, which could have been because of the wifi at FOSDEM... but E2E it took what felt like for-ever. 

b) When I finally did open my client, all the files I'd previously downloaded needed to be re-downloaded. Like, the client wiped their presence on the machine from my GUI. I don't know if the files may still be on the machine somewhere (I should learn how to search for them using the command-line), but the GUI showed they were no longer there. 

Is there a way to check to see if the files are still on the machine? If I try to download a redundant file, will that break things? Will try to find out during breakfast, regardless... filing this but now, tho, so I don't forget. Will edit all of this to be less babbly, once I have more info. Ta!

**Comment by redshiftzero** [comment]
possibly due to no data migration performed during the file/folder refactor in #737? in prod files/folders won't just disappear like that (because we'll do the migration)

**Comment by eloquence** [comment]
If caused by #737 this is safe to close (devs will have to re-download). Keeping open for a few days in case folks encounter it in other contexts.
