### ISSUE TITLE
Replies aren't updating as successful once sent

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#766]
## STR

0. send reply
1. see it as pending

## expected behavior

once reply sends successfully, reply updates to its confirmed (not grayed out/pending) state

## actual behavior

reply does _not_ update when successfully sent and stays in the pending state

**Comment by creviera** [comment]
looks like `pending replies->failed replies` works, but i also see `pending replies->successful replies` not working. i wonder if the `reply_ready` signal is no longer being emitted from the reply job handler

**Comment by redshiftzero** [comment]
just discussed this one with @creviera and it turns out that this is a bug that was introduced due to the close merge of two PRs modifying related logic (and our no rebase/retest before final merge policy, which is primarily for dev agility): the snippets PR (#752) and my PR from yesterday (#764).
