### ISSUE TITLE
securedrop-client qrexec is giving vchan errors

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#782]
In the `securedrop-client 0.0.13-dev-20200207-060113` and also the previous build, while running on the Qubes system, I can see the follow error coming after some random minutes:

```
Error while vchan send, exiting
```

**Comment by redshiftzero** [comment]
yep i've seen this too, it's https://github.com/QubesOS/qubes-issues/issues/5597

**Comment by redshiftzero** [comment]
resolved upstream
