### ISSUE TITLE
Download icon flickers when mousing over spinner

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#791]
When you mouse over an active "Downloading" spinner, the "Download" icon ![Screenshot from 2020-02-10 09-31-08](https://user-images.githubusercontent.com/213636/74174141-47f5ac00-4be8-11ea-8036-2df6586352d3.png) briefly flickers into view.

# STR

1. Download a sufficiently large file for the spinner to run for a while
2. Mouse over spinner

# Expected result

Nothing

# Actual result

Download icon briefly flickers into view

# Test environment

Reproduced with latest `master` on Ubuntu and with latest nightly in Qubes

**Comment by ntoll** [comment]
Sounds like an event handler is firing (on mouse_over) which changes the download icon, only to be swiftly updated by the next animation frame.
