### ISSUE TITLE
Filename Hover State

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#795]
## Thing
After a file has been downloaded to the Workstation, a user can click on it to open it in a disp-VM. 

## Not Quite Right
When the user hovers their cursor over a file that can be opened, that file's text should turn light-blue and mimick the hover-state coloring of the words "Download" and "Print" and "Export." If the cursor changes states, that should be reflected, too (which I only state as a question, because I do not know where that is at with Qubes-vs-QT at the moment).

**Comment by creviera** [comment]
Here are some images of the not-quite-right behavior:

![Screenshot from 2020-02-11 09-58-27](https://user-images.githubusercontent.com/4522213/74266680-8c9d4800-4cb9-11ea-9402-bcaf1158e159.png)


And, if the file is missing and needs to be redownloaded the icon remains in a highlighted state even without mousing over it:

![Screenshot from 2020-02-11 10-01-02](https://user-images.githubusercontent.com/4522213/74266733-a6d72600-4cb9-11ea-91f8-e08fba4ba4a2.png)

**Comment by eloquence** [comment]
The issue body and the first comment by Allie describe different issues.

The hover state on filenames works as expected for me in latest `master`.

I can reproduce the issue with the download icons that Allie's screenshots document.

Unless I'm missing something, will refactor into a new issue for clarity.

**Comment by eloquence** [comment]
(Closing and reopening w/ correct issue body for clarity)
