### ISSUE TITLE
Investigate race condition with deletion, other possible race conditions

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#797]
# Description

Race conditions can be hard to create reproducible STRs for, so I'm opening this issue for possible race conditions that need STRs.

**Comment by creviera** [comment]
```
0. New source submits message A. 
1. Sync occurs in client. Journalist sees message A.
2. Source submits message B.
3. Journalist simultaneously deletes the source while the sync begins. Deletion completes as it occurs independently of the sync, but by this time the sync has collected the list of new messages, which includes message B.
4. Source is gone, yet the logic in the sync will attempt to add message B which corresponds to a source that is deleted.

Solution: we ensure that we discard messages, files, submissions corresponding to sources that have been deleted
```
~ redshiftzero

**Comment by creviera** [comment]
Here's a new issue to look into:
1. Journalist sends a reply to a source
2. Right at the beginning of `SendReplyJob` being processed, journalist deletes the source locally
3. The reply sends: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/api_jobs/uploads.py#L50 but the source is deleted so creating a new reply in the replies table and updating the draft will fail. I think the GUI will not reflect that the draft does not exist until the next sync.

**Comment by rmol** [comment]
We should probably make new issues for each race we find, instead of keeping this one open for the life of the project.

**Comment by creviera** [comment]
i think we can move higher level overview of possible race conditions here: https://docs.google.com/spreadsheets/d/1tP0LNCzg_hS0Uy49ZxFAqCsreJEP6OL05JkYhkokOnY/edit#gid=0

**Comment by eloquence** [comment]
Thanks for putting that spreadsheet together, Allie. We're all very busy especially right now, but I agree with you that it makes sense to have deeper architectural discussions more often. 

Next week we'll have one about template consolidation, but soon after that, perhaps we can have a chat about client/server synchronization, thread safety & future-proofing the client against race conditions? Closing this issue for now but tentatively tracking this under "Discussion Points".
