### ISSUE TITLE
after X continued failed metadata syncs, we need to raise an alert to the user

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#798]
On `master` there is a bug where after _any_ failed metadata sync (this will be fixed with securedrop-sdk 0.0.13 as the issue was in the SDK logic) we raise the login window. Once that's resolved, the behavior we will have is the following:

1. Metadata sync fails transparently to the user and gets retried. We now go to either 2a or 2b.

2a. Metadata sync then succeeds, all is well.

2b. Metadata sync continues to fail. User will only get the retry / paused behavior if the user _then_ tries to take an action using the two main queues.

We need to limit the number of times (or the amount of time) that a metadata sync can fail in a transparent manner such that the user gets the retry window when they likely _do_ need to take action: plug back in their network cable or whatever has gone wrong with their network connection. 

Suggestion: modify the number of retries here https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/sync.py#L118 and modify the failure signal behavior in the case of RequestTimeoutError

**Comment by creviera** [comment]
> On master there is a bug where after any failed metadata sync (this will be fixed with securedrop-sdk 0.0.13 as the issue was in the SDK logic) we raise the login window

Just want to note that once the client uses the latest SDK with the fix, this code in the client on `master` will just work (nothing needs to change here):
https://github.com/freedomofpress/securedrop-client/blob/29880419ba4f55b7f26f2c79f8c08ccf782fe5f8/securedrop_client/logic.py#L446-L457

**Comment by creviera** [comment]
(in the client we only ask the user to reauthenticate when we see an ApiInaccessibleError)

**Comment by creviera** [comment]
> 2b. Metadata sync continues to fail. User will only get the retry / paused behavior if the user then tries to take an action using the two main queues.

True, the metadata sync background thread silently "pings" the server every 15 seconds

> We need to limit the number of times (or the amount of time) that a metadata sync can fail in a transparent manner such that the user gets the retry window when they likely do need to take action: plug back in their network cable or whatever has gone wrong with their network connection.

Agreed, and it would be useful to determine whether or not we're seeing repeated `ConnectTimeout` errors vs `ReadTimeout` errors, because one means we can't connect to the server at all.
