### ISSUE TITLE
message bubbles don't expand

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#799]
message bubbles (I saw this for replies at least) don't expand when the content exceeds the size of the bubble, it is instead truncated

**Comment by eloquence** [comment]
Tracked as release blocker because truncation may suggest loss of information to the user.

**Comment by creviera** [comment]
I'm unable to repro, so if someone else can thoroughly check that a speech bubble doesn't expand for replies (also check messages while you're at it) then I think we can close this issue. Here's an example of what I'm seeing:
![Screenshot from 2020-02-18 14-05-03](https://user-images.githubusercontent.com/4522213/74782208-dd7fe400-5257-11ea-8697-d7987cc8150d.png)

**Comment by redshiftzero** [comment]
Hmm so I don't have solid STR, but I see this intermittently still on latest `master` in non-Qubes:

<img width="1033" alt="Screen Shot 2020-02-19 at 5 01 17 PM" src="https://user-images.githubusercontent.com/7832803/74880885-3de75200-533a-11ea-80d5-6c67e6e3d01b.png">

**Comment by eloquence** [comment]
Can't repro in Ubuntu dev env:

![Screenshot from 2020-02-19 16-54-20](https://user-images.githubusercontent.com/213636/74890300-7f76fd80-5338-11ea-83c5-59df8fc17e7e.png)

**Comment by creviera** [comment]
Here's an STR for a similar issue:

1. Send a reply 100+ characters long

# Expected

The word to be wrapped across multiple lines with an indicator of wrapping or a horizontal scrollbar

# Actual

We cut off the word after around 97 characters

**Comment by creviera** [comment]
Another STR for a different but related issue (this is for the preview of text):

1. Send a reply less than 120 characters but 4 lines long, e.g. 
> one
> two
> three
> four

# Expected

three lines in the preview with a `...`

# Actual

Four lines in the preview, which looks a bit crowded 

(minor issue but worth reporting)

**Comment by kushaldas** [comment]
![truncated_reply_reproduced](https://user-images.githubusercontent.com/272303/75041994-b63d4700-54e3-11ea-9364-e3bfe4fa350a.png)

I created the reply with `python3 -c "print('A' * 300)"`
I think this should be counted as a proof of the error.

**Comment by creviera** [comment]
^ yup that confirms the [related issue ](https://github.com/freedomofpress/securedrop-client/issues/799#issuecomment-589306571) but not the original issue reported here by @redshiftzero where the speech bubble doesn't entirely resize top to bottom to fit its content: https://github.com/freedomofpress/securedrop-client/issues/799#issuecomment-588496583

even though i can't repro, i wonder, since it's an intermittent issue, if it's because we are redrawing the speech bubble at the same time we are updating the text in the speech bubble

**Comment by eloquence** [comment]
![Screenshot from 2020-02-24 12-30-57](https://user-images.githubusercontent.com/213636/75188741-88354e00-5701-11ea-9fb2-86d10499e9fc.png)

Possibly related, seeing some extra special behavior in (Ubuntu/Docker) dev env today. This is after a sync, where a file and a message was added for an existing source.

**Comment by creviera** [comment]
ah this reminds me of what i saw when i did a bunch of testing here https://github.com/freedomofpress/securedrop-client/pull/688#pullrequestreview-344138660

the issue had to do with the way ConversationView widgets (the message and reply speech bubbles) were being added/ reordered using the new index variable inline

**Comment by creviera** [comment]
i'll try to repro by selecting a source and sending multiple messages in one sync to that source so that the GUI has to append multiple message widgets... it looks like you saw this behavior without having to send replies, so i'll just focus on messages for now

**Comment by creviera** [comment]
@eloquence I've tried many different scenarios and cannot come up with an STR for what you saw here: https://github.com/freedomofpress/securedrop-client/issues/799#issuecomment-590534638

I think the only two takeaways from this issue so far are these two STRs, which I'll create issues for:

* https://github.com/freedomofpress/securedrop-client/issues/799#issuecomment-589306571
* https://github.com/freedomofpress/securedrop-client/issues/799#issuecomment-589320591

**Comment by eloquence** [comment]
I've not been able to repro either, even when nuking dev env while keeping client DB unchanged. Will keep an eye on it.

**Comment by creviera** [comment]
Feel free to create a separate issue since I do believe it's a different issue than what @redshiftzero reported here. We can track these issues even without STRs.

**Comment by eloquence** [comment]
@redshiftzero since we've been unable to reproduce the _original_ issue (as opposed to long text truncation, tracked in #815), what do you think about deprioritizing this for now, and seeing if we can reproduce during the QA stage, while pulling in #815 for immediate work?

**Comment by redshiftzero** [comment]
yep, closing this in favor of those followups
