### ISSUE TITLE
Only the download icon is higlighted in hover state

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#804]
(Originally captured by @creviera in #795):

Here is what you see when you mouse over a "Download" icon or label:

![Screenshot from 2020-02-11 09-58-27](https://user-images.githubusercontent.com/4522213/74266680-8c9d4800-4cb9-11ea-9402-bcaf1158e159.png)

This is a bug; both the icon and the label should be highlighted.

And, if the file is missing and needs to be redownloaded, the icon remains in a highlighted state even without mousing over it:

![Screenshot from 2020-02-11 10-01-02](https://user-images.githubusercontent.com/4522213/74266733-a6d72600-4cb9-11ea-91f8-e08fba4ba4a2.png)

**Comment by ntoll** [comment]
Hmmm... I'm sure this was fixed in an earlier PR. I guess it's a regression. Will take a look.

**Comment by ntoll** [comment]
OK... the CSS isn't getting picked up. Not sure why, but will figure something out.

**Comment by ntoll** [comment]
Here's the problem line: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L2015 PR coming in a moment.
