### ISSUE TITLE
File widget doesn't update to "Download" link after deleting file in `sd-app`

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#808]
# STR

1. download a file
2. delete it
3. wait until next sync and see source list update to `<Encrypted file on server>`

# Expected

during step 3, we should see the file widget in the conversation view also update to provide a "Download" link

# Actual

during step 3 the file widget does not show the "Download" link

**Comment by eloquence** [comment]
Thanks @creviera. This is clearly a bug, but I would consider all issues with files that are manually deleted in `sd-app` to not be release showstoppers, as that is not officially supported behavior. Does that make sense, or are there circumstances where this is likely to arise during ordinary use of the client?

**Comment by creviera** [comment]
Since it's an edge case I agree. It might be easier to fix now since it is a regression.

**Comment by eloquence** [comment]
(Given the number of sprint commitments, I've not officially pulled this into the 2/20-3/4 sprint, a good candidate to pull in when we start transitioning to QA / feature freeze.)
