### ISSUE TITLE
Standardize connection errors to "Trying to reconnect" language without Retry

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#811]
## Description

We've agreed to the following changes to network error handling:

- All network-related errors (connection errors or timeouts) should display the same error message. If the error message is already being displayed, no change to the message is necessary.

- The error message should _not_ display a "Retry" link, as the client will automatically and continuously attempt to restore connectivity.

- The message should be changed to make that clearer. "The SecureDrop server cannot be reached. Trying to reconnect." sounds reasonable, but we can use this issue to kick around exact language and UI display.

- The message should _not_ be ephemeral; it should continue to be the only message displayed until connectivity is restored.

## Motivation

- There is message display contention between multiple places in the client that can trigger messages to the same effect for the same reason. In other words, an "operation failed" message can compete with a "network down" message (not the actual wording in the client).
- Offering a "Retry" button that may disappear at any time -- including while the user is attempting to click it -- is confusing.
- The exact behavior of "Retry" is not always clear.

## Out of scope for this issue:

- Any changes to the sync widget or the top bar of the client (e.g., offline mode styling)
- Any changes to what actions are available to the user in the client (e.g., preventing the user from sending additional replies)

**Comment by eloquence** [comment]
I'm not labeling this a release blocker just yet as the behavior is confusing but not completely broken, especially once #604 (which I've marked as a release blocker) is fixed. However, I would recommend that it should at least be a very high priority once other client blockers are resolved.

#798 is related to this; once the message is standardized, the MetadataSync can be another way to trigger it if it's not already being displayed.

**Comment by creviera** [comment]
Resolving this issue will also resolve https://github.com/freedomofpress/securedrop-client/issues/676

**Comment by eloquence** [comment]
@creviera I still see "Failed to update star" as a special case error message e.g. if I take down the server while the client is running. Should that also trigger the "Trying to reconnect" error or is there a reason why it shouldn't?

**Comment by eloquence** [comment]
I'm reopening this issue since we still have two cases where we want to display "Trying to reconnect" i there is a connection error:
- If a starring operation failed due to a connection error and is being retried
- If a deletion operation failed due to a connection error and is being retried.

**Comment by creviera** [comment]
> I'm reopening this issue since we still have two cases where we want to display "Trying to reconnect" if there is a connection error:
> - If a starring operation failed due to a connection error and is being retried

This will be resolved in https://github.com/freedomofpress/securedrop-client/pull/952 and will close this issue.

> - If a deletion operation failed due to a connection error and is being retried.

This was resolved in https://github.com/freedomofpress/securedrop-client/pull/879
