### ISSUE TITLE
Preview sometimes 4 lines instead of 3

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#816]
# STR

1. Send a reply less than 180 characters but 4 lines long, e.g. 
> one
> two
> three
> four

OR 
1. Send a reply with word wrapping on one line that is more than 120 characters long, e.g.

![Screenshot from 2020-02-20 13-21-01](https://user-images.githubusercontent.com/4522213/74979635-df76ae00-53e3-11ea-8260-fff4e1293042.png)

# Expected

three lines in the preview with a `...`

# Actual

Four lines in the preview, which looks a bit crowded

**Comment by eloquence** [comment]
Reproduced with the following test submission:

```
In Xanadu did Kubla Khan
A stately pleasure-dome decree:
Where Alph, the sacred river, ran
Through caverns measureless to man
   Down to a sunless sea.
```

The parts of characters below the baseline also got cut off a bit, e.g., the loop in the letter "g".

**Comment by eloquence** [comment]
It's now always one line, so this issue is no longer applicable.
