### ISSUE TITLE
Iterate on user feedback for download/decrypting of files

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#82]
This is a placeholder issue for iterating on the user feedback of downloading/decrypting of messages, as I don't want @ninavizz's comment [here](https://github.com/freedomofpress/securedrop-client/issues/19#issuecomment-433253513) to get lost:

> Ok... I have no idea if this is the right place for this, but since it's just Nicholas, Jen, and I'll 'cc @heartsucker for kicks, I figured I'd quickly share before hopping off for the eve.

> https://projects.invisionapp.com/prototype/SD-IWS-DownloadDecrypt-cjnp346am00f0vk019tyfqvke/play/0cf6509e

> This prototype demonstrates activity messaging in-progress, for:
• Initial downloading/decrypting of new messages upon sign-in (just click the sign-in button on that screen, text fields don't work atm)
• Downloading and decrypting files. The 1.6mb file in the prototype for Benign Artichoke, is live.

> @heartsucker this is also a great mini-prototype instance for me to build some failed-to-send messages into... so wrt that separate ticket, I'll hop on that tonite after I'm home from class.

> Animations in this are mega-choppy via tooling limitations on my end, and because sexy transitions aren't ever really a vision I've had. Namely just wanting to get in front of users to validate contextually located messaging; but, as allthesethings are the result of user feedback thus far, I figured I'd share.

**Comment by redshiftzero** [comment]
This ticket only applies to files. Files when downloaded will proceed through the following states and should resume processing where they left off:

1. Not downloaded
2. Download started - download user feedback begins
3. Download finishes (eventually sha256sum provided in ETag is verified) - download user feedback ends
4. Decryption is attempted - decryption user feedback begins
5. Decryption is finished - decryption user feedback ends
6. "Open" is shown

(After merge of #284 and #262, the current behavior is that we proceed from step 1 directly to 6 after click.)

**Comment by eloquence** [comment]
Closing in favor of #288 for clearer scoping.
