### ISSUE TITLE
OSError when downloading files (Qubes only)

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#83]
If one is developing in Qubes using the `run.sh` script, when you download files you get:

```
'OSError: [Errno 18] Invalid cross-device link' 
```

Due to the fact that `/tmp` is on a different filesystem than `/home/user`, so we can't use `os.rename` and instead should use `shutil.move`

**Comment by heartsucker** [comment]
Does this error originate in the SDK or in the client code?

**Comment by redshiftzero** [comment]
it's in the client code [here](https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/logic.py#L362), i have this fixed in a branch on my workstation, will probably push up as part of #66 (it's a one line fix, just wanted to alert others developing to this bug in case they hit it)
