### ISSUE TITLE
Implement LogIn overlay from Offline Mode

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#852]
## Problem
Login from Sign Out mode currently opens the launch login pane in a separate dialog window. It should instead prompt an overlay, positioned in place over the Auth Widget.

## Solution
- [On Open](https://zpl.io/bL5MGG7)
  - _Note: Implement with standardized spinner over Login button, not the dot-dot-dot over to the left._
- [Error State](.)

**Comment by zenmonkeykstop** [comment]
Closing as wontfix.
