### ISSUE TITLE
Filename truncation

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#854]
## Problem
Crazy-long filenames currently wrap. If insaaaaanely filenames were likely to be common, that would be great—however crazy (vs insaaaaaaanely) long filenames will more likely be common—and as such, a wrap will more likely display as a widow, than a complete 2 lines of text.

## Solution
[This is a screen](https://zpl.io/aw6K50n) that shows a truncated filename, displayed. On hover, the tooltip should display the complete filename.

## Afterward
This does not feel like a pre-Beta priority, if getting the hover/tooltip bit right would take too long.

**Comment by eloquence** [comment]
A first iteration on truncation/tooltips is in fact part of #840 per https://github.com/freedomofpress/securedrop-client/pull/840#issuecomment-594215486 . We can aim to transition from the native yellow tooltip styling to SecureDrop styling post-beta, but that should be tracked as a separate issue. This issue can be resolved by #840.
