### ISSUE TITLE
[0.2.1-deb] Reply seems to disappear

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#861]
Encountered [during QA](https://github.com/freedomofpress/securedrop-workstation/issues/484).

This one's _very_ elusive.

## STR:

1. Log into the client
2. Send a reply to a source you've ever replied to before

## Expected behavior

The reply sends.

## Actual behavior

If I remember correctly, I saw the reply briefly appear, before disappearing. It re-appeared after the next sync.

**Comment by redshiftzero** [comment]
When you saw this do you remember if the reply confirmed as successful, and then disappeared? Or did it disappear while in the pending state?

**Comment by eloquence** [comment]
I _think_ it appeared successful at first, but I could be wrong - I'll pay closer attention to the state changes if I manage to repro it again.

**Comment by creviera** [comment]
so I've been unable to repro this, but one thing I recommend trying is to increase sync frequency and also try adding sleeps in the reply job in various places inside api_call and in the synchronization code that runs after getting new metadata sync data.

**Comment by redshiftzero** [comment]
I think this one would have been resolved by https://github.com/freedomofpress/securedrop-client/pull/937, please reopen if you see it again
