### ISSUE TITLE
New source never transitions out of "Awaiting key" state

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#862]
Encountered [during QA](https://github.com/freedomofpress/securedrop-workstation/issues/484). Intermittent.

## STR
1. Create new sources until you hit the "Awaiting key" issue for the source.
2. Wait until the next sync.

## Expected behavior

A key is eventually fetched for the source

## Actual behavior

The source never changes state. Other sources work fine, but the original source remains in the "Awaiting key" state. **Logging out and back in resolves.**

## Note

#830 recently touched this area of the code to resolve #803.

**Comment by eloquence** [comment]
Observing this again, with slightly different STR. 

Environment type: Qubes prod
Client version: 0.2.0
Workstation version: 0.3.0
Server version: 1.4.0~rc1

STR:
1) Populate a staging environment with a large number of sources (I had >300)
2) Delete all of them in a batch
3) Create a new source through the SUI
4) Client crashes upon sync (could be related to #906)
5) When client restarts, it never successfully fetches the key for the new source

Even deleting the client database and syncing from scratch had no effect; this one source continues to be broken. Will poke a bit more at logs tomorrow and try to get a clean repro.

**Comment by zenmonkeykstop** [comment]
Closing - we don't believe this is reproducible given server (Sequoia) and client changes since.
