### ISSUE TITLE
UI Polish: Source List item typesetting 

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#867]
## Problem
Current "Source List item" widget in Client is a touch too tall, and they typesetting not quite right. Much as I'd love to categorize this under "nina's a PITA" the typography was very carefully done to consider legibility needs, in addition to stuffing the most amount of information possible into the total height of the screen. As such, I'd love for the below to get implemented.

## Solution
_In the below screenshot, all lowercase letters refer to items on my "should be" mockup, and upper-case letters are for the screenshot of the client as it is coded today. [Zeplin page](https://zpl.io/VQ8JXxP) for linespacing/padding/size/etc values, here._ 

- [ ] **The Selected Source name** should be `filepane-blue` aka `#102781` and semi-bold weight (number for code [is 600, per this](https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat:600)—and also [FYI this page](https://github.com/freedomofpress/securedrop-client/wiki/Styleguide%28ish%29) for reference with coding weight designations with Google Fonts).
- [ ] Reduce **Source widget height**. See pale pink rectangles on the below spec; both highlight the differences in height between a screenshot of the coded client, and my mockup. The two are center-aligned to the `hr` between the two Source list items. 
- [ ] **A: Star/Name Alignment** should be middle-aligned, not top-aligned. Not sure it that'd be easiest achieved with 2px of padding atop the Source name, or if they can be center aligned.
- [ ] **B: Date Alignment** should always be top-aligned with the top line of the snippet/preview text. Whether or not there is a paperclip icon to indicate there are files, it should never move. That spot for the paperclip should always be either blank, or occupied. 
- [ ] **C: Padding between Source Name and Preview** should be reduced. It is currently too big.
- [ ] <strike><b>D: Preview Text Linespacing</b> needs to be increased. [My Zeplin](https://zpl.io/VQ8JXxP) says `1.5em` and Allie wasn't able to get it to work in the QT code before she merged the current code. </strike>

![image](https://user-images.githubusercontent.com/8262612/75932542-8586d700-5e2c-11ea-933d-85991c486474.png)

**Comment by ninavizz** [comment]
Created item #959 to address the linespacing... perhaps @ntoll cd tackle the other items on this list? @eloquence? Will add the coloration of the date and Source Name on-hover, to this, too.

**Comment by zenmonkeykstop** [comment]
WONTFIX, closing.
