### ISSUE TITLE
Create positionable overlays that work w/in QT

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#876]
## Problem
Inline with standard client application behavior, windows initially spec'd as Overlays were decided to be implemented as Dialogs. In a Windows or Mac environment, this would have been the right call. 

As has been observed in Qubes, however, the dialogs behave with a few Linux quirks (#826) that are likely to frustrate native Mac/Windows users (so, a majority of journalists). Likewise, the bold window framing on Qubes feels cognitively disruptive—as it removes context connecting the dialog to UI within the bigger-framed App VM. Unlikely for folks acclimated to Qubes to be bothered by this, but—that's not a majority of our users.

Finally, the contextual help built-in to the overlays cannot be done in an OS dialog. As such, we should probably migrate as many of the dialogs as we can to embedded overlays more common in web UIs, after we launch Beta. 

Hooray for "build what we think is right, but with the flexibility to change our minds," and kudos to Allie for having worked so hard on Dialogs that I feel truly awful asking to now ditch. :(

## Solution
For Delete, these are wires/mockups for [help closed](https://zpl.io/29RMvPd), and [help open](https://zpl.io/2ve8rKQ).

For a user logging in from Offline Mode, the overlay will need to [open in a fixed location on the screen](#852). How to do that, also needs to be resolved.

**Comment by zenmonkeykstop** [comment]
Marking as WONTFIX - UI concerns are valid but staying within the QT toolbox as much as we can will ease development.
