### ISSUE TITLE
 Preview sometimes cut off for long words

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#877]
# STR

1. Send a reply that has a long word or send a file that has a long filename.

# Expected

For the word to wrap so that you can see all its characters until the `...`

# Actual

The word wraps but you cannot see all its characters - they are cut off on the right side for long words.

**Comment by ntoll** [comment]
This is an interesting (!) problem for two reasons:

* We don't use a fixed width font, so line length in characters doesn't lead to a uniform line width in pixels.
* I've been playing around with the elide related settings in the `SecureQLabel` class in the hope that this will help us out. Sadly it only appears to work on single line text (and we need two lines at least, in the snippet preview version of this widget where we're using Python's built-in `textwrap` module to truncate things).

Both the `textwrap` and elide aspects of this bump into each other in ways which cause unpredictable rendering. I believe updating the `set_text` method with bespoke elide-like behaviour
is perhaps the way to go in terms of a spike.

**Comment by ntoll** [comment]
OK a quick spike gives me this:

![word_wrap](https://user-images.githubusercontent.com/37602/76537773-2e10e880-6476-11ea-8617-986099a54e41.png)

I'll push a draft PR with tests and things so folks can give feedback.
