### ISSUE TITLE
Newlines in messages/replies being dropped by textwrap.wrap

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop-client#885]
The use of `textwrap.wrap` in `SecureQLabel.setText` has brought along some undesirable default `textwrap` behavior: newlines in input text are being [replaced](https://docs.python.org/3/library/textwrap.html#textwrap.TextWrapper.replace_whitespace). The second note there suggests a solution: we could split the input on newlines and wrap each line, then recombine. 

As an illustration, this message:
![image](https://user-images.githubusercontent.com/47430598/76117142-3f12b300-5fb9-11ea-941f-dc3521013a77.png)

is rendered like this in the client now:
![image](https://user-images.githubusercontent.com/47430598/76117155-4639c100-5fb9-11ea-8350-5d07a6aeaf21.png)

We have to wrap long lines, but where possible we should preserve structure that does fit.

Related: #841

**Comment by eloquence** [comment]
Thanks @rmol! Per our discussion not tracking as release blocker, but let's still aim to fix since it's a recent regression.
