### ISSUE TITLE
[0.2.1-deb] New file widget not created for upload after file deletion

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#891]
Originally reported [here](https://github.com/freedomofpress/securedrop-workstation/issues/484#issuecomment-596011944).

## Steps to reproduce

1. Start the client and log in (run via `LOGLEVEL=DEBUG securedrop-client` in `sd-app`)
2. Load Tor Browser in `sd-proxy` and visit the Journalist Interface; log in there as well
3. Load the Source Interface in a separate tab.
4. Create a new source via the Source Interface with just a file upload.
5. Wait for the client to sync. You should see the source with the file widget.
6. Delete the _individual file_ (not the whole source) for this new source in the Journalist Interface.
7. Wait for the client to sync. 
8. You should see the empty state below (expected).
9. Upload _another_ file as the source.
10. Wait for the client to sync.

## Expected behavior

A file widget for the new file shows up in the client.

## Actual behavior

The conversation area remains empty, but the preview snippet is updated.

Restarting the client or signing out resolves; the file widget for the new file is now displayed.

## Screenshots

Empty state at step at step 8:
![Screenshot_2020-03-06_16-12-16](https://user-images.githubusercontent.com/213636/76132404-b18a8f80-5fc7-11ea-9f23-05084b342033.png)

State after sync finishes at step 10:
![Screenshot_2020-03-06_16-14-06](https://user-images.githubusercontent.com/213636/76132408-b5b6ad00-5fc7-11ea-8519-e0554cc55467.png)

Corresponding state of Journalist Interface after step 10:
![Screenshot_2020-03-06_16-28-39](https://user-images.githubusercontent.com/213636/76132415-bb13f780-5fc7-11ea-90d9-1e50e760c08b.png)

**Comment by eloquence** [comment]
(I did not notice anything in the logs other than normal sync behavior; the fact that no sync is required for the client to recover to a correct state may suggest this is purely a UI level issue.)

**Comment by redshiftzero** [comment]
Looks like this is a generic issue, we're not updating the conversation view when we sync

**Comment by redshiftzero** [comment]
Another STR:

1. Login to client, view source.
2. Delete submission via JI.
3. Wait for sync. The deleted submission does _not_ disappear.

**Comment by redshiftzero** [comment]
wip in branch `conv-view-refresh` refreshes the conversation view on the screen after a sync (to resolve the two STR here) and fixes the crasher described in [#494 (comment)](https://github.com/freedomofpress/securedrop-workstation/issues/494#issuecomment-597961125), but not the overlaid `FileWidget` yet, currently investigating that:

![Screen Shot 2020-03-13 at 5 08 30 PM](https://user-images.githubusercontent.com/7832803/76662078-5fabb180-6553-11ea-8780-0d4ebd174715.png)
