### ISSUE TITLE
No dropshadow on Export Confirm dialog

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#908]
## Problem
All the other dialog windows in the `sd-app` client have nice dropshadows on them, 'cept this one!

![image](https://user-images.githubusercontent.com/8262612/76377298-c046ae80-6307-11ea-9027-a9b0f3606019.png)

## Solution
Could be nice if they all get to match? Just a little wonky, that they don't.

**Comment by zenmonkeykstop** [comment]
Will be invalidated by upcoming export dialog changes in #1777. Closing.
