### ISSUE TITLE
Improve user expectations management w/ "Export"

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#910]
## Problem
When going to export a file, I consistently observed this screen _appear_ to freeze for 9 seconds, upon hitting submit on the passphrase for my drive. No presence of an active-state on the "Submit" button, and no confirmation that my passphrase was accepted (or being told my file is now saving to the drive), are why.

![image](https://user-images.githubusercontent.com/8262612/76592503-d17eef00-64b0-11ea-9e38-1ba8da6002a0.png)

## Solution
1. There needs to be an active-state on the buttons throughout Print and Export. 
2. Users need some indication that a passphrase was accepted or not.
3. Users also expect some indication that the machine has moved past authenticating their drive, and is actively doing the task (in this case, saving a file to a drive).

9 seconds is a lifetime to users to see, literally, nothing. 

While a confirmation screen does state that the export was successful, it concerns me that 9-seconds of nothing followed by a confirmation message, will still feel disconcerting. Especially when our users are not able to just go to a regular machine to verify the file transferred ok, and engaging an admin is required for that.

**Comment by eloquence** [comment]
Flagging for discussion, can be done asynchronously: Is this something Nick can realistically help with, or can changes to those dialogs only be tested effectively in Qubes? If Nick can't help with it, I'm afraid further improvements in this area will have to wait until all release blockers are resolved, i.e. almost certainly until after the first official beta release.

**Comment by ninavizz** [comment]
@eloquence I'm creating separate tickets for the two identified action-items this ticket identifies—the active state on print/export buttons, and the additional screen state. Art assets for both will be included in each.

**Comment by eloquence** [comment]
During QA, I'm noticing that this is particularly problematic when the user enters an incorrect passphrase, because the dialog will remain in this error state while successfully exporting:

![Screenshot_2020-03-11_16-46-07](https://user-images.githubusercontent.com/213636/76474125-df047e00-63b7-11ea-8d04-23265c10c632.png)

**Comment by ninavizz** [comment]
From today's UX meeting, I've assembled the below. 

Note, that none of the below is qualified by timing around beta, and is instead a general prioritization based on conversation around how today's experience works, abreast [ideas expressed in this pdf](https://drive.google.com/open?id=14EC6slVzsceP72mjNbmkIdqkm9Wkg4sG).

_—Discussing with Erik in a few mins, may edit after that—_

## Must
- Near-term option steps to remediate [Pane Sandwich issue](#826)
- Add an "Active State" to primary buttons
- Add a spinner w/ disabled butt to Speedbump screen
- Add 2nd state to Speedbump screen that shows "Ready" vs "Preparing To" text in H1
- Disable Password field when actively submitting pane for auth

## Should
- Update H1 texts with each state, as shown in PDF
- If "Could" cannot be done, use backup text edits to improve human-tone of text

## Could
- Rejigger layouts of Icon, H1, and Byline, to accommodate improved error message placement and subsequent tone/voice
  - Smaller icons
  - No more HR
  - Uniform pane size and slight layout tweeks, to accommodate
  - Update content to reflect new hierarchies
- Include error-icon
- Include success icon

## Won't (but wd be nice to do later)
- Include spot for stack-trace messages, beneath human writing for immediate user
  - Nice to include these for admins to see in shared Signal pix
- Kill HR on Speedbump screen, and rejigger text layout to have blue background as PDF shows, instead.

**Comment by ninavizz** [comment]
In the original comment, items n°2 and n°3 are unlikely to be addressed for the Beta release, but everything discussed in today's UX meeting and in the 3 child issues to this, should make a marked improvement. :)

**Comment by ninavizz** [comment]
All spinner art is in child issues, here. :D

**Comment by creviera** [comment]
> 1. There needs to be an active-state on the buttons throughout Print and Export. 

This was added today.

> 2. Users need some indication that a passphrase was accepted or not.

We've been showing the message "The passphrase provided did not work. Please try again." if the passphrase is not accepted and the "Export successful" screen if it is accepted. This paired with the change in #1 meets this criteria.

> 3. Users also expect some indication that the machine has moved past authenticating their drive, and is actively doing the task (in this case, saving a file to a drive).

This should be tracked separately because I think it needs ux discussion.


I think this is ready to be closed.

**Comment by zenmonkeykstop** [comment]
Fixed for export with wizard changes, will fix for print separately.
