### ISSUE TITLE
Create "Active" state for Export and Print buttons

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#912]
_Child issue w/in #910_

## Punchlist This Issue
_[Zeplin, here](https://zpl.io/VKgpODA)_ 
(note: this mockup uses screenshots w/ graphics added where things changed, so if you're confused why some text looks odd—well, that's why!)
- [ ] Add active-state to all primary buttons across flow(s)
- [ ] When re-submitting a page with an error on it, either:
   - a: Clear-out the error to return the screen to its state, or
   - b: If "a" would cause the height of the screen to shorten (because the error made the screen taller) just remove the error and show whitespace. We aim for this to be an epilepsy-free experience. :D

**Comment by ninavizz** [comment]
^ This one's also ready @ntoll! :)

**Comment by ninavizz** [comment]
I made this GIF 3-4x as big as it needs to be, so it doesn't look sucky. Let me know if you need it to be a different size!

![littlespinner-grimace](https://user-images.githubusercontent.com/8262612/76593805-849d1780-64b4-11ea-89f2-7efc8e454915.gif)

**Comment by ntoll** [comment]
@ninavizz this spinner gif stops after X number of frames. I've GIMP-ed it a bit so it spins forever... please give me a kick on here if there's anything wrong with my version:

![spinner2](https://user-images.githubusercontent.com/37602/76646295-a220be80-6552-11ea-88fa-cebdf3a3e494.gif)
