### ISSUE TITLE
When source conversation is updated, it does not float to the top of the source list

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#914]
## Description

When a source conversation is updated in the sidebar, its corresponding source widget does not move to the top of the source list.

## STR

0. Submit source A via source interface. Save the codename.
1. Submit source B via source interface. At this point source A appears below source B, as we would expect since source B was sent after source A.
2. Submit a new message as source A.

## Expected behavior

Source A now moves to the top of the source list.

## Actual behavior

Source A continues to be below source B.

**Comment by eloquence** [comment]
Hm, I think this worked in the past, sounds like a potentially significant regression in terms of surfacing new submissions to the user. Will do a quick test in Qubes + `git master` to repro.

**Comment by eloquence** [comment]
Unfortunately can still reproduce in `git master` on Qubes using those STR.

**Comment by eloquence** [comment]
@ntoll Fairly high priority bug, good candidate issue for your last day.

**Comment by ntoll** [comment]
Ack :+1:
