### ISSUE TITLE
Disable "Print" when file format is not conducive to printing

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#918]
## Problem
A bit to file in the "duh" bucket, and thus something I'm not at all worried about until the post-Pilot release...

Ya can't print a video file. Or a song, or a ZIP, an EXE, etc. As such, the obviousness of this qualifies it as a low-priority to me, at the time of this filling. 

![image](https://user-images.githubusercontent.com/8262612/76467834-c55b3a80-63a7-11ea-9b24-ffb164eeb9ee.png)

## Solution
Disable the "Print" text-link next to files that are somehow not printable; be they compressed archives, videos, audio, or any other non-printable dealie-o. On second thought, perhaps best to approach this as only _enabling_ the "Print" button to be live, for supported/known filetypes that can deal with printing. Images less than 100mb (or whatever), .doc, .pdf, .xls, .txt, etc.

**Comment by ninavizz** [comment]
[Spreadsheet here](https://docs.google.com/spreadsheets/d/1l-DGR5UnnvYA5jfeZtplER933ANPWgFLx_uWbnJZKWI/edit#gid=0), nice guide for where to do.

**Comment by gonzalo-bulnes** [comment]
Cross-referencing https://github.com/freedomofpress/securedrop-workstation/issues/842 because it is a step towards fixing this issue.
