### ISSUE TITLE
starring requiring login after already logged in

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#919]
# steps to reproduce

1. login into the client
2. star a source

# expected

for the source to star

# actual

the client says you need to log in to perform this action

looks like this was introduced here, but i cannot immediately tell why this is happening: https://github.com/freedomofpress/securedrop-client/pull/893/files

**Comment by rmol** [comment]
I can't reproduce this with current master (44b975e). I did see it earlier today, but cannot induce it now.

**Comment by redshiftzero** [comment]
I _don't_ see this on current master (28a5ce32c2741241853ab598e8a625d69a856acb) in the non-Qubes dev env

**Comment by kushaldas** [comment]
I can reproduce on master (28a5ce32c2741241853ab598e8a625d69a856acb) in non-Qube environment today. 

![star_asking_to_signin](https://user-images.githubusercontent.com/272303/76622354-5e7c8380-6557-11ea-8351-cd910c07c545.gif)

**Comment by rmol** [comment]
I've seen it! I can repro consistently with sd-app and my staging environment.
