### ISSUE TITLE
consider periodically purging encrypted content in ~/QubesIncoming/sd-proxy

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#920]
Right now downloaded (encrypted) files first are downloaded to `~/QubesIncoming/sd-proxy`, and then are moved to the relevant `~/.securedrop_client` data directory. If something goes wrong, for example, the application crashes, prior to this move action occurring, then the encrypted content can accumulate in `~/QubesIncoming/sd-proxy`. It will persist reboots. We should run a periodic cleanup action to remove this content, for example on application start.

**Comment by zenmonkeykstop** [comment]
Will be fixed in upcoming proxyv2, which streams files directly to datastore.
