### ISSUE TITLE
Snippets don't update when an item is deleted

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#922]
## STR

1. Delete the most recent item in a conversation (I did this with a source with one file)

## Expected behavior

Snippet does not continue to contain the content of the deleted item

## Actual behavior

Snippet does contain the content of the deleted item

**Comment by creviera** [comment]
Closed by https://github.com/freedomofpress/securedrop-client/pull/911, see how we now have a deletion pending state that removes the preview snippet:
![Screenshot from 2020-03-17 10-30-57](https://user-images.githubusercontent.com/4522213/76884145-721b3900-683a-11ea-9dd4-71c35bb7247f.png)

**Comment by creviera** [comment]
Reopening (didn't realize this was a bug with snippets not updating after making a change in the Journalist Interface) :bushes:
