### ISSUE TITLE
Export/Print "Speedbump" screens experience polish

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#927]
_Child issue w/in #910_

## This Issue's Punchlist
_[Zeplin, here](https://zpl.io/2vp1xmr)_
(note: this mockup uses screenshots w/ graphics added where things changed, so if you're confused why some text looks odd—well, that's why!)
- [ ] Separate single screen into 2 distinct states: "Preparing" vs "Ready"
- For _Preparing_
     - [ ] `H1` text to say 'Preparing to [print or export]'
     - [ ] Spinner at top-left instead of device icon
     - [ ] 'Continue' button is disabled
- For _Ready_
     - [ ] `H1` text to say `Ready to [print or export]`
     - [ ] Show device icon in place of spinner at top-left of screen
     - [ ] Enabled "Continue" button

## Etc
This issue is only for the functionality and two words of text, cited above. Any other inconsistencies between text between Zeplin and what's in the code, are not included in this issue.

**Comment by eloquence** [comment]
@ntoll As discussed today this may be a bit hairy to test/develop without Qubes. It's not worth trying to get you up and running in Qubes in this final stretch of your contract -- but if you can make some headway on the above w/ Qubes, please have at it :).

**Comment by ninavizz** [comment]
I can haz BIG spinner for Speedbump screen! 
See Zeplin for sizing particulars. That's one of the only actual bits in that Zeplin, that's _not_ part of a screenshot.

![bigspinner](https://user-images.githubusercontent.com/8262612/76593700-469ff380-64b4-11ea-9447-c4dfdc50ddff.gif)

**Comment by ntoll** [comment]
@ninavizz WRT the spinner... I've just noticed... but I believe it's not centred (i.e. it's not spinning around the centre) and thus wobbles. Gives me the heebie-jeebies in a motion-sickness sort of a way. :stuck_out_tongue_closed_eyes: 

The spinner in #912 looks / behaves well to me. I'll just use that. ;-)

**Comment by ninavizz** [comment]
@ntoll Thank you for catching that—reason(s) I shouldn't be delivering production assetts past my bedtime. ;)

The wobble is a Flash problem unique to how the art is configured, and quite frankly a BIG PITA when creating any circular spinner. Anywho, I've re-cut it with a hack to tone it down. When it's small as it will be in the Speedbump screen, the wobble isn't noticable. Hoping this one works for ya better—no queezies... 

![bigspinner22](https://user-images.githubusercontent.com/8262612/76651355-92d54d00-6521-11ea-950d-6d154f94da06.gif)

**Comment by ninavizz** [comment]
Oopsie... this is it! As per the other one, I cut it 3x the size it should be in the client, so it shows-up as nice and crisp when at 100%. Again: there is a visible wobble when it's this big, but it's not visible when it's the size it should be in the Speedbump screen. 

![bigspinner-smh](https://user-images.githubusercontent.com/8262612/76651710-4a6a5f00-6522-11ea-836c-d48ebadddb1e.gif)
