### ISSUE TITLE
Encrypted drive auth screen: active state

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#928]
_Child issue w/in #910_

## This issue's punchlist
_[Zeplin, here](https://zpl.io/bWEKZDj)_
(note: this mockup uses screenshots w/ graphics added where things changed, so if you're confused why some text looks odd—well, that's why!)
- [ ] Implement active state spinner w/ button styling
- [ ] Disable Password field when actively submitting pane for auths
  - This includes "fading" the label for the text field, and the bullets or text in the field
- [ ] When returning an error'd screen, return the screen to its state w/o the error

**Comment by eloquence** [comment]
@ntoll Same here, also ready for ya :)

**Comment by ninavizz** [comment]
I made this GIF 3-4x as big as it needs to be, so it doesn't look sucky. Let me know if you need it to be a different size!

![littlespinner-grimace](https://user-images.githubusercontent.com/8262612/76593805-849d1780-64b4-11ea-89f2-7efc8e454915.gif)
