### ISSUE TITLE
"Select a source" and "Deleting..." shown at the same

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#929]
# Description

Both the "Select a source" text and the "Deleting..." text are shown at the same time when you make a deletion during sync.  

We should move the "Select a source" logic from the MainView to the SourceConversationWrapper where the "Deleting..." logic is in order to make sure we only show one or the other.

# STR

1. Click on the `...` menu and select "Delete"
2. Before clicking "Yes" on the confirmation window, wait until you see the sync icon begin its animation
3. Now click "Yes"

# Expected

For the "Delete" text to be displayed.

# Actual

The "Delete" text is displayed along with the "Select a source" text.

**Comment by rmol** [comment]
I think this has been fixed by #937. I just tested again on latest master and the pending deletion state is clean.

**Comment by redshiftzero** [comment]
I also can't repro this one in normal operation of the client. Inspecting the logic - if both `SourceConversationWrapper._on_source_deletion` (which shows the "Deleting..." text after a successful deletion) and `MainView.show_sources` (during sync) are called I think we can still end up in a state where the "Deleting..." text (`SourceConversationWrapper.waiting_delete_confirmation`) appears overlaid with the `EmptyConversationView`. As a resolution, it would make sense to move the logic determining which of these views to show to one place (also it makes more sense from a dev perspective imho, but open to discussion).

**Comment by redshiftzero** [comment]
From https://github.com/freedomofpress/securedrop-client/pull/955#issuecomment-601327703: 

> I think what was happening was that the "Select a source screen" would appear after we removed the source item from the source list before we got to delete_conversation which deletes the conversation wrapper with the "Deleting" text.

**Comment by creviera** [comment]
I think we can close this because none of us seem to be able to repro.
