### ISSUE TITLE
reconnecting text gets cut off on minimized window

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#932]
# STR
 
1. Minmize the client window to its smallest width
2. Disconnect from the server by stopping apache or killing the dev container
3 Wait until you see the "reconnecting" text

# Expected

To be able to see the full "reconnecting" text

# Actual

It gets cut off right at the end.

**Comment by eloquence** [comment]
Might be a candidate issue for @ntoll if we can come up with a simple recommendation for him how to resolve.
