### ISSUE TITLE
After deletion via JI, overlapping message and file widgets stick around

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#939]
## Steps to reproduce

1. Launch a client nicely populated with sources, messages and files.
2. Delete an individual file or message via the Journalist Interface in Tor Browser
3. Wait for client to sync

## Expected behavior

Widgets for deleted messages and files are removed after a sync.

## Actual behavior

Widgets for deleted messages and files continue to be rendered in the Journalist Interface, overlapping with widgets that should exist.

## Example screenshots

from [0.2.2-deb testing](https://github.com/freedomofpress/securedrop-workstation/issues/494#issuecomment-597961125)

![broken files](https://user-images.githubusercontent.com/213636/76478420-df0b7a80-63c5-11ea-88f9-678f84c0fe0f.png)

from [0.2.2-deb testing](https://github.com/freedomofpress/securedrop-workstation/issues/494#issuecomment-598972850)

![broken messages](https://user-images.githubusercontent.com/213636/76669351-7d274e00-6548-11ea-95ed-2b541c5ae0a4.png)

from [0.2.1-deb testing](https://github.com/freedomofpress/securedrop-workstation/issues/484#issuecomment-595962314)

![broken files](https://user-images.githubusercontent.com/47430598/76121915-d8929280-5fc2-11ea-83cd-a2c6b3d977fa.png)

**Comment by eloquence** [comment]
Related: #891 and WIP here: https://github.com/freedomofpress/securedrop-client/issues/891#issuecomment-598929002

**Comment by redshiftzero** [comment]
This should be fixed by #937
