### ISSUE TITLE
Support HOTP for 2FA

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-client#94]
The SecureDrop Journalist Interfaces supports two options for 2FA:

* [TOTP (via FreeOTP, Google Authenticator, or otherwise)](https://docs.securedrop.org/en/release-0.10.0/hardware.html#usb-drive-s)
* [HOTP (e.g. via Yubikey)](https://docs.securedrop.org/en/release-0.10.0/yubikey_setup.html)

Currently the Client prototype only supports TOTP. We should add support for HOTP to ensure a smooth migration for orgs already using it. Given the Qubes model, we'll need to consider integrating with `sys-usb`, as well as configuring `dom0` RPC policies to permit the connections.

**Comment by heartsucker** [comment]
Maybe I'm missing something here, but since the check on whether or not it's TOTP/HOTP occurs server side, wouldn't that mean there's no explicit support needed in the client? Wouldn't this only be a workstation related issue where we need to ensure that Qubes attaches the USB correctly?

**Comment by redshiftzero** [comment]
^ this is correct, since the HOTP code from the yubikey is also six digits we shouldn't need additional code changes in the client provided the yubikey gets properly attached to sd-svs

Closing in favor of https://github.com/freedomofpress/securedrop-workstation/issues/317
