### ISSUE TITLE
pending status begins showing after the deletion completes

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#951]
Right now source deletion on master does the following:

1. User adds source deletion job to the queue.
2. The job runs, and once we learn from the server that the deletion job was completed, the pending status is shown. 
3. We wait for a sync to run.
4. The sync removes the source and its collection, removing the pending status.

This process nicely resolves #858. However, if a lot of network activity is happening, the pending status won't appear for a while, which means the user doesn't get feedback. I think the time to show the pending status is in step 1, when the source deletion job is added to the queue (similar to what we do for replies, where if a reply is queued to send to the server, it's in its pending state). Thoughts? 

Cross-referencing #929

**Comment by eloquence** [comment]
Yes, I was about to file the same issue. :) This would be great to clean up before launch because the current behavior feels a bit broken (though it appears to work just fine, so I won't add the `bug` label).
