### ISSUE TITLE
Stars changing state unexpectedly

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#954]
# Description

There are four main issues I came across with star behavior:

#### Issue 1
When a star job fails to send it doesn't go back to its original state:

1. Send a star and see "Failed to update star" message
2. See that the star doesn't change back to its original state

#### Issue 2
When a star succeeds it will toggle back a few seconds later and then toggle a third time after a sync (this happens more if you star a few sources and it looks very confusing):

1. Toggle the stars of a few sources
2. Wait a while for the jobs to succeed (you can add a log in the success handler)

#### Issue 3
When you toggle a star during a sync, or just after a sync, it will toggle the star back a couple seconds later (this is the familiar "ghost" issue).

1. Toggle a star when you see the sync icon flashing
2. Toggle another star shortly after the sync icon flashes
3. The stars toggle back to what they were before a few seconds later

#### Issue 4
Star jobs seem to timeout at a high rate even with the default timeout value is doubled or tripled.

**Comment by eloquence** [comment]
The behavior I see in 0.2.3-deb/0.2.3-rpm may be a combination of your issue 2 and issue 3. I am _not_ seeing your issue 4, but I have seen it in the past; in my experience the client is not as resilient against what seem to be temporary Tor network issue as Tor browser is.

If with three sources in the client, I star them top to bottom, I see state changes like this:

(initial state)
off
off
off

(after user action)
on
on
on

(over the following seconds)
on 
off
on

on
off
off

on
on
on

It would make for a nice blinkenlights installation ;)
