### ISSUE TITLE
Use pytest-flaky to retry fragile functional tests.

### ISSUE THREAD

**Issue by ntoll** [freedomofpress/securedrop-client#956]
Sometimes, on CI, our functional tests fail with errors like this:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

Such random, impossible to reproduce and frustrating errors are caused by a problematic state in the CI server, rather than with our tests. For instance, the error quoted above is due to disk read/write problems on the server.

I suggest we use [pytest-flaky](https://docs.pytest.org/en/latest/flaky.html) as a way to retry such flaky tests.

**Comment by kushaldas** [comment]
I saw the same error today:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by kushaldas** [comment]
Now I am seeing this error in all random tests in both master and while working on https://github.com/freedomofpress/securedrop-client/tree/login_via_clicking_icon_functional_test I think I should just add flaky to all tests under functional
