### ISSUE TITLE
Add background gradients

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#958]
## Problem
From @ntoll after tackling issue #865 that included this item:

> Hi @ninavizz, I just checked but the CSS capabilities in Qt can't do background image gradients: `background-image: linear-gradient(to right, #f8fefe 2%, #f3f0f9 74%, #f3f5f9 100%);`
> It can handle solid background-color specifications. 

## Solution
Qt investigation TBD

**Comment by ninavizz** [comment]
Removed "low priority" label, because in re-reading older Issues I realized that part of the rationale for the gradient in the Selected Source, was to [improve starring visibility](https://github.com/freedomofpress/securedrop-client/issues/865#issuecomment-594926581) and general legibility... so, it's not quite a LOWWWW priority, but it's not as high as other post-Beta things.

**Comment by zenmonkeykstop** [comment]
Marking as WONTFIX - if QT doesn't support it, this is low-priority. Buttt stuff like this should factor into potential future discussions of other frameworks.
