### ISSUE TITLE
How can we support message / reply threading?

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-client#96]
The client UI design assumes that we're able to thread source messages and journalist replies.

In order to do that, we need to be able to divine some reasonbale order among a set of messages and replies. 

We are able to order messages, and we're able to order replies, since the tables which store those things have an autoincrementing integer ID column (and, although the API doesn't expose those IDs directly, we can pull the ID out of the filenames the API uses to store and transmit messages and replies).

The problem is that messages and replies are stored in _different_ tables, and thus their IDs are independent, so order between messages and replies cannot be determined using that mechanism.

We also don't store wallclock time in the server database, so we can't use that time to order messages and replies.

Finally, we don't store any sore of reference between messages and replies, so we're not establishing any explicit order.

I'm not sure how to approach this problem, so I hope I'm missing something obvious :face_with_head_bandage:

**Comment by redshiftzero** [comment]
good question - I added [this attribute](https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/models.py#L41) (taken from the server side) that gives one an ordered list of the replies/messages/files associated with a given source - I _think_ that should do what you are looking for, e.g.: check out [this for loop](https://github.com/freedomofpress/securedrop-client/blob/f25cf5a8e1e8be34dcdf6c75a51b4b45454081ce/securedrop_client/gui/main.py#L168) in `show_conversation_for`

**Comment by joshuathayer** [comment]
Ah, fantastic, that's just what I was after. Thanks very much, I'll close this.
