### ISSUE TITLE
Provide explicit handing of application/x-desktop in mimeapps.list 

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-client#961]
In https://github.com/freedomofpress/securedrop-workstation/issues/494#issuecomment-601215535 , application/x-desktop files are opened in a dvm , without an explicit rule. In default VMs, they are opened in a text editor, likely because debian on qubes doesn't use all of gnome's tooling and gdm. However,  to ensure defense-in-depth, we should explicitly add the association in the `mimeapps.list`

**Comment by conorsch** [comment]
To aid in review, recall that `file` and `xdg-mime` may report different results:

```
$ file --mime-type /usr/share/applications/debian-xterm.desktop
/usr/share/applications/debian-xterm.desktop: text/plain
$ xdg-mime query filetype /usr/share/applications/debian-xterm.desktop
application/x-desktop
```

It's the latter we're trying to ensure is handled sufficient by the Client and associated tooling.
