### ISSUE TITLE
iterate on config and packaging logic

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#97]
During merge of https://github.com/freedomofpress/securedrop-client/pull/86, some [issues](https://github.com/freedomofpress/securedrop-client/pull/86#issuecomment-435094544) came up that need to be discussed and resolved prior to the beta, as beta installs may turn into officially supported long-running workstation installs. This is a placeholder issue for those discussions and we should break this ticket up into finer grained issues after the alpha. The questions that were raised include:

- should we continue to use `/usr/share` to store configs? (my view is that using `/usr/share` is fine since we can safely assume that this deb package will only be used by the default single user in a Debian based AppVM on Qubes)
- should we implement a `Config` class, see @heartsucker's comment: 

> To auto-handle configs and load a local config if present, we should probably have a Config class that does the default handling / Qubes detection. This should be injected into the app / logic / controller and passed around that way. Def do not want a global reference (because testing).

As part of this iteration on the packaging logic, we should also make sure to do a test schema change in an upgrade to ensure there are no issues with client database migrations (we also did this test back when we first added migrations support over in SecureDrop server).

**Comment by kushaldas** [comment]
>- should we continue to use /usr/share to store configs? (my view is that using /usr/share is fine since we can safely assume that this deb package will only be used by the default single user in a Debian based AppVM on Qubes)
>- should we implement a Config class, see @heartsucker's comment:

I am okay to both. 

>As part of this iteration on the packaging logic, we should also make sure to do a test schema change in an upgrade to ensure there are no issues with client database migrations (we also did this test back when we first added migrations support over in SecureDrop server).

This is also good, and we can do test based on the packages from `apt-test` repo itself.

**Comment by eloquence** [comment]
A config class was added in 63a4fada80313dc9039532015a928f39b504cdf8 and has since been in use; the other proposal is to continue doing what we're doing. Are there additional improvements that are needed, or can this issue be closed?

**Comment by redshiftzero** [comment]
yeah I think the packaging logic is pretty stable now, let's leave as is - if anyone disagrees and has a recommended change file a specific followup in securedrop-debian-packaging or here
