### ISSUE TITLE
horizontal scrollbar on source list

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#973]
# Description 

A source list with a vertical scroll bar also now has a horizontal scroll bar.

# STR

1. NUM_SOURCES=11 make dev
2. run the client

# Expected

For a vertical scrollbar to appear without a horizontal scrollbar

# Actual

A horizontal scrollbar appears

**Comment by redshiftzero** [comment]
just checked, I do see a horizontal scrollbar - this could be a good one for you @ntoll
