### ISSUE TITLE
Cancelling export in progress conflicts with subsequent export attempts

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#992]
Steps to reproduce (tested in Qubes on `master`):

1. Export a file in the client
2. While export is running, cancel.
3. Immediately export again

## Expected behavior

Export is aborted, new export completes successfully
## Actual behavior
Things get a bit wacky:
- it starts with the "Preparing to export" screen spinning for a while
- then we briefly see the "Export successful" message flash from the previous export
- then we see "Ready to export", but instead of "Continue", the primary button says "Done", and the dialog message is still the "Remember to be careful" message.

**Comment by eloquence** [comment]
Unlike the setup stage, once you submit a password, it should IMO just disable the "Cancel" button until the operation either succeeds or fails.

**Comment by eloquence** [comment]
This screenshot illustrates the final "mutant dialog" state -- note the "Ready to export" with the "Done" button and the message from the success screen.

![Screenshot_2020-03-24_19-56-03](https://user-images.githubusercontent.com/213636/77488044-7501c500-6e0a-11ea-8600-ecfb3aee10b3.png)

**Comment by ninavizz** [comment]
Yes, in the original design users were supposed to get a "Do you really wanna do this?" dialog if they tried to cancel after authenticating—and it was agreed that canceling after that stage would introduce too many complications to execute this correctly, for Beta.

**Comment by eloquence** [comment]
(Tracked as release blocker to reflect severity, we can demote to known issue if we run out of time.)
